<?php

namespace app\common\controller;

use think\Exception;
class ApiBackend extends CommonBase
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;
    // 站长ID
    protected $adminId;
    // 站长登录信息
    protected $adminInfo;
    // 用户ID
    protected $userId;
    // 用户登录信息
    protected $userInfo;
    // 网络请求
    protected $param;
    /**
     * @var \app\admin\model\AppModel|array|false|\think\Model
     */
    protected $myAppInfo;
    protected $myPowerInfo;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function userLogin(){
        try{
            $userId = cookie('userId');
            $sign = cookie('userSign');
            $this->userId = $userId;

            // 登录用户信息
            $userModel = new \app\user\model\User();
            $userInfo = $userModel->getInfo();
            if(!$userInfo){
                throw new Exception(t('user.account_abnormal').'[errorCode:UserInfoError]');
            }
            $expectedSign = data_auth_sign($userInfo['appid'].$userInfo['username'].$userInfo['password'].qh_password_hash());
            if(!empty($userId) && !hash_equals((string)$expectedSign, (string)$sign)){
                throw new Exception(t('login.user_session_expired'));
            }
            $this->userInfo = $userInfo;
            if(empty($userInfo['appid'])){
                throw new Exception(t('user.account_abnormal').'[errorCode:UserAppIdEmpty]');
            }
            if(!is_numeric($userInfo['appid']) || $userInfo['appid'] <= 0){
                throw new Exception(t('user.account_abnormal').'[errorCode:UserAppIdError]');
            }
            if($userInfo['status'] != 1){
                throw new Exception(t('user.account_blocked').'[errorCode:UserStatusBlocked]');
            }
            if(!empty($userInfo['ip'])){
                if(!in_array(get_client_ip(), qh_safe_unserialize_array($userInfo['ip']), true)){
                    throw new Exception(t('user.ip_not_whitelist'));
                }
            }
            $appModel = new \app\admin\model\AppModel();
            $this->myAppInfo = $appModel->getInfo(intval($userInfo['appid']));
            if(!$this->myAppInfo){
                throw new Exception(t('user.account_abnormal').'[errorCode:GetUserAppInfoError]');
            }
            $this->myPowerInfo = $this->getPowerPriceInfo(intval($userInfo['power']));
            if(!$this->myPowerInfo){
                throw new Exception(t('user.account_abnormal').'[errorCode:GetUserPowerInfoError]');
            }
            // 数据绑定
        }catch (\Exception $e){
            //$this->logOut();
            throw new Exception($e->getMessage());
        }
    }

    /**
     * 获取权限信息
     * @return array
     * @author 陌上花开
     * @date 2022/1/25
     */
    private function getPowerPriceInfo($id)
    {
        if(empty($id)) return false;
        $powerPriceModel = new \app\admin\model\PowerPriceModel();
        try{
            $result = $powerPriceModel->getInfo($id);
            if(!$result) return false;
            return $result;
        }catch (\Exception $e){
            return false;
        }

    }

    public function logOut(){
        cookie('userId',null);
        cookie('userSign',null);
        return message(t('login.logout_success'), true);
    }
}
