<?php
/*
* +----------------------------------------------------------------------
* | SF 综合验证授权系统
* +----------------------------------------------------------------------
* | Quotes [ 花开的再灿烂，也有凋谢的一天，致我们过去的青春 ]
* +----------------------------------------------------------------------
* | Author: 陌上花开 <2129876388@qq.com>
* +----------------------------------------------------------------------
* | Date: 2022年1月19日 18:48:32
* +----------------------------------------------------------------------
*/

namespace app\common\controller;

use think\facade\View;

/**
 * 前台控制器基类
 *
 * @author 陌上花开
 * @since 2020-04-21
 */
class Frontend extends CommonBase
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->checkMaintain();

    }


    public function checkMaintain(){
        if(conf('maintain_switch') == 1){
            if(IS_POST){
                exit(json_encode(message('站点正在维护中' ,false)));
            }
            View::config(['view_path' => config('self_template')['maintain']['view_base']]);
            exit($this->render('index/index'));
        }
    }

    /**
     * 判断站长是否登录
     * @return bool
     */
    public function isAdminLogin()
    {
        // 用户未登录返回 false
        if (empty(session('adminId'))) {
            return false;
        }
        // 用户已登录返回 true
        return true;
    }

    /**
     * 判断用户是否登录
     * @return bool
     */
    public function isUserLogin()
    {
        // 用户未登录返回 false
        if (empty(session('userId'))) {
            return false;
        }
        // 用户已登录返回 true
        return true;
    }

    /**
     * 获取App列表
     * @return array
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function getAppList()
    {
        try{
            $appModel = new \app\admin\model\AppModel();
            $result = $appModel->getAllList();
            return message('获取列表成功！', true, ['data' => $result]);
        }catch (\Exception $e){
            return message($e->getMessage(), false);
        }
    }
}