<?php
/*
* +----------------------------------------------------------------------
* | SF 综合验证授权系统
* +----------------------------------------------------------------------
* | Quotes [ 花开的再灿烂，也有凋谢的一天，致我们过去的青春 ]
* +----------------------------------------------------------------------
* | Author: 陌上花开 <2129876388@qq.com>
* +----------------------------------------------------------------------
* | Date: 2022年1月19日 18:48:32
* +----------------------------------------------------------------------
*/

namespace app\common\controller;

/**
 * 安装控制器基类
 *
 * @author 陌上花开
 * @since 2020-04-21
 */
class Install extends CommonBase
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(file_exists(APP_PATH . DS . 'install' . DS . 'SF_Auth.Lock')){
            if(IS_POST){
                exit(json_encode(message('您已经安装过，如需重新安装请删除app/install/SF_Auth.Lock文件后再安装！', false)));
            }
            exit($this->render('/public/error' ,['msg' => '您已经安装过，如需重新安装请删除app/install/SF_Auth.Lock文件后再安装！']));
        }
    }

    public function authorInfo()
    {
        return '陌上花开';
    }
}