<?php
namespace app\common\controller;

/**
 * 安装控制器基类
 *
 * @author 陌上花开
 * @since 2020-04-21
 */
class Install extends CommonBase
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(file_exists(APP_PATH . DS . 'install' . DS . 'SF_Auth.Lock')){
            if(IS_POST){
                exit(json_encode(message('您已经安装过，如需重新安装请删除app/install/SF_Auth.Lock文件后再安装！', false)));
            }
            exit($this->render('/public/error' ,['msg' => '您已经安装过，如需重新安装请删除app/install/SF_Auth.Lock文件后再安装！']));
        }
    }

    public function authorInfo()
    {
        return '陌上花开';
    }
}