<?php
namespace app\common\controller;

/**
 * 安装控制器基类
 *
 * @author 陌上花开
 * @since 2020-04-21
 */
class Install extends CommonBase
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(file_exists(APP_PATH . DS . 'install' . DS . 'SF_Auth.Lock')){
            if(IS_POST){
                exit(json_encode(message(t('install.already_installed'), false)));
            }
            exit($this->render('/public/error' ,['msg' => t('install.already_installed')]));
        }
    }

    public function authorInfo()
    {
        return '陌上花开';
    }
}
