<?php
namespace app\common\controller;

use app\common\service\BindingMailVerificationService;
use app\common\service\RateLimitService;
use think\App;
use think\Exception;
use think\facade\Event;
use think\facade\Log;
use think\facade\View;
use think\facade\Cookie;
/**
 * 系统中台控制器基类
 *
 * @author 陌上花开
 * @since 2022-01-19
 */
class UserBackend extends CommonBase
{
    // 模型
    protected $model;
    // 服务
    protected $service;
    // 校验
    protected $validate;
    // 用户ID
    protected $userId;
    // 用户登录信息
    protected $userInfo;
    protected $myAppInfo;
    protected $myPowerInfo;
    // 网络请求
    protected $param;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 初始化登录信息
        $this->initLogin();
    }


    /**
     * 校验登录
     * @author 陌上花开
     * @since: 2022/01/19
     */
    public function initLogin()
    {
        try{
            $userId = cookie('userId');
            $sign = cookie('userSign');
            $this->userId = $userId;

            // 登录用户信息
            $userModel = new \app\user\model\User();
            $userInfo = $userModel->getInfo();
            if(!$userInfo){
                throw new Exception(t('user.account_abnormal').'[errorCode:UserInfoError]');
            }
            $expectedSign = data_auth_sign($userInfo['appid'].$userInfo['username'].$userInfo['password'].qh_password_hash());
            if(!empty($userId) && !hash_equals((string)$expectedSign, (string)$sign)){
                cookie('userId',null);
                cookie('userSign',null);
                throw new Exception(t('login.user_session_expired'));
            }
            $this->userInfo = $userInfo;
            if(empty($userInfo['appid'])){
                throw new Exception(t('user.account_abnormal').'[errorCode:UserAppIdEmpty]');
            }
            if(!is_numeric($userInfo['appid']) || $userInfo['appid'] <= 0){
                throw new Exception(t('user.account_abnormal').'[errorCode:UserAppIdError]');
            }
            if($userInfo['status'] != 1){
                throw new Exception(t('user.account_blocked').'[errorCode:UserStatusBlocked]');
            }
            if(!empty($userInfo['ip'])){
                if(!in_array(get_client_ip(), qh_safe_unserialize_array($userInfo['ip']), true)){
                    throw new Exception(t('user.ip_not_whitelist'));
                }
            }
            $appModel = new \app\admin\model\AppModel();
            $this->myAppInfo = $appModel->getInfo(intval($userInfo['appid']));
            if(!$this->myAppInfo){
                throw new Exception(t('user.account_abnormal').'[errorCode:GetUserAppInfoError]');
            }
            $this->myPowerInfo = $this->getPowerPriceInfo(intval($userInfo['power']));
            if(!$this->myPowerInfo){
                throw new Exception(t('user.account_abnormal').'[errorCode:GetUserPowerInfoError]');
            }
            // 数据绑定
            $this->userInfo['app_name'] = $this->myAppInfo['name'];
            $this->userInfo['power_name'] = $this->myPowerInfo['name'];
            $this->userInfo['addauth_discount'] = floatval($this->myPowerInfo['addauth_discount'] / 100);
            $this->userInfo['adduser_discount'] = floatval($this->myPowerInfo['adduser_discount'] / 100);
            $this->userInfo['rebate_enabled'] = intval($this->myPowerInfo['rebate_enabled'] ?? 0);
            $this->userInfo['rebate_rate'] = floatval($this->myPowerInfo['rebate_rate'] ?? 0);
            $this->userInfo['discount_code_enabled'] = intval($this->myPowerInfo['discount_code_enabled'] ?? 0);
            View::assign('userId', $this->userId);
            View::assign('userInfo', $this->userInfo);
        }catch (\Exception $e){
            $this->logOut();
            if(IS_POST){
                exit(json_encode(message($e->getMessage(), false)));
            }
            exit($this->render('/public/error', ['msg' => $e->getMessage()]));
        }
    }

    /**
     * 退出登录
     * @author 陌上花开
     * @since: 2022/01/19
     */
    public function logOut(){
        $content = [
            'Title' => '退出登录',
            'Result' => 'success'
        ];
        event('ActionLog', $content);
        Cookie::delete('userId');
        Cookie::delete('userSign');
        Cookie::save();
        return message(t('login.logout_success'), true);
    }

    /**
     * 判断用户是否登录
     * @return bool
     */
    public function isUserLogin()
    {
        // 用户未登录返回 false
        if (empty(cookie('userId'))) {
            return false;
        }
        // 用户已登录返回 true
        return true;
    }

    public function sendCode(){
        if(!IS_POST){
            return message(t('validation.param_error'), false);
        }

        $type = input('post.type');
        if($type !== 'changeBindingMail'){
            return message(empty($type) ? t('validation.missing_type') : t('validation.param_error'), false);
        }

        $userId = intval($this->userId);
        $stage = strtolower(trim((string)input('post.stage', 'new')));
        $newEmail = BindingMailVerificationService::normalizeEmail(input('post.content'));
        $currentEmail = BindingMailVerificationService::normalizeEmail($this->userInfo['email'] ?? '');
        if(!in_array($stage, ['old', 'new'], true)){
            return message(t('validation.param_error'), false);
        }
        if(!filter_var($newEmail, FILTER_VALIDATE_EMAIL)){
            return message(t('profile.new_email_invalid'), false);
        }
        if($currentEmail !== '' && hash_equals($currentEmail, $newEmail)){
            return message(t('profile.new_email_same'), false);
        }
        if(\app\user\model\User::where('email', $newEmail)->where('id', '<>', $userId)->find()){
            return message(t('profile.email_already_used'), false);
        }

        if($stage === 'old'){
            if($currentEmail === ''){
                return message(t('profile.current_email_unbound'), false);
            }
            $recipient = $currentEmail;
            $mailContent = t('mail.current_email_code_body', ['code' => '{{code}}', 'username' => $this->userInfo['username']]);
        }else{
            if($currentEmail !== '' && !BindingMailVerificationService::isOldVerified($userId, $currentEmail)){
                $oldResult = BindingMailVerificationService::verifyCode(
                    $userId,
                    'old',
                    $currentEmail,
                    trim((string)input('post.old_code'))
                );
                if(!$oldResult['ok']){
                    return message($oldResult['message'], false);
                }
                BindingMailVerificationService::consumeCode($userId, 'old', $currentEmail);
                BindingMailVerificationService::markOldVerified($userId, $currentEmail);
            }
            $recipient = $newEmail;
            $mailContent = t('mail.new_email_code_body', ['code' => '{{code}}', 'username' => $this->userInfo['username']]);
        }

        $cooldownKey = BindingMailVerificationService::cooldownKey($userId, $stage, $recipient);
        if(\think\facade\Cache::get($cooldownKey)){
            return message(t('login.send_too_frequent'), false);
        }
        $rate = RateLimitService::hit('change_binding_mail', (string)get_client_ip(), 20, 3600);
        if(!$rate['ok']){
            return message(t('login.network_send_limited'), false);
        }

        $code = sprintf('%06d', random_int(0, 999999));
        $param = [
            'to' => $recipient,
            'title' => conf('title').' - '.t('mail.verification_code_subject'),
            'from_name' => conf('title'),
            'content' => str_replace('{{code}}', $code, $mailContent),
        ];
        if(!empty($this->userInfo['config'])){
            $param = array_replace_recursive($param, qh_safe_unserialize_array($this->userInfo['config']));
        }
        // 用户邮件配置只能提供 SMTP 参数，不允许改写本次收件人和验证内容。
        $param['to'] = $recipient;
        $param['title'] = conf('title').' - '.t('mail.verification_code_subject');
        $param['from_name'] = conf('title');
        $param['content'] = str_replace('{{code}}', $code, $mailContent);

        try {
            $result = Event::trigger('ChangeBindingMailNotice', $param)[0] ?? null;
            if (is_string($result)) {
                $decoded = json_decode($result, true);
                $result = is_array($decoded) ? $decoded : null;
            }
            if (!is_array($result) || intval($result['code'] ?? -1) !== 0) {
                Log::warning('Binding mail verification dispatch failed', [
                    'user_id' => $userId,
                    'stage' => $stage,
                ]);
                return message(t('login.email_send_failed'), false);
            }

            \think\facade\Cache::set($cooldownKey, 1, 60);
            if($stage === 'old'){
                BindingMailVerificationService::clearOldVerified($userId, $currentEmail);
            }
            BindingMailVerificationService::storeCode($userId, $stage, $recipient, $code);
            return message($stage === 'old' ? t('profile.current_email_code_sent') : t('profile.new_email_code_sent'), true);
        } catch (\Throwable $e) {
            Log::error('Binding mail verification dispatch exception: ' . $e->getMessage(), [
                'user_id' => $userId,
                'stage' => $stage,
                'exception' => $e,
            ]);
            return message(t('login.email_send_failed'), false);
        }
    }


    /**
     * 控制器默认入口
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/19
     */
    public function index()
    {
        return $this->render();
    }

//    /**
//     * 获取价格模板列表
//     * @return mixed
//     * @author 陌上花开
//     * @date 2022/1/25
//     */
//    public function getAuthTemplateList()
//    {
//        $authTemplateModel = new \app\admin\model\AuthTemplateModel();
//        $result = $authTemplateModel->getAllList();
//        return $result;
//    }
//
//    /**
//     * 获取权限模板列表
//     * @return mixed
//     * @author 陌上花开
//     * @date 2022/1/25
//     */
//    public function getPowerTemplateList()
//    {
//        $powerTemplateModel = new \app\admin\model\PowerTemplateModel();
//        $result = $powerTemplateModel->getAllList();
//        return $result;
//    }

//    /**
//     * 获取模式列表
//     * @return mixed
//     * @author 陌上花开
//     * @date 2022/1/25
//     */
//    public function getCheckTypeList()
//    {
//        try{
//            $checkTypeModel = new \app\admin\model\CheckTypeModel();
//            $result = $checkTypeModel->getCheckTypeList();
//            return $result;
//        }catch (\Exception $e){
//            throw new Exception($e->getMessage());
//        }
//
//    }

    /**
     * 获取价格列表
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function getAuthPriceList()
    {
        try{
            if(IS_POST){
                $appid = intval($this->userInfo['appid']);
                if(empty($appid)){
                    return message(t('app.appid_empty'), false);
                }
                $authPriceModel = new \app\admin\model\AuthPriceModel();
                $appModel = new \app\admin\model\AppModel();
                $appInfo = $appModel->getInfo($appid);
                if(!$appInfo){
                    return message(t('user.info_error').'[errorCode:GetUserAppInfoError]', false);
                }
                $tid = intval($appInfo['auth_template']);
                if(empty($tid)){
                    return message(t('app.get_template_failed').'[errorCode:GetAuthPriceTIDError]', false);
                }
                $content = [
                    'Title' => '获取列表',
                    '操作' => '获取价格列表',
                    'Result' => 'success'
                ];
                event('ActionLog', $content);
                $result = $authPriceModel->getAuthPriceList($tid);
                return message(t('common.list_success'), true, ['data' => $result]);
            }
        }catch (\Exception $e){
            return message(t('common.server_error').'[errorCode:GetAuthPriceList]', false);
        }
    }

//    /**
//     * 获取App列表
//     * @return array
//     * @author 陌上花开
//     * @date 2022/1/25
//     */
//    public function getAppList()
//    {
//        try{
//            $appModel = new \app\admin\model\AppModel();
//            $result = $appModel->getAllList();
//            return $result;
//        }catch (\Exception $e){
//            return message('获取应用列表失败！', false);
//        }
//
//    }

    /**
     * 获取权限信息
     * @return array
     * @author 陌上花开
     * @date 2022/1/25
     */
    private function getPowerPriceInfo($id)
    {
        if(empty($id)) return false;
        $powerPriceModel = new \app\admin\model\PowerPriceModel();
        try{
            $result = $powerPriceModel->getInfo($id);
            if(!$result) return false;
            return $result;
        }catch (\Exception $e){
            return false;
        }

    }

    /**
     * 获取权限列表
     * @return array
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function getPowerList(){
        $appid = intval($this->userInfo['appid']);
        try{
            $appModel = new \app\admin\model\AppModel();
            $appInfo = $appModel->getInfo($appid);
            if(!$appInfo){
                return message(t('user.app_info_error').'[errorCode:GetUserAppInfoError]', false);
            }
            $powerPriceModel = new \app\admin\model\PowerPriceModel();
            $result = $powerPriceModel->getAddPowerList($this->userInfo['power']);
            return message(t('common.list_success'), true, ['data' => $result]);
        } catch (\Exception $e) {
            return message(t('power.get_list_failed').'[errorCode:GetUserAddPowerListError]', false);
        }
    }

    /**
     * 获取可升级权限列表
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function getUpdatePowerList(){
        if(IS_POST){
            try{
                $post = request()->post();
                $power = !empty($post['power'])?intval($post['power']):null;
                if(empty($power) || $power < 1){
                    return message(t('common.server_error').'[errorCode:GetUpdatePowerListError]', false);
                }
                $powerPriceModel = new \app\admin\model\PowerPriceModel();
                $result = $powerPriceModel->getUpdatePowerList($power, $this->userInfo['power']);
                return message(t('common.list_success'), true, ['data' => $result]);
            } catch (\Exception $e) {
                return message(t('common.server_error').'[errorCode:GetUpdatePowerListError]', false);
            }
        }
    }

    /**
     * 获取用户可升级权限列表
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function getUserUpdatePowerList(){
        if(IS_POST) {
            try {
                $powerPriceModel = new \app\admin\model\PowerPriceModel();
                $result = $powerPriceModel->getUserUpdatePowerList($this->userInfo['power']);
                return message(t('common.list_success'), true, ['data' => $result]);
            } catch (\Exception $e) {
                return message(t('common.server_error').'[errorCode:GetUserUpdatePowerListError]', false);
            }
        }
    }
    /**
     * 添加或编辑入口
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function edit()
    {
        if (IS_POST) {
            try{
                try{
                    if(!$this->myPowerInfo) {
                        return json(message(t('user.power_info_error').'[errorCode:GetUserPowerInfoError]', false));
                    }
                    // 权限检测
                    if($this->service instanceof \app\user\service\AuthService){
                        if($this->myPowerInfo['addauth_power'] != 1){
                            return json(message(t('login.no_access'), false));
                        }
                    } else if ($this->service instanceof \app\user\service\PirateService){
                        if($this->myPowerInfo['pirate_power'] != 1){
                            return json(message(t('login.no_access'), false));
                        }
                    } else if ($this->service instanceof \app\user\service\UserService){
                        if($this->myPowerInfo['adduser_power'] != 1){
                            return json(message(t('login.no_access'), false));
                        }
                    }
                }catch (\Exception $e){
                    return json(message(t('common.server_error').'[errorCode:GetAccessRightsError]', false));
                }
                return json($this->service->edit());
            }catch (\Exception $e){
                return json(message($e->getMessage(), false));
            }
        }
    }

    /**
     * 删除单条记录
     * @return array
     * @author 陌上花开
     * @date 2022/1/25
     */
    public function drop()
    {
        if (IS_POST) {
            $id = input('post.id');
            try{
                $info = $this->service->getInfo($id);
                if ($info) {
                    $this->service->drop($id);
                    return json(message(t('user.delete_success'), true));
                }
                return json(message(t('validation.invalid_id'), false));
            }catch (\Exception $e){
                return json(message($e->getMessage(), false));
            }
        }
    }

    /**
     * 批量删除记录
     * @return array
     * @author 陌上花开
     * @date 2019/2/25
     */
    public function batchDrop()
    {
        if (IS_POST) {
            try{
                // Normalize ids from request before passing them into service layer.
                $ids = array_values(array_filter(array_unique(array_map('intval', explode(',', (string)input('post.id'))))));
                if (empty($ids)) {
                    return json(message('common.invalid_id', false));
                }
                if (count($ids) > 100) {
                    return json(message(t('batch.delete_limit', ['limit' => 100]), false));
                }
                //批量删除
                $num = 0;
                foreach ($ids as $key => $val) {
                    $res = $this->service->drop($val);
                    if ($res !== false) {
                        $num++;
                    }
                }
                return json(message(t('batch.delete_count', ['total' => count($ids), 'count' => $num])));
            }catch (\Exception $e){
                return json(message($e->getMessage(), false));
            }
        }
    }

    /**
     * 列表
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/12
     */
    public function list()
    {
        if (IS_POST) {
            try{
                try{
                    if(!$this->myPowerInfo) {
                        return json(message(t('user.power_info_error').'[errorCode:GetUserPowerInfoError]', false));
                    }
                    // 权限检测
                    if($this->service instanceof \app\user\service\AuthService){
                        if($this->myPowerInfo['addauth_power'] != 1){
                            return json(message(t('login.no_access'), false));
                        }
                    } else if ($this->service instanceof \app\user\service\PirateService){
                        if($this->myPowerInfo['pirate_power'] != 1){
                            return json(message(t('login.no_access'), false));
                        }
                    } else if ($this->service instanceof \app\user\service\UserService){
                        if($this->myPowerInfo['adduser_power'] != 1){
                            return json(message(t('login.no_access'), false));
                        }
                    }
                }catch (\Exception $e){
                    return json(message(t('common.server_error').'[errorCode:GetAccessRightsError]', false));
                }
                $result = $this->service->list();
                return json(message(t('common.list_success'), true, ['data' => $result]));
            }catch (\Exception $e){
                return json(message($e->getMessage(), false, ['data' => []]));
            }
        }
        try{
            if(!$this->myPowerInfo) {
                return $this->render('public/error', ['msg' => t('user.power_info_error').'[errorCode:GetUserPowerInfoError]']);
            }
            // 权限检测
            if($this->service instanceof \app\user\service\AuthService){
                if($this->myPowerInfo['addauth_power'] != 1){
                    return $this->render('public/error', ['msg' => t('login.no_access')]);
                }
            } else if ($this->service instanceof \app\user\service\PirateService){
                if($this->myPowerInfo['pirate_power'] != 1){
                    return $this->render('public/error', ['msg' => t('login.no_access')]);
                }
                View::assign('price', qh_money_apply_rate($this->myAppInfo['pirate_money'], $this->myPowerInfo['pirate_discount']));
            } else if ($this->service instanceof \app\user\service\UserService){
                if($this->myPowerInfo['adduser_power'] != 1){
                    return $this->render('public/error', ['msg' => t('login.no_access')]);
                }
            }
            return $this->render();
        }catch (\Exception $e){
            return $this->render('public/error', ['msg' => t('common.server_error').'[errorCode:GetAccessRightsError]']);
        }
    }

    /**
     * 设置状态
     * @return mixed
     * @author 陌上花开
     * @date 2022/1/12
     */
    public function setStatus()
    {
        if (IS_POST) {
            try{
                $this->service->setStatus();
                return json(message(t('user.status_change_success'), true));
            }catch (\Exception $e){
                return json(message($e->getMessage(), false));
            }
        }
    }
}
