<?php
namespace addons\encryption\controller;

use app\common\controller\Backend;

class Encryption extends Backend
{
    private static $config = [
        1 => [
            'method' => 'Sg11',
            'versionSelection' => '1',
            'version' => ['5.4','5.5','5.6','7.0','7.1','7.2','7.3','7.4']
        ],
        2 => [
            'method' => 'Sg12',
            'versionSelection' => '1',
            'version' => ['5.4','5.5','5.6','7.0','7.1','7.2','7.3','7.4','8.0']
        ],
        3 => [
            'method' => 'Sg13',
            'versionSelection' => '1',
            'version' => ['5.4','5.5','5.6','7.0','7.1','7.2','7.3','7.4','8.0','8.1']
        ]
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function list(){
        $config = self::$config;
        $introductions = [
            1 => t('encryption_ui.sg11_intro'),
            2 => t('encryption_ui.sg12_intro'),
            3 => t('encryption_ui.sg13_intro'),
        ];
        foreach ($config as $id => &$item) {
            $item['name'] = t('encryption_ui.sg_name', ['version' => $id + 10]);
            $item['introduce'] = $introductions[$id];
        }
        unset($item);
        return $config;
    }

    public function index()
    {
        if(IS_POST){
            $post = $this->request->post();
            $type = !empty($post['type'])?intval($post['type']):null;
            $version = !empty($post['version'])?$post['version']:null;
            $comment = !empty($post['comment'])?$post['comment']:null;
            $filename = !empty($post['name'])?trim((string)$post['name']):null;

            if(empty($type)){
                return message(t('encryption.select_type'), false);
            }

            if(empty($comment)){
                return message(t('encryption.copyright_required'), false);
            }

            if(empty($filename)){
                return message(t('upload.select_file'), false);
            }
            if ($filename !== basename($filename) || !preg_match('/^[^\x00\/\\\\]{1,180}\.zip$/iu', $filename)) {
                return message(t('upload.filename_invalid'), false);
            }

            if(!array_key_exists($type, self::$config)){
                return message(t('encryption.type_not_found'), false);
            }

            if(self::$config[$type]['versionSelection'] && empty($version)){
                return message(t('encryption.select_php_version'), false);
            }

            try{
                $zip_name = 'QH_Encryption_'.time().'.zip';
                $filePath = RUNTIME_PATH . DS . 'temp' . DS . 'upload' . DS . $filename;
                $completePath = RUNTIME_PATH . DS . 'temp' . DS . 'upload' . DS . $zip_name;
                $class = '\\addons\\encryption\\library\\' . self::$config[$type]['method'];
                if (!class_exists($class)) {
                    return message(t('encryption.library_not_found'), false);
                }
                $encryptionClass = new $class();
                $result = $encryptionClass->encryption($comment, $version, $filePath, $completePath);
                if($result['code'] == 1){
                    return message(t('encryption.success'), true, $zip_name);
                }else{
                    return message(t('encryption.failed'), false);
                }
            }catch(\Exception $e){
                return message(t('encryption.failed'), false);
            }

        }
    }

    public function download(){
        $name = trim((string)$this->request->get('name'));
        if(empty($name)){
            return $this->render('/public/error', ['msg' => t('archive.name_required')]);
        }
        if ($name !== basename($name) || !preg_match('/^[^\x00\/\\\\]{1,180}\.zip$/iu', $name)) {
            return $this->render('/public/error', ['msg' => t('archive.name_invalid')]);
        }
        $filePath = RUNTIME_PATH . DS . 'temp' . DS . 'upload' . DS . $name;
        if(!is_file($filePath)){
            return $this->render('/public/error', ['msg' => t('archive.not_found')]);
        }
        return download($filePath, $name);
    }

    private function get_curl($url, $paras = array()) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        if (@$paras['Header']) {
            $Header = $paras['Header'];
        } else {
            $Header[] = "Accept:*/*";
            $Header[] = "Accept-Encoding:gzip,deflate,sdch";
            $Header[] = "Accept-Language:zh-CN,zh;q=0.8";
            $Header[] = "Connection:close";
        }
        curl_setopt($ch, CURLOPT_HTTPHEADER, $Header);
        if (@$paras['ctime']) { // 连接超时
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $paras['ctime']);
        } else {
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30);
        }
        if (@$paras['rtime']) { // 读取超时
            curl_setopt($ch, CURLOPT_TIMEOUT, $paras['rtime']);
        }
        if (@$paras['post']) {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $paras['post']);
        }
        if (@$paras['header']) {
            curl_setopt($ch, CURLOPT_HEADER, true);
        }
        if (@$paras['cookie']) {
            curl_setopt($ch, CURLOPT_COOKIE, $paras['cookie']);
        }
        if (@$paras['refer']) {
            if ($paras['refer'] == 1) {
                curl_setopt($ch, CURLOPT_REFERER, 'http://m.qzone.com/infocenter?g_f=');
            } else {
                curl_setopt($ch, CURLOPT_REFERER, $paras['refer']);
            }
        }
        if (@$paras['ua']) {
            curl_setopt($ch, CURLOPT_USERAGENT, $paras['ua']);
        } else {
            curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36");
        }
        if (@$paras['nobody']) {
            curl_setopt($ch, CURLOPT_NOBODY, 1);
        }
        curl_setopt($ch, CURLOPT_ENCODING, "gzip");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        if (@$paras['GetCookie']) {
            curl_setopt($ch, CURLOPT_HEADER, 1);
            $result = curl_exec($ch);
            preg_match_all("/Set-Cookie: (.*?);/m", $result, $matches);
            $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $header = substr($result, 0, $headerSize); //状态码
            $body = substr($result, $headerSize); //响应内容
            $ret = [
                "Cookie" => $matches, "body" => $body, "code" => $header
            ];
            curl_close($ch);
            return $ret;
        }
        $ret = curl_exec($ch);
        if (@$paras['loadurl']) {
            $Headers = curl_getinfo($ch);
            $ret = $Headers['redirect_url'];
        }
        curl_close($ch);
        return $ret;
    }
}
