location ~* (runtime|application)/ {
    return 403;
}

location / {
    # 测试期页面仅允许站长当前公网 IP。
    allow 117.147.12.123;
    allow 124.160.203.148;
    deny all;
    if (!-e $request_filename) {
        rewrite ^(.*)$ /index.php?s=$1 last;
        break;
    }
}
