<?php

namespace app\index\controller;

use app\common\controller\Frontend;
use think\facade\Cache;
use think\facade\Db;

class DownloadInfo extends Frontend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function verification(){
        if(IS_POST){
            $post = $this->request->post();
            $qq = !empty($post['qq'])?intval($post['qq']):null;
            $appid = !empty($post['appid'])?intval($post['appid']):null;
            $auth_info = !empty($post['auth_info'])?$post['auth_info']:null;
            $authcode = !empty($post['authcode'])?$post['authcode']:null;
            if(empty($appid)){
                return message('请选择所属应用！' ,false);
            }
            if(empty($auth_info)){
                return message('请填写授权内容！' ,false);
            }
            if(empty($qq)){
                return message('请填写授权者QQ！' ,false);
            }
            if(empty($authcode)){
                return message('请填写授权码！' ,false);
            }
            $row = Db::name('auth')
                ->where([
                    'appid' => $appid,
                    'auth_info' => $auth_info
                ])
                ->field('qq,authcode')
                ->find();
            if(empty($row)){
                return message('不存在此授权！' ,false);
            }
            if($row['qq'] != $qq){
                return message('该授权QQ与所填QQ不匹配！' ,false);
            }
            if($row['authcode'] != $authcode){
                return message('该授权授权码与所填授权码不匹配！' ,false);
            }
            $res = Db::name('version')
                ->where([
                    ['appid', '=', $appid],
                    ['status', '=', 1],
                    ['type', '=', 0]
                ])
                ->find();
            if(empty($res)){
                return message('此应用无安装包' ,false);
            }
            $value = serialize([
                'versionInfo' => $res,
                'authInfo' => $row
            ]);
            $key = md5(uniqid());
            Cache::set($key, $value, 43200);
            return message('获取下载链接成功' ,true, ['url' => 'http://'.DOMAIN.'/api.php/Download/download/?sign='.$key]);
        }
    }
}