<?php

namespace app\index\controller;

use app\common\controller\Frontend;
use think\facade\Cache;
use think\facade\Db;

class DownloadQrCode extends Frontend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function verification(){
        if(IS_POST){
            $post = $this->request->post();
            $appid = !empty($post['appid'])?intval($post['appid']):null;
            $auth_info = !empty($post['auth_info'])?$post['auth_info']:null;

            if(empty($appid)){
                return message('请选择所属应用！' ,false);
            }
            if(empty($auth_info)){
                return message('请填写授权内容！' ,false);
            }

            $row = Db::name('auth')
                ->where([
                    'appid' => $appid,
                    'auth_info' => $auth_info
                ])
                ->field('qq,authcode')
                ->find();
            if(empty($row)){
                return message('不存在此授权！' ,false);
            }
            return message('请使用绑定该授权QQ继续扫码' ,true);
        }
    }
}