<?php

return [
    [
        'name' => 'type',
        'title' => t('mail_config.mode'),
        'type' => 'radio',
        'content' => [
            t('common.closed'),
            t('mail_config.smtp'),
            t('mail_config.aliyun'),
            'SendCloud',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'smtp',
        'title' => t('mail_config.smtp'),
        'type' => 'array',
        'content' => [],
        'value' => [
            'server' => (string)env('mail.smtp_server', ''),
            'port' => (string)env('mail.smtp_port', '465'),
            'name' => (string)env('mail.smtp_username', ''),
            'authcode' => (string)env('mail.smtp_authcode', ''),
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'aliyun',
        'title' => t('mail_config.aliyun'),
        'type' => 'array',
        'content' => [],
        'value' => [
            'accessKey' => t('mail_config.access_key_placeholder'),
            'accessSecret' => t('mail_config.access_secret_placeholder'),
            'name' => t('mail_config.sender_placeholder'),
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sendcloud',
        'title' => 'SendCloud',
        'type' => 'array',
        'content' => [],
        'value' => [
            'apiUser' => t('mail_config.api_user_placeholder'),
            'apiKey' => t('mail_config.api_key_placeholder'),
            'name' => t('mail_config.sender_placeholder'),
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'recv',
        'title' => t('mail_config.recipient'),
        'type' => 'string',
        'content' => [],
        'value' => (string)env('mail.test_recipient', ''),
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => t('common.nice_tips'),
        'type' => 'string',
        'content' => [],
        'value' => t('mail_config.help_html'),
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'orange',
    ],
];
