<?php

return [
    [
        'name' => 'type',
        'title' => '发信模式',
        'type' => 'radio',
        'content' => [
            '关闭',
            'SMTP发信',
            '阿里云',
            'SendCloud',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'smtp',
        'title' => 'SMTP发信',
        'type' => 'array',
        'content' => [],
        'value' => [
            'server' => 'smtpdm.aliyun.com',
            'port' => '465',
            'name' => 'noteweb@notice.noteweb.top',
            'authcode' => 'ZAEsky1203',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'aliyun',
        'title' => '阿里云',
        'type' => 'array',
        'content' => [],
        'value' => [
            'accessKey' => '您的accessKey',
            'accessSecret' => '您的accessSecret',
            'name' => '您的发信邮箱',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sendcloud',
        'title' => 'SendCloud',
        'type' => 'array',
        'content' => [],
        'value' => [
            'apiUser' => '您的API_USER',
            'apiKey' => '您的API_KEY',
            'name' => '您的发信邮箱',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'recv',
        'title' => '收信邮箱',
        'type' => 'string',
        'content' => [],
        'value' => '986682545@qq.com',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '使用普通模式发信时，建议使用QQ邮箱，SMTP服务器smtp.qq.com，端口465或587，密码不是QQ密码也不是邮箱独立密码，是QQ邮箱设置界面生成的<a href="https://service.mail.qq.com/cgi-bin/help?subtype=1&&no=1001256&&id=28"  target="_blank" rel="noreferrer">授权码</a>。<br/>阿里云邮件推送：<a href="https://www.aliyun.com/product/directmail" target="_blank" rel="noreferrer">点此进入</a>｜<a href="https://usercenter.console.aliyun.com/#/manage/ak" target="_blank" rel="noreferrer">获取AK/SK</a><br/>SendCloud邮件推送：<a href="https://www.sendcloud.net/home" target="_blank" rel="noreferrer">点此进入</a>',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'orange',
    ],
];
