<?php

namespace app\admin\controller;

use app\common\controller\Backend;
use think\facade\View;

class AddCode extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        View::assign('app_list', parent::getAppList());
        return $this->render();
    }
}