<?php
namespace app\admin\controller;

use app\common\controller\Backend;
use app\admin\service\AddonService;
use think\addons\Service;
use think\facade\Cache;
use think\Exception;
use think\facade\View;
use think\facade\Db;
class Addon extends Backend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AddonService();
    }

    public function config($name = null){
        if (IS_POST) {
            $name = $name ?? $this->request->post("name");
            if (!$name) {
                return message('缺少NAME参数！', false);
            }
            if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
                return message('插件名不合法！', false);
            }
            if (!is_dir(ADDONS_PATH . DS . $name)) {
                return message('不存在此插件！', false);
            }
            $info = get_addons_info($name);
            $config = get_addons_fullconfig($name);
            if (!$info) {
                return message('获取插件配置信息失败！', false);
            }

            $params = $this->request->post('row/a', [], 'trim');
            if ($params) {
                foreach ($config as $k => &$v) {
                    if($v['type'] == 'bool'){
                        $value = isset($params[$v['name']])?'1':'0';
                        $v['value'] = $value;
                    }else {
                        if (isset($params[$v['name']])) {
                            if ($v['type'] == 'array') {
                                $params[$v['name']] = getArrayData($params[$v['name']]);
                                $value = $params[$v['name']];
                            } else {
                                $value = is_array($params[$v['name']]) ? implode(',', $params[$v['name']]) : $params[$v['name']];
                            }
                            $v['value'] = $value;
                        }
                    }
                }
                try {
                    //更新配置文件
                    $result = set_addons_fullconfig($name, $config);
                    Service::refresh();
                    if($result){
                        return message('更新插件配置信息成功！', true);
                    }else{
                        return message('更新插件配置信息失败！<br> 没有写入权限！', false);
                    }
                } catch (Exception $e) {
                    return message('更新插件配置信息失败！'.$e->getMessage(), false);
                }
            }
            return message('参数不能为空！', false);
        }

        $name = $name ?? $this->request->post("name");
        if (!$name) {
            return $this->render('/public/error', ['msg' => '缺少NAME参数！']);
        }
        if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
            return $this->render('/public/error', ['msg' => '插件名不合法！'.$name]);
        }
        if (!is_dir(ADDONS_PATH . DS . $name)) {
            return $this->render('/public/error', ['msg' => '不存在此插件！']);
        }
        $info = get_addons_info($name);
        $config = get_addons_fullconfig($name);
        if (!$info) {
            return $this->render('/public/error', ['msg' => '获取插件配置信息失败！']);
        }


        $tips = [];
        foreach ($config as $index => &$item) {
            if ($item['name'] == '__tips__') {
                $tips = $item;
                unset($config[$index]);
            }
        }
        View::assign("name", $name);
        View::assign("addon", ['info' => $info, 'config' => $config, 'tips' => $tips]);
        $configFile = ADDONS_PATH. DS . $name . DS . 'config.html';
        $viewFile = is_file($configFile) ? $configFile : '';
        return $this->render($viewFile);
    }

    /**
     * 禁用启用
     */
    public function status()
    {

        if(IS_POST){
            $name = $this->request->post("name");
            //return method_exists(get_addons_instance($name), "disable");
            $action = $this->request->post("action");
            if (!$name) {
                return message('缺少NAME参数！', false);
            }
            if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
                return message('插件名不合法！', false);
            }
            if (!is_dir(ADDONS_PATH . DS . $name)) {
                return message('不存在此插件！', false);
            }
            try {
                $action = $action == 'enable' ? 'enable' : 'disable';
                //调用启用、禁用的方法
                Service::$action($name);
                Cache::tag('SF_Menu')->clear();
            } catch (Exception $e) {
                return message($e->getMessage(), false);
            }
            return message('插件'.($action=='enable'?'启用':'禁用').'成功！', true);
        }
    }

    /**
     * 本地上传安装
     */
    public function local()
    {
        $file = $this->request->file('file');
        try {
            Service::local($file);
        } catch (Exception $e) {
            return message($e->getMessage(), false);
        }
        return message('插件安装成功！', true);
    }

    /**
     * 本地上传更新
     */
    public function update()
    {
        $name = $this->request->post('name');
        $file = $this->request->file('file');
        try {
            Service::update($name, $file);
            Cache::tag('SF_Menu')->clear();
        } catch (Exception $e) {
            return message($e->getMessage(), false);
        }
        return message('插件更新成功！', true);
    }

    public function list(){
        try{
            if(IS_POST){
                return message("获取列表成功！", true, $this->service->list());
            }
        }catch (\Exception $e){
            return message($e->getMessage());
        }
        try{
            return $this->render();
        }catch (\Exception $e){
            return $this->render('/public/error', ['msg' => $e->getMessage()]);
        }
    }

    /**
     * 卸载
     */
    public function unInstall()
    {
        $name = $this->request->post("name");
        $droptables = (int)$this->request->post("droptables");
        if (!$name) {
            return message('缺少NAME参数！', false);
        }
        if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
            return message('插件名不合法！', false);
        }
        if (!is_dir(ADDONS_PATH . DS . $name)) {
            return message('不存在此插件！', false);
        }

        $tables = [];
        if ($droptables) {
            $tables = get_addons_tables($name);
        }

        try {
            Service::uninstall($name);
            if ($tables) {
                $prefix = Config::get('database.prefix');
                //删除插件关联表
                foreach ($tables as $index => $table) {
                    //忽略非插件标识的表名
                    if (!preg_match("/^{$prefix}{$name}/", $table)) {
                        continue;
                    }
                    Db::execute("DROP TABLE IF EXISTS `{$table}`");
                }
            }
            Cache::tag('SF_Menu')->clear();
        } catch (Exception $e) {
            return message($e->getMessage(), false);
        }
        return message('插件删除成功！', true);
    }

}