<?php
namespace app\admin\controller;

use app\common\controller\Backend;
use app\admin\service\AddonService;
use think\addons\Service;
use think\facade\Cache;
use think\Exception;
use think\facade\View;
use think\facade\Db;
use think\facade\Config;
class Addon extends Backend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new AddonService();
    }

    public function config($name = null){
        if (IS_POST) {
            $name = $name ?? $this->request->post("name");
            if (!$name) {
                return message(t('validation.missing_name'), false);
            }
            if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
                return message(t('addon.name_illegal'), false);
            }
            if (!is_dir(ADDONS_PATH . DS . $name)) {
                return message(t('addon.not_exist'), false);
            }
            $info = get_addons_info($name);
            $config = get_addons_fullconfig($name);
            if (!$info) {
                return message(t('addon.config_failed'), false);
            }

            $params = $this->request->post('row/a', [], 'trim');
            if ($params) {
                foreach ($config as $k => &$v) {
                    if($v['type'] == 'bool'){
                        $value = isset($params[$v['name']])?'1':'0';
                        $v['value'] = $value;
                    }else {
                        if (isset($params[$v['name']])) {
                            if ($v['type'] == 'array') {
                                $params[$v['name']] = getArrayData($params[$v['name']]);
                                $value = $params[$v['name']];
                            } else {
                                $value = is_array($params[$v['name']]) ? implode(',', $params[$v['name']]) : $params[$v['name']];
                            }
                            $v['value'] = $value;
                        }
                    }
                }
                try {
                    //更新配置文件
                    $result = set_addons_fullconfig($name, $config);
                    // think-addons 2.x 会在 hooks 缓存为空时重新扫描插件。
                    Cache::delete('hooks');
                    if($result){
                        return message(t('addon.config_update_success'), true);
                    }else{
                        return message(t('addon.config_update_failed'), false);
                    }
                } catch (Exception $e) {
                    return message(t('addon.config_update_failed').$e->getMessage(), false);
                }
            }
            return message(t('validation.params_missing'), false);
        }

        $name = $name ?? $this->request->post("name");
        if (!$name) {
            return $this->render('/public/error', ['msg' => t('validation.missing_name')]);
        }
        if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
            return $this->render('/public/error', ['msg' => t('addon.name_illegal').$name]);
        }
        if (!is_dir(ADDONS_PATH . DS . $name)) {
            return $this->render('/public/error', ['msg' => t('addon.not_exist')]);
        }
        $info = get_addons_info($name);
        $config = get_addons_fullconfig($name);
        if (!$info) {
            return $this->render('/public/error', ['msg' => t('addon.config_failed')]);
        }


        $tips = [];
        foreach ($config as $index => &$item) {
            if ($item['name'] == '__tips__') {
                $tips = $item;
                unset($config[$index]);
            }
        }
        View::assign("name", $name);
        View::assign("addon", ['info' => $info, 'config' => $config, 'tips' => $tips]);
        $configFile = ADDONS_PATH. DS . $name . DS . 'config.html';
        $viewFile = is_file($configFile) ? $configFile : '';
        return $this->render($viewFile);
    }

    /**
     * 禁用启用
     */
    public function status()
    {

        if(IS_POST){
            $name = $this->request->post("name");
            $action = $this->request->post("action");
            if (!$name) {
                return message(t('validation.missing_name'), false);
            }
            if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
                return message(t('addon.name_illegal'), false);
            }
            if (!is_dir(ADDONS_PATH . DS . $name)) {
                return message(t('addon.not_exist'), false);
            }
            try {
                $action = $action == 'enable' ? 'enable' : 'disable';
                //调用启用、禁用的方法 — think\addons\Service 没有静态 enable/disable
                //应使用 get_addons_instance($name)->$action()
                $addon = get_addons_instance($name);
                if (!$addon || !method_exists($addon, $action)) {
                    return message(t('addon.not_exist'), false);
                }
                $addon->$action();
                Cache::tag('QH_Menu')->clear();
            } catch (Exception $e) {
                return message($e->getMessage(), false);
            }
            return message($action=='enable' ? t('addon.enabled') : t('addon.disabled'), true);
        }
    }

    /**
     * 本地上传安装
     */
    public function local()
    {
        if (!IS_POST) {
            return message('common.illegal_request', false);
        }
        $file = $this->request->file('file');
        try {
            // think\addons\Service::local 不存在,改用 addons Service::localInstall 方式:
            // 走 get_addons_instance + install() 的标准流程
            $info = [];
            $addonPath = $this->service->extractLocalAddon($file, $info);
            if (!$addonPath) {
                return message(t('addon.install_failed'), false);
            }
        } catch (Exception $e) {
            return message($e->getMessage(), false);
        }
        return message(t('addon.install_success'), true);
    }

    /**
     * 本地上传更新
     */
    public function update()
    {
        if (!IS_POST) {
            return message('common.illegal_request', false);
        }
        $name = $this->request->post('name');
        $file = $this->request->file('file');
        if (!$name) {
            return message(t('validation.missing_name'), false);
        }
        if (!is_string($name) || !preg_match('/^[A-Za-z0-9]{1,64}$/D', $name)) {
            return message(t('addon.name_illegal'), false);
        }
        try {
            // think\addons\Service::update 不存在,改为通过 get_addons_instance 处理
            $addon = get_addons_instance($name);
            if (!$addon) {
                return message(t('addon.not_exist'), false);
            }
            // 由 AdminService 处理具体更新逻辑(文件解压/覆盖/refresh)
            $this->service->updateAddon($name, $file);
            Cache::tag('QH_Menu')->clear();
        } catch (Exception $e) {
            return message($e->getMessage(), false);
        }
        return message(t('addon.update_success'), true);
    }

    public function list(){
        try{
            if(IS_POST){
                return message(t('common.list_success'), true, $this->service->list());
            }
        }catch (\Exception $e){
            return message($e->getMessage());
        }
        try{
            return $this->render();
        }catch (\Exception $e){
            return $this->render('/public/error', ['msg' => $e->getMessage()]);
        }
    }

    /**
     * 卸载
     */
    public function unInstall()
    {
        if (!IS_POST) {
            return message('common.illegal_request', false);
        }
        $name = $this->request->post("name");
        $droptables = (int)$this->request->post("droptables");
        if (!$name) {
            return message(t('validation.missing_name'), false);
        }
        if (!preg_match("/^[a-zA-Z0-9]+$/", $name)) {
            return message(t('addon.name_illegal'), false);
        }
        if (!is_dir(ADDONS_PATH . DS . $name)) {
            return message(t('addon.not_exist'), false);
        }

        $tables = [];
        if ($droptables) {
            $tables = get_addons_tables($name);
        }

        try {
            Service::uninstall($name);
            if ($tables) {
                $prefix = Config::get('database.prefix');
                //删除插件关联表
                foreach ($tables as $index => $table) {
                    // 动态标识符不能使用参数绑定，必须先限制为普通表名，
                    // 再确认它确实属于当前插件的命名空间。
                    if (!is_string($table)
                        || !preg_match('/^[A-Za-z0-9_]{1,64}$/D', $table)
                        || !preg_match('/^' . preg_quote($prefix . $name, '/') . '/', $table)
                    ) {
                        continue;
                    }
                    Db::execute("DROP TABLE IF EXISTS `{$table}`");
                }
            }
            Cache::tag('QH_Menu')->clear();
        } catch (Exception $e) {
            return message($e->getMessage(), false);
        }
        return message(t('addon.delete_success'), true);
    }

}
