<?php
declare (strict_types = 1);

namespace app\admin\controller;

use app\admin\service\MenuService;
use app\common\controller\Backend;
use think\facade\Db;
use think\facade\View;

/**
 * 用户行为-控制器
 * @author 陌上花开
 * @since 2022/1/20
 * Class Action
 * @package app\admin\controller
 */
class Index extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 后台主入口
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since: 2022/6/30
     * @author 陌上花开
     */
    public function index()
    {
        //return hook('mail',['to' => '2129876388@qq.com', 'title' => '换绑邮箱通知', 'content' => '验证码:11111']);
        //return hook('wxPushUserNotice',['title' => 1, 'content' => '12', 'to' => 'UID_Kl7r77sruvFSn8gdk4DfkDS3eAW5','contentType' => 1]);
        //hook('testhook');
        // 取消模板布局
        //$this->app->view->layout(false);
        try{
            $meunService = new MenuService();
            $menuList = $meunService->getList();
            // Shared layout is role-driven; business menu source remains unchanged.
            View::assign([
                'layoutRole' => 'admin',
                'layoutAvatar' => '//q4.qlogo.cn/headimg_dl?dst_uin='.$this->adminInfo['qq'].'&spec=100',
                'layoutUsername' => '管理员',
                'menuList' => $menuList,
            ]);
            return View::fetch(APP_PATH . DS . 'common' . DS . 'view' . DS . 'layout' . DS . 'main_layout.html');
        }catch (\Exception $e){
            return $this->render('/public/error', ['msg' => $e->getMessage()]);
        }
    }

    /**
     * 欢迎页
     * @author 陌上花开
     * @since: 2022/6/30
     */
    public function main(){
        $authCount = Db::name('auth')->count('id');
        $authYesterday = Db::name('auth')->whereTime('addtime', 'yesterday')->count('id');
        $authToday = Db::name('auth')->whereTime('addtime', 'today')->count('id');
        $authIncrease = $authToday - $authYesterday;

        $paymentCount = Db::name('payment')->count('id');
        $paymentYesterday = Db::name('payment')->whereTime('addtime', 'yesterday')->count('id');
        $paymentToday = Db::name('payment')->whereTime('addtime', 'today')->count('id');
        $paymentIncrease = $paymentToday - $paymentYesterday;

        $pirateCount = Db::name('pirate')->count('id');
        $pirateYesterday = Db::name('pirate')->whereTime('addtime', 'yesterday')->count('id');
        $pirateToday = Db::name('pirate')->whereTime('addtime', 'today')->count('id');
        $pirateIncrease = $pirateToday - $pirateYesterday;

        $userCount = Db::name('user')->count('id');
        $userYesterday = Db::name('user')->whereTime('addtime', 'yesterday')->count('id');
        $userToday = Db::name('user')->whereTime('addtime', 'today')->count('id');
        $userIncrease = $userToday - $userYesterday;
        $logList = Db::name('log')->order('id' ,'desc')->field('title,create_time')->where(['username' => $this->adminId, 'is_admin' => 1])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $balanceRanking = Db::name('user')->order('balance' ,'desc')->field('username,balance')->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $integralRanking = Db::name('user')->order('integral' ,'desc')->field('username,integral')->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);

        View::assign([
            'log_list' => $logList,
            'balance_ranking' => $balanceRanking,
            'integral_ranking' => $integralRanking,
            'auth_count' => $authCount,
            'auth_increase' => $authIncrease,
            'payment_count' => $paymentCount,
            'payment_increase' => $paymentIncrease,
            'pirate_count' => $pirateCount,
            'pirate_increase' => $pirateIncrease,
            'user_count' => $userCount,
            'user_increase' => $userIncrease
        ]);
        return $this->render();
    }

    public function editPassword(){
        if(IS_POST){
            $post = $this->request->post();
            $username = !empty($post['username'])?$post['username']:null;
            $oldPassword = !empty($post['oldPassword'])?$post['oldPassword']:null;
            $newPassword = !empty($post['newPassword'])?$post['newPassword']:null;
            if(empty($username)){
                return message('请填写用户名！', false);
            }
            if(empty($oldPassword)){
                return message('请填写原密码！', false);
            }
            if($oldPassword != $this->adminInfo['password']){
                return message('原密码不正确！', false);
            }
            if($username == $this->adminInfo['username']){
                if(empty($newPassword)){
                    return message('请填写新密码！', false);
                }
                if($oldPassword == $newPassword){
                    return message('新密码不能与原密码相同！', false);
                }
                if(strlen($newPassword) < 6){
                    return message('新密码不能小于6位！', false);
                }
                try{
                    Db::name('admin')
                        ->where('id', $this->adminId)
                        ->data(['password' => $newPassword])
                        ->update();
                    return message('修改密码成功！', true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }else{
                $row = Db::name('admin')->where('username', $username)->find();
                if($row){
                    return message('系统已存在该用户名，请更换后重试！', false);
                }
                if(!empty($newPassword)){
                    if($oldPassword == $newPassword){
                        return message('新密码不能与原密码相同！', false);
                    }
                    if(strlen($newPassword) < 6){
                        return message('新密码不能小于6位！', false);
                    }
                    $password = $newPassword;
                }else{
                    $password = $this->adminInfo['password'];
                }
                try{
                    Db::name('admin')
                        ->where('id', $this->adminId)
                        ->data(['username' => $username, 'password' => $password])
                        ->update();
                    return message('修改用户名成功！', true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }
        }
        return $this->render();
    }
}
