<?php
declare (strict_types = 1);

namespace app\admin\controller;

use app\admin\service\MenuService;
use app\common\controller\Backend;
use think\facade\Db;
use think\facade\View;

/**
 * 用户行为-控制器
 * @author 陌上花开
 * @since 2022/1/20
 * Class Action
 * @package app\admin\controller
 */
class Index extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    /**
     * 后台主入口
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since: 2022/6/30
     * @author 陌上花开
     */
    public function index()
    {
        //return hook('mail',['to' => '2129876388@qq.com', 'title' => '换绑邮箱通知', 'content' => '验证码:11111']);
        //return hook('wxPushUserNotice',['title' => 1, 'content' => '12', 'to' => 'UID_Kl7r77sruvFSn8gdk4DfkDS3eAW5','contentType' => 1]);
        //hook('testhook');
        // 取消模板布局
        //$this->app->view->layout(false);
        try{
            $meunService = new MenuService();
            $menuList = $meunService->getList();
            // Shared layout is role-driven; business menu source remains unchanged.
            View::assign([
                'layoutRole' => 'admin',
                'layoutAvatar' => '//q4.qlogo.cn/headimg_dl?dst_uin='.$this->adminInfo['qq'].'&spec=100',
                'layoutUsername' => t('common_ui.admin_label'),
                'layoutAdminQQ' => $this->adminInfo['qq'] ?: '',
                'menuList' => $menuList,
            ]);
            return View::fetch(APP_PATH . DS . 'common' . DS . 'view' . DS . 'layout' . DS . 'main_layout.html');
        }catch (\Exception $e){
            return $this->render('/public/error', ['msg' => $e->getMessage()]);
        }
    }

    /**
     * 欢迎页
     * @author 陌上花开
     * @since: 2022/6/30
     */
    public function main(){
        $authCount = Db::name('auth')->count('id');
        $authYesterday = Db::name('auth')->whereTime('addtime', 'yesterday')->count('id');
        $authToday = Db::name('auth')->whereTime('addtime', 'today')->count('id');
        $authIncrease = $authToday - $authYesterday;

        $appCount = Db::name('app')->count('id');

        $pirateCount = Db::name('pirate')->count('id');
        $pirateYesterday = Db::name('pirate')->whereTime('addtime', 'yesterday')->count('id');
        $pirateToday = Db::name('pirate')->whereTime('addtime', 'today')->count('id');
        $pirateIncrease = $pirateToday - $pirateYesterday;

        $userCount = Db::name('user')->count('id');
        $userYesterday = Db::name('user')->whereTime('addtime', 'yesterday')->count('id');
        $userToday = Db::name('user')->whereTime('addtime', 'today')->count('id');
        $userIncrease = $userToday - $userYesterday;
        $logList = Db::name('log')->order('id' ,'desc')->field('title,create_time')->where(['username' => $this->adminId, 'is_admin' => 1])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $balanceRanking = Db::name('user')->order('balance' ,'desc')->field('username,balance')->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $integralRanking = Db::name('user')->order('integral' ,'desc')->field('username,integral')->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);

        // Pending items
        $pendingPlugins = Db::name('plugin')->where('status', 0)->count('id');
        $pendingFeedback = Db::name('feedback')->where('status', 0)->count('id');
        $pendingOrders = Db::name('order')->where('status', 0)->count('id');

        // Latest plugins & orders
        $latestPlugins = Db::name('plugin')->order('id', 'desc')->limit(5)->field('id,name,icon,author,version,status,created_at')->select()->toArray();
        $recentOrders = Db::name('order')
            ->alias('o')
            ->join('user u', 'o.userid = u.id', 'left')
            ->order('o.id', 'desc')
            ->limit(5)
            ->field('o.id, o.trade_no, o.name, o.money, o.status, o.addtime, u.username')
            ->select()
            ->toArray();

        // Today stats
        $todayAuths = Db::name('auth')->whereTime('addtime', 'today')->count('id');
        $todayOrders = Db::name('order')->whereTime('addtime', 'today')->count('id');
        $todayDownloads = Db::name('plugin_download')->whereTime('created_at', 'today')->count('id');
        $weekTrend = [];
        $weekAuthMax = 1;
        $weekUserMax = 1;
        for ($i = 6; $i >= 0; $i--) {
            $start = date('Y-m-d 00:00:00', strtotime('-' . $i . ' days'));
            $end = date('Y-m-d 23:59:59', strtotime('-' . $i . ' days'));
            $authNum = Db::name('auth')->whereTime('addtime', 'between', [$start, $end])->count('id');
            $userNum = Db::name('user')->whereTime('addtime', 'between', [$start, $end])->count('id');
            $weekAuthMax = max($weekAuthMax, $authNum);
            $weekUserMax = max($weekUserMax, $userNum);
            $weekTrend[] = [
                'day' => date('m-d', strtotime($start)),
                'auth' => $authNum,
                'user' => $userNum,
            ];
        }
        foreach ($weekTrend as &$trendItem) {
            $trendItem['auth_rate'] = max(6, round($trendItem['auth'] / $weekAuthMax * 100));
            $trendItem['user_rate'] = max(6, round($trendItem['user'] / $weekUserMax * 100));
        }
        unset($trendItem);

        View::assign([
            'log_list' => $logList,
            'balance_ranking' => $balanceRanking,
            'integral_ranking' => $integralRanking,
            'auth_count' => $authCount,
            'auth_increase' => $authIncrease,
            'app_count' => $appCount,
            'pirate_count' => $pirateCount,
            'pirate_increase' => $pirateIncrease,
            'user_count' => $userCount,
            'user_increase' => $userIncrease,
            'pending_plugins' => $pendingPlugins,
            'pending_feedback' => $pendingFeedback,
            'pending_orders' => $pendingOrders,
            'latest_plugins' => $latestPlugins,
            'recent_orders' => $recentOrders,
            'today_auths' => $todayAuths,
            'today_orders' => $todayOrders,
            'today_downloads' => $todayDownloads,
            'week_trend' => $weekTrend,
            'week_auth_max' => $weekAuthMax,
            'week_user_max' => $weekUserMax,
        ]);
        return $this->render();
    }

    public function editPassword(){
        if(IS_POST){
            $post = $this->request->post();
            $username = !empty($post['username'])?$post['username']:null;
            $oldPassword = !empty($post['oldPassword'])?$post['oldPassword']:null;
            $newPassword = !empty($post['newPassword'])?$post['newPassword']:null;
            if(empty($username)){
                return message(t('login.please_enter_username'), false);
            }
            if(empty($oldPassword)){
                return message(t('user.old_password_empty'), false);
            }
            if(get_password($oldPassword) != $this->adminInfo['password']){
                return message(t('user.old_password_wrong'), false);
            }
            if($username == $this->adminInfo['username']){
                if(empty($newPassword)){
                    return message(t('user.new_password_empty'), false);
                }
                if($oldPassword == $newPassword){
                    return message(t('user.new_password_same'), false);
                }
                if(strlen($newPassword) < 6){
                    return message(t('user.new_password_short'), false);
                }
                try{
                    Db::name('admin')
                        ->where('id', $this->adminId)
                        ->data(['password' => get_password($newPassword)])
                        ->update();
                    return message(t('user.password_change_success'), true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }else{
                $row = Db::name('admin')->where('username', $username)->find();
                if($row){
                    return message(t('user.username_exists'), false);
                }
                if(!empty($newPassword)){
                    if($oldPassword == $newPassword){
                        return message(t('user.new_password_same'), false);
                    }
                    if(strlen($newPassword) < 6){
                        return message(t('user.new_password_short'), false);
                    }
                    $password = $newPassword;
                }else{
                    $password = $this->adminInfo['password'];
                }
                try{
                    Db::name('admin')
                        ->where('id', $this->adminId)
                        ->data(['username' => $username, 'password' => get_password($password)])
                        ->update();
                    return message(t('user.username_change_success'), true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }
        }
        return $this->render();
    }

    public function unbindWechatMp()
    {
        if (!IS_POST) {
            return message('非法请求', false);
        }
        try {
            Db::name('admin')->where('id', $this->adminId)->data(['wechat_openid' => ''])->update();
            return message('微信公众号解绑成功', true);
        } catch (\Exception $e) {
            return message('微信公众号解绑失败', false);
        }
    }
}
