<?php

declare(strict_types=1);

/**
 * Build the non-destructive 4.2.9 legacy bridge table definitions.
 *
 * Only CREATE TABLE blocks for the explicit allowlist are copied. Data
 * statements and destructive DDL from the installer SQL are never emitted.
 */

$root = dirname(__DIR__);
$sourcePath = $root . '/app/QH_Auth.sql';
$targetPath = $root . '/database/migrations/20260816_legacy_429_bridge_tables.sql';

$tables = [
    'QH_feedback',
    'QH_feedback_reply',
    'QH_notification',
    'QH_point_log',
    'QH_wechat_mp_login',
    'QH_point_product',
    'QH_point_exchange_record',
    'QH_point_product_reward',
    'QH_balance_log',
    'QH_withdraw',
    'QH_checkin_record',
    'QH_carousel',
    'QH_user_notice',
    'QH_discount_code',
    'QH_rebate_record',
    'QH_plugin',
    'QH_plugin_versions',
    'QH_plugin_resources',
    'QH_plugin_order',
    'QH_plugin_comment',
    'QH_plugin_rating',
    'QH_plugin_download',
    'QH_plugin_download_token',
    'QH_plugin_purchase',
    'QH_loginlog',
];

$source = file_get_contents($sourcePath);
if ($source === false) {
    fwrite(STDERR, "Cannot read {$sourcePath}\n");
    exit(1);
}

$blocks = [];
foreach ($tables as $table) {
    $quoted = preg_quote($table, '/');
    $pattern = '/CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+`' . $quoted . '`\s*\(.*?\)\s*ENGINE\s*=.*?;/is';
    $count = preg_match_all($pattern, $source, $matches);
    if ($count !== 1) {
        fwrite(STDERR, "Expected exactly one CREATE TABLE block for {$table}; found {$count}\n");
        exit(2);
    }

    $block = preg_replace(
        '/^CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?/i',
        'CREATE TABLE IF NOT EXISTS',
        trim($matches[0][0])
    );
    if (!is_string($block)) {
        fwrite(STDERR, "Failed to normalize {$table}\n");
        exit(3);
    }
    $blocks[] = $block;
}

$output = "-- Generated by deploy/build-legacy-bridge.php.\n"
    . "-- Non-destructive table bridge for a 4.2.9 database copied into the new environment.\n"
    . "-- This file intentionally contains CREATE TABLE IF NOT EXISTS statements only.\n\n"
    . implode("\n\n", $blocks)
    . "\n";

if (preg_match('/\b(?:DROP|TRUNCATE|DELETE|UPDATE|INSERT|REPLACE|ALTER|CALL|PROCEDURE)\b/i', $output)) {
    fwrite(STDERR, "Generated SQL contains a prohibited statement\n");
    exit(4);
}

if (file_put_contents($targetPath, $output) === false) {
    fwrite(STDERR, "Cannot write {$targetPath}\n");
    exit(5);
}

fwrite(STDOUT, sprintf("Generated %d safe CREATE TABLE statements\n", count($blocks)));
