<?php

namespace app\pay\controller;

use app\common\controller\PayBackend;
use app\pay\service\CommonService;
use app\pay\library\alipay\AlipayTradeService;
use app\pay\library\epay\EpayNotify;
use think\facade\Config;
use think\facade\Db;

class AliPay extends PayBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CommonService();
    }

    public function alipayReturn(){
        $get = request()->get();
        $config = Config::get('payconfig.zfb.alipay_config');
        //异步通知地址
        $config['notify_url'] = SITE_URL . url('/AliPay/alipayNotify');
        //同步通知地址
        $config['return_url'] = SITE_URL . url('/AliPay/alipayReturn.php');
        //计算得出通知验证结果
        $alipaySevice = new AlipayTradeService($config);
        //$alipaySevice->writeLog(var_export($_POST,true));
        $verify_result = $alipaySevice->check($get);

        if($verify_result && (conf('alipay_api') == 1 || conf('alipay_api') == 3)) {//验证成功
            //商户订单号
            $out_trade_no = isset($get['out_trade_no'])?$get['out_trade_no']:null;
            //支付宝交易号
            $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
            //交易金额
            $total_amount = isset($get['total_amount'])?$get['total_amount']:null;
            if(empty($out_trade_no)) return $this->render('public/error', ['msg' => '订单号不能为空！[errorCode:PayOrderIdEmpty]','time' => 5, 'url' => '/']);
            if(empty($trade_no)) return $this->render('public/error', ['msg' => '订单交易号不能为空！[errorCode:PayOrderApiIdEmpty]','time' => 5, 'url' => '/']);
            if(empty($total_amount)) return $this->render('public/error', ['msg' => '订单交易金额不能为空！[errorCode:PayOrderMoneyEmpty]','time' => 5, 'url' => '/']);
            $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();

            if ($srow['status'] == 0) {
                //付款完成后，支付宝系统发送该交易状态通知
                $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                if($result){
                    Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                    $this->service->processOrder($srow);
                }
                return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
            }else{
                return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
            }

        } else {
            //验证失败
            return $this->render('public/error', ['msg' => '验证订单交易状态失败！[errorCode:CheckPayStatusError]','time' => 5, 'url' => '/']);
        }
    }

    public function alipayNotify(){
        $post = request()->post();
        $config = Config::get('payconfig.zfb.alipay_config');
        //异步通知地址
        $config['notify_url'] = SITE_URL . url('/AliPay/alipayNotify');
        //同步通知地址
        $config['return_url'] = SITE_URL . url('/AliPay/alipayReturn.php');
        //计算得出通知验证结果
        $alipaySevice = new AlipayTradeService($config);
//$alipaySevice->writeLog(var_export($_POST,true));
        $verify_result = $alipaySevice->check($post);

        if($verify_result && (conf('alipay_api') == 1 || conf('alipay_api') == 3)) {//验证成功
            //商户订单号
            $out_trade_no = isset($post['out_trade_no'])?$post['out_trade_no']:null;
            //支付宝交易号
            $trade_no = isset($post['trade_no'])?$post['trade_no']:null;
            //交易金额
            $total_amount = isset($post['total_amount'])?$post['total_amount']:null;
            //交易状态
            $trade_status = isset($post['trade_status'])?$post['trade_status']:null;
            //买家支付宝
            $buyer_id = isset($post['buyer_id'])?$post['buyer_id']:null;

            $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();

            if ($trade_status == 'TRADE_SUCCESS' && $srow['status']==0) {
                //付款完成后，支付宝系统发送该交易状态通知
                $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                if($result){
                    Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                    $this->service->processOrder($srow);
                }
            }
            echo "success";
        } else {
            //验证失败
            echo "fail";
        }
    }

    public function kayixinNotify(){
        $post = request()->post();
        $config = Config::get('payconfig.zfb.kayixin_config');
        //计算得出通知验证结果
        $alipayNotify = new EpayNotify($config);
        $verify_result = $alipayNotify->verifyNotify();

        if($verify_result && conf('alipay_api') == 7) {//验证成功
            //商户订单号
            $out_trade_no = isset($post['out_trade_no'])?$post['out_trade_no']:null;
            //支付宝交易号
            $trade_no = isset($post['trade_no'])?$post['trade_no']:null;
            //交易金额
            $total_fee = isset($post['total_fee'])?$post['total_fee']:null;
            //交易状态
            $trade_status = isset($post['trade_status'])?$post['trade_status']:null;
            //买家支付宝
            $buyer_id = isset($post['buyer_id'])?$post['buyer_id']:null;

            $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();

            if($trade_status == 'TRADE_FINISHED') {
                //退款日期超过可退款期限后（如三个月可退款），支付宝系统发送该交易状态通知
            } else if ($trade_status == 'TRADE_SUCCESS' && $srow['status'] == 0) {
                //付款完成后，支付宝系统发送该交易状态通知
                $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                if($result){
                    Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                    $this->service->processOrder($srow);
                }
            }
            echo "success";
        } else {
            //验证失败
            echo "fail";
        }
    }

    public function kayixinReturn(){
        $post = request()->post();
        $config = Config::get('payconfig.zfb.kayixin_config');
        //计算得出通知验证结果
        $alipayNotify = new EpayNotify($config);
        $verify_result = $alipayNotify->verifyReturn();
        if($verify_result && conf('alipay_api') == 7) {
            //商户订单号
            $out_trade_no = isset($post['out_trade_no'])?$post['out_trade_no']:null;
            //支付宝交易号
            $trade_no = isset($post['trade_no'])?$post['trade_no']:null;
            //交易金额
            $total_fee = isset($post['total_fee'])?$post['total_fee']:null;
            //交易状态
            $trade_status = isset($post['trade_status'])?$post['trade_status']:null;

            $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();

            if($trade_status == 'TRADE_FINISHED' || $trade_status == 'TRADE_SUCCESS') {
                if($srow['status'] == 0){
                    $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                    if($result){
                        Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                        $this->service->processOrder($srow);
                    }
                    return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
                }else{
                    return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
                }
            } else {
                return $this->render('public/error', ['msg' => '该订单未支付！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
            }
        } else {
            //验证失败
            return $this->render('public/error', ['msg' => '验证订单交易状态失败！[errorCode:CheckPayStatusError]','time' => 5, 'url' => '/']);
        }
    }

}