<?php

namespace app\pay\controller;

use app\common\controller\PayBackend;
use app\pay\service\CommonService;
use think\facade\Config;
use think\facade\Db;
use think\facade\View;

class CodePay extends PayBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CommonService();
    }

    public function index(){
        $qr = ''; //初始化一个默认的二维码
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        $type = isset($get['type'])?$get['type']:null;
        if(!is_numeric($trade_no)) return $this->render('public/error', ['msg' => '订单号格式错误！[errorCode:PayOrderApiIdError]','time' => 5, 'url' => '/']);
        if (conf('alipay_api') != 5 && conf('qqpay_api') != 5 && conf('wxpay_api') !=5 ) {
            return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        }
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);

        if(!is_file('/Assets/pay/codepay/qrcode.php')){ //如果存在这个文件 表示codepay目录上传 使用本地资源否则用远程资源
            $codepay_path = "https://codepay.fateqq.com";
        }else{
            $codepay_path = "/Assets/pay/codepay/";
        }
        if ($type == 'wxpay') {
            $codepay_config = Config::get('payconfig.wx.codepay_config');
            $type = 3;
            $typeName = '微信';
            $codepay_wxpay = '/Assets/pay/codepay/'.$codepay_config['codepay_wxpay'];
            $codepay_zsm = '/Assets/pay/codepay/'.$codepay_config['codepay_zsm'];
            if(is_file($codepay_wxpay)){ //如果赞赏码存在 则使用赞赏码
                $qr = $codepay_config['qrcode_url'] = $codepay_wxpay;
            }else if(is_file($codepay_zsm)){ //如果赞赏码存在 则使用赞赏码
                $qr = $codepay_config['qrcode_url'] = $codepay_zsm;
            }
        } else if ($type == 'qqpay' || $type == 'tenpay') {
            $codepay_config = Config::get('payconfig.qq.codepay_config');
            $typeName = 'QQ';
            $type = 2;
            $codepay_qqpay = '/Assets/pay/codepay/'.$codepay_config['codepay_qqpay'];
            $codepay_zsm = '/Assets/pay/codepay/'.$codepay_config['codepay_zsm'];
            if(is_file($codepay_qqpay)){ //如果赞赏码存在 则使用赞赏码
                $qr = $codepay_config['qrcode_url'] = $codepay_qqpay;
            }else if(is_file($codepay_zsm)){ //如果赞赏码存在 则使用赞赏码
                $qr = $codepay_config['qrcode_url'] = $codepay_zsm;
            }
        } else {
            $codepay_config = Config::get('payconfig.zfb.codepay_config');
            $type = 1;
            $typeName = '支付宝';
            $codepay_alipay = '/Assets/pay/codepay/'.$codepay_config['codepay_alipay'];
            $codepay_zsm = '/Assets/pay/codepay/'.$codepay_config['codepay_zsm'];
            if(is_file($codepay_alipay)){ //如果赞赏码存在 则使用赞赏码
                $qr = $codepay_config['qrcode_url'] = $codepay_alipay;
            }else if(is_file($codepay_zsm)){ //如果赞赏码存在 则使用赞赏码
                $qr = $codepay_config['qrcode_url'] = $codepay_zsm;
            }
        }

        $price = $row['money'];
        $param = $trade_no;

        $pay_id = get_client_ip();
        if($row['input']) $pay_id .= '_'.mb_substr($row['input'], 0, 20, 'UTF-8');
        $parameter = array(
            "id" => $codepay_config['id'],//平台ID号
            "type" => $type,//支付方式
            "price" => $price,//原价
            "pay_id" => $pay_id, //可以是用户ID,站内商户订单号,用户名
            "param" => $param,//自定义参数
//            "https" => 1,//启用HTTPS
            "act" => $codepay_config['act'],
            "outTime" => $codepay_config['outTime'],//二维码超时设置
            "page" => $codepay_config['page'],//付款页面展示方式
            "return_url" => SITE_URL.url('/CodePay/return'),//付款后附带加密参数跳转到该页面
            "notify_url" => SITE_URL.url('/CodePay/notify'),//付款后通知该页面处理业务
            "style" => $codepay_config['style'],//付款页面风格
            "user_ip" => get_client_ip(),//用户IP
            "out_trade_no" => $param,//单号去重复
            "createTime" => time(),//服务器时间
            "qrcode_url" => $codepay_config['qrcode_url'],//本地化二维码
            "chart" => strtolower('utf-8')//字符编码方式
            //其他业务参数根据在线开发文档，添加参数.文档地址:https://codepay.fateqq.com/apiword/
            //如"参数名"=>"参数值"
        );
        $user_data = array(
            "return_url" => 'codepay_return.php',
            "type" => $type,
            "outTime" => $codepay_config["outTime"],
            "codePay_id" => $codepay_config["id"],
            "out_trade_no" => $param,
            "price" => $price,
            "money" => $price,
            "order_id" => $param,
            "subject" => $row['name']
        ); //传给网页JS去执行
        $user_data["qrcode_url"] = $codepay_config["qrcode_url"];
        //中间那log 默认为8秒后隐藏
        //改为自己的替换img目录下的use_开头的图片 你要保证你的二维码遮挡不会影响扫码
        //二维码容错率决定你能遮挡多少部分
        $user_data["logShowTime"] = $user_data["qrcode_url"]?1:8*1000;
        $codepay_back_data = $this->getCodepayHtml($parameter,$codepay_config['key']);
        $user_data['money'] = $codepay_back_data['money'];
        $codepay_html = $codepay_back_data['codepay_html'];
        View::assign([
            'typeName' => $typeName,
            'codepay_path' => $codepay_path,
            'type' => $type,
            'price' => $price,
            'user_data' => $user_data,
            'qr' => $qr,
            'codepay_html' => $codepay_html,
        ]);
        return $this->render();
    }

    private function create_link($params, $codepay_key, $apiHost=""){
        ksort($params); //重新排序$data数组
        reset($params); //内部指针指向数组中的第一个元素
        $sign = '';
        $urls = '';
        foreach ($params AS $key => $val) {
            if ($val == '') continue;
            if ($key != 'sign') {
                if ($sign != '') {
                    $sign .= "&";
                    $urls .= "&";
                }
                $sign .= "$key=$val"; //拼接为url参数形式
                $urls .= "$key=" . urlencode($val); //拼接为url参数形式
            }
        }
        $key = md5($sign . $codepay_key);//替换为自己的密钥
        $query = $urls . '&sign=' . $key; //创建订单所需的参数
        $url = $apiHost.$query; //支付页面
        return array("url" => $url, "query" => $query, "sign" => $sign, "param" => $urls);
    }

    private function getCodepayHtml($parameter,$key){
        $codepay_json='';
        if ($parameter['page'] != 3) { //只要不为3 返回JS 就去服务器加载资源
            $parameter['page'] = "4"; //设置返回JSON
            $back = $this->create_link($parameter, $key, 'http://api4.xiuxiu888.com/creat_order/?'); //生成支付URL
            $timeout = 5; //超时设置 5秒
            if (function_exists('curl_init')) {
                $ch = curl_init(); //使用curl请求
                curl_setopt($ch, CURLOPT_URL, $back['url']);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
                $codepay_json = curl_exec($ch);
                curl_close($ch);
            }else if(function_exists('file_get_contents')){
                $context = array();
                $context['http'] = array('timeout'=>$timeout,'method' => 'GET');
                $codepay_json = file_get_contents($back['url'], false, stream_context_create($context));
            }
        }
        if (empty($codepay_json)) { //如果没有获取到远程HTML 则走JS创建订单
            $parameter['call'] = "callback";
            $parameter['page'] = "3";
            $qr='';
            $money=$parameter['price'];
            $back = $this->create_link($parameter, $key, 'https://api.xiuxiu888.com/creat_order/?');
            $codepay_html = '<script src="' . $back['url'] . '"></script>'; //JS数据
        } else { //获取到了JSON
            $codepay_data = json_decode($codepay_json);
            $qr = $codepay_data ? $codepay_data->qrcode : '';
            $money = $codepay_data && $codepay_data->money ? $codepay_data->money : $parameter['price'];
            $codepay_html = "<script>callback({$codepay_json})</script>"; //JSON数据
        }
        return array("codepay_html" => $codepay_html, "qr" => $qr, "money" => $money);
    }

    private function codepayMsg($msg, $quit = true){
        $get = request()->get();
        $js = isset($get['js']) ? $get['js'] : '';
        echo $js?"cron_back&&cron_back({$msg})":json_encode($msg);
        if($quit)exit(0);
    }

    private function create_link2($params, $codepay_key, $host = "")
    {
        ksort($params); //重新排序$data数组
        reset($params); //内部指针指向数组中的第一个元素
        $sign = '';
        $urls = '';
        foreach ($params AS $key => $val) {
            if ($val == '') continue;
            if ($key != 'sign') {
                if ($sign != '') {
                    $sign .= "&";
                    $urls .= "&";
                }
                $sign .= "$key=$val"; //拼接为url参数形式
                $urls .= "$key=" . urlencode($val); //拼接为url参数形式
            }
        }

        $key = md5($sign . $codepay_key);
        $query = $urls . '&sign=' . $key; //创建订单所需的参数
        $apiHost = $host ? $host : "http://api2.fateqq.com:52888/api/orders/?";
        $url = $apiHost . $query; //支付页面
        return array("url" => $url, "query" => $query, "sign" => $sign, "param" => $urls);
    }
    /*支付接口订单监控文件
        说明：用于请求支付接口订单列表，同步未通知到本站的订单，防止漏单。

        注意：千万不要监控太快或使用多节点监控！！！否则会被支付接口自动屏蔽IP地址
        */
    public function cron(){
        $get = request()->get();
        $order_type = 0;//补单支付方式 0全部 1支付宝 2QQ 3微信
        $order_status = 1;//状态0为全部 1为通知失败  2成功状态
        $limit = 5; //检测订单数量限制 防止数据库压力过大

        $ua = $_SERVER['HTTP_USER_AGENT'] ?? '';
        if ($ua && preg_match('/Baiduspider/', $ua)) return;

        if (function_exists("set_time_limit")) {
            @set_time_limit(0);
        }
        if (function_exists("ignore_user_abort")) {
            @ignore_user_abort(true);
        }

        if (conf('alipay_api') != 5 && conf('qqpay_api') != 5 && conf('wxpay_api') !=5) $this->codepayMsg('{"error":"not open"}');

        if(conf('alipay_api') == 5){
            $pay_config = Config::get('payconfig.zfb.codepay_config');
            $this->cronCore($pay_config['id'], $pay_config['key'] ,$limit, $order_type, $order_status);
        }

        if(conf('wxpay_api') == 5){
            $pay_config = Config::get('payconfig.wx.codepay_config');
            $this->cronCore($pay_config['id'], $pay_config['key'] ,$limit, $order_type, $order_status);
        }

        if(conf('qqpay_api') == 5){
            $pay_config = Config::get('payconfig.qq.codepay_config');
            $this->cronCore($pay_config['id'], $pay_config['key'] ,$limit, $order_type, $order_status);
        }
    }

    private function cronCore($id,$key,$limit,$order_type,$order_status){
        $get = request()->get();
        $lastTime = (int)session('last_api_time');  //储存上次请求时间到变量

        session('last_api_time', time());

        if (time() - $lastTime < 60) $this->codepayMsg('{"error":"Too frequent"}');

        $api_data = array(
            "id" => $id,//平台ID号
            "ip" => get_client_ip(),//请求人的IP 必传
            "req_time" => time(),//请求时间
            "limit" => $limit,
            "api" => 'ds1',
            "chart" => 'utf-8',
            "type" => $order_type,//支付方式 0全部 1支付宝 2QQ 3微信
            "status" => $order_status,//状态0为全部 1为通知失败  2成功状态
        );
        $api_url = $this->create_link2($api_data, $key, 'http://api2.fateqq.com:52888/api/orders/?'); //生成API请求地址

        $back_data = curl_get($api_url['url']);

        $arr = json_decode($back_data, true);

        if ($arr && $arr['code'] == 1) {
            $count = 0;
            $success_trade = '';
            $api_data['trade_no'] = '';
            $api_data['count'] = 0;
            if (!$arr['nonce_str'] || md5($arr['nonce_str'] . $key) != $arr['sign']) $this->codepayMsg('{"error":"fail"}');
            $sign = '';
            $urls = '';
            foreach ($get AS $key => $val) {
                if ($val == '') continue;
                if ($key != 'sign') {
                    if ($sign != '') {
                        $sign .= "&";
                        $urls .= "&";
                    }
                    $sign .= "$key=$val"; //拼接为url参数形式
                    $urls .= "$key=" . urlencode($val); //拼接为url参数形式
                }
            }
            foreach ($arr['data'] as $row) {
                if ($row['status'] == 1 && $count < $limit) {
                    $count += 1;
                    $out_trade_no = $row['param'];
                    if (!$out_trade_no) continue;
                    $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();
                    if ($srow && $srow['status'] == 0) {
                        Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1, 'endtime' => datetime()]);
                        $this->service->processOrder($srow);
                        $api_data['count'] += 1;
                        if ($row['trade_no']) $api_data['trade_no'] += $row['trade_no'] + ',';
                    }
                }
            }
            echo '{"code":1,"success":' . (int)$api_data['count'] . '}';
            if (!empty($api_data['trade_no'])) {
                $api_url = $this->create_link2($api_data, conf('codepay_key'), 'http://api2.fateqq.com:52888/api/up_orders/?'); //生成API请求地址
                curl_get($api_url['url']);
            }
            exit(0);
        } else {
            $this->codepayMsg('{"error":"not data"}');
        }
    }

    public function return(){
        $get = request()->get();
        ksort($get); //排序get参数
        reset($get); //内部指针指向数组中的第一个元素
        $sign = '';
        $urls = '';
        foreach ($get AS $key => $val) {
            if ($val == '') continue;
            if ($key != 'sign') {
                if ($sign != '') {
                    $sign .= "&";
                    $urls .= "&";
                }
                $sign .= "$key=$val"; //拼接为url参数形式
                $urls .= "$key=" . urlencode($val); //拼接为url参数形式
            }
        }
        if (conf('alipay_api') != 5 && conf('qqpay_api') != 5 && conf('wxpay_api') !=5) {
            return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        } elseif (empty($codepay_config['key']) || !$get['pay_no'] || md5($sign . $codepay_config['key']) != $get['sign']) { //不合法的数据 KEY密钥为你的密钥
            return $this->render('public/error', ['msg' => '验证订单交易状态失败！[errorCode:CheckPayStatusError]','time' => 5, 'url' => '/']);
        } else { //合法的数据
            //订单号
            $out_trade_no = isset($get['param'])?$get['param']:null;
            //交易号
            $trade_no = isset($get['pay_no'])?$get['pay_no']:null;

            if(empty($out_trade_no)) return $this->render('public/error', ['msg' => '请提交订单号！[errorCode:PayOrderIdEmpty]','time' => 5, 'url' => '/']);
            if(empty($trade_no)) return $this->render('public/error', ['msg' => '请提交交易号！[errorCode:PayOrderApiIdEmpty]','time' => 5, 'url' => '/']);

            $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();
            if($srow['status']==0){
                $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                if($result) {
                    Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                    $this->service->processOrder($srow);
                }
                return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
            }else{
                return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：'.$out_trade_no,'time' => 5, 'url' => '/']);
            }
        }
    }

    public function notify(){
        $post = request()->post();
        ksort($post); //排序post参数
        reset($post); //内部指针指向数组中的第一个元素
        $sign = '';
        $urls = '';
        foreach ($post AS $key => $val) {
            if ($val == '') continue;
            if ($key != 'sign') {
                if ($sign != '') {
                    $sign .= "&";
                    $urls .= "&";
                }
                $sign .= "$key=$val"; //拼接为url参数形式
                $urls .= "$key=" . urlencode($val); //拼接为url参数形式
            }
        }

        if (conf('alipay_api') != 5 && conf('qqpay_api') != 5 && conf('wxpay_api') !=5) {
            exit('fail');
        } elseif (empty($codepay_config['key']) || !$_POST['pay_no'] || md5($sign . $codepay_config['key']) != $_POST['sign']) { //不合法的数据 KEY密钥为你的密钥
            exit('fail');
        } else { //合法的数据
            //订单号
            $out_trade_no = isset($get['param'])?$get['param']:exit('fail');
            //交易号
            $trade_no = isset($get['pay_no'])?$get['pay_no']:exit('fail');

            $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();
            if($srow['status']==0) {
                $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                if($result) {
                    Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                    $this->service->processOrder($srow);
                }
            }
            exit('success');
        }
    }
}