<?php

namespace app\pay\controller;

use app\common\controller\PayBackend;
use think\facade\Db;
use think\facade\Config;
use app\pay\library\epay\EpayNotify;
use app\pay\service\CommonService;
use think\Exception;
class EPay extends PayBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CommonService();
    }

    public function return(){
        //return $this->render('public/error', ['msg' => '111','time' => 5, 'url' => '/']);
        $get = request()->get();
        //订单号
        $out_trade_no = isset($get['out_trade_no'])?$get['out_trade_no']:null;
        //交易号
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        //交易状态
        $trade_status = isset($get['trade_status'])?$get['trade_status']:null;
        //金额
        $money = isset($get['money'])?$get['money']:null;
        if(empty($out_trade_no)) return $this->render('public/error', ['msg' => '订单号不能为空！[errorCode:PayOrderIdEmpty]','time' => 5, 'url' => '/']);
        if(empty($trade_no)) return $this->render('public/error', ['msg' => '订单交易号不能为空！[errorCode:PayOrderApiIdEmpty]','time' => 5, 'url' => '/']);
        if(empty($trade_status)) return $this->render('public/error', ['msg' => '订单交易状态不能为空！[errorCode:PayOrderStatusEmpty]','time' => 5, 'url' => '/']);
        if(empty($money)) return $this->render('public/error', ['msg' => '订单交易金额不能为空！[errorCode:PayOrderMoneyEmpty]','time' => 5, 'url' => '/']);
        $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();

        switch ($srow['channel']){
            case 'zfb_epay':
                $pay_config = Config::get('payconfig.zfb.epay_config');
                break;
            case 'wx_epay':
                $pay_config = Config::get('payconfig.wx.epay_config');
                break;
            case 'qq_epay':
                $pay_config = Config::get('payconfig.qq.epay_config');
                break;
            default:
                return $this->render('public/error', ['msg' => '获取该订单支付类型错误，请联系站长处理！[errorCode:GetPayChannelError]','time' => 5, 'url' => '/']);
        }
        //计算得出通知验证结果
        $epayNotify = new EpayNotify($pay_config);
        $verify_result = $epayNotify->verifyReturn();
        if($verify_result && (conf('alipay_api') == 2 || conf('qqpay_api') == 2 || conf('wxpay_api') == 2) && !empty($pay_config['partner']) && !empty($pay_config['key']) && !empty($pay_config['apiurl'])) {
            if ($trade_status == 'TRADE_FINISHED' || $trade_status == 'TRADE_SUCCESS') {
                if ($srow['status'] == 0 && round($srow['money'], 2) == round($money, 2)) {
                    try {
                        Db::name('pay')
                            ->where('trade_no', $out_trade_no)
                            ->data(['status' => 1])
                            ->update();
                        Db::name('pay')
                            ->where('trade_no', $out_trade_no)
                            ->data(['endtime' => datetime(), 'api_trade_no' => $trade_no])
                            ->update();
                        $this->service->processOrder($srow);
                        return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：' . $out_trade_no, 'time' => 5, 'url' => '/']);
                    } catch (\Exception $e) {
                        return $this->render('public/success', ['msg' => '您所购买的商品已付款成功，感谢购买！<br><br> 订单号：' . $out_trade_no, 'time' => 5, 'url' => '/']);
                    }
                } else {
                    return $this->render('public/error', ['msg' => '该订单未支付！[errorCode:PayOrderError] <br><br> 订单号：' . $out_trade_no, 'time' => 5, 'url' => '/']);
                }
            } else {
                //验证失败
                return $this->render('public/error', ['msg' => '验证订单交易状态失败！[errorCode:CheckPayStatusError]', 'time' => 5, 'url' => '/']);
            }
        }
    }

    public function notify(){
        $get = request()->get();
        //订单号
        $out_trade_no = isset($get['out_trade_no'])?$get['out_trade_no']:null;
        //交易号
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        //交易状态
        $trade_status = isset($get['trade_status'])?$get['trade_status']:null;
        //金额
        $money = isset($get['money'])?$get['money']:null;
        $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();

        switch ($srow['channel']){
            case 'zfb_epay':
                $pay_config = Config::get('payconfig.zfb.epay_config');
                break;
            case 'wx_epay':
                $pay_config = Config::get('payconfig.wx.epay_config');
                break;
            case 'qq_epay':
                $pay_config = Config::get('payconfig.qq.epay_config');
                break;
            default:
                exit('error');
        }

        //计算得出通知验证结果
        $epayNotify = new EpayNotify($pay_config);
        $verify_result = $epayNotify->verifyNotify();

        if($verify_result && (conf('alipay_api') == 2 || conf('qqpay_api') == 2 || conf('wxpay_api') == 2) && !empty($pay_config['partner']) && !empty($pay_config['key']) && !empty($pay_config['apiurl'])) {

            if($trade_status == 'TRADE_FINISHED' || $trade_status == 'TRADE_SUCCESS') {
                if($srow['status']==0 && round($srow['money'],2) == round($money,2)){
                    $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                    if($result) {
                        Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $trade_no]);
                        $this->service->processOrder($srow);
                    }
                }
            }
            echo "success";
        } else {
            //验证失败
            echo "fail";
        }
    }

}