<?php
/*
* +----------------------------------------------------------------------
* | SF 综合验证授权系统
* +----------------------------------------------------------------------
* | Quotes [ 花开的再灿烂，也有凋谢的一天，致我们过去的青春 ]
* +----------------------------------------------------------------------
* | Author: 陌上花开 <2129876388@qq.com>
* +----------------------------------------------------------------------
* | Date: 2022年1月19日 18:48:32
* +----------------------------------------------------------------------
*/

namespace app\pay\controller;

use app\common\controller\PayBackend;

/**
 * 空控制器
 * @author 陌上花开
 * @since 2020/7/4
 * Class Error
 * @package app\admin\controller
 */
class Error extends PayBackend
{
    /**
     * 初始化
     * @author 陌上花开
     * @since 2020/7/5
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 错误页面
     * @return mixed
     * @since 2020/7/4
     * @author 陌上花开
     */
    public function index()
    {
        return $this->render("public/404");
    }
}