<?php

namespace app\pay\controller;

use app\common\controller\PayBackend;
use app\pay\service\CommonService;
use think\facade\Db;
use think\facade\Log;
use app\pay\library\qqpay\QpayMchAPI;
use app\pay\library\qqpay\QpayMchUtil;
use app\pay\library\qqpay\QpayNotify;
use think\facade\View;

class QqPay extends PayBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CommonService();
    }

    public function index(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        if(conf('qqpay_api') != 1) return $this->render('public/error', ['msg' => t('pay.interface_disabled'),'time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => t('pay.order_not_exist'),'time' => 5, 'url' => '/']);
        if (!$this->ownsPaymentOrder($row)) return $this->render('public/error', ['msg' => t('pay.order_access_denied'),'time' => 5, 'url' => '/']);
        $ordername = $row['name'];

        //入参
        $params = array();
        $params["out_trade_no"] = $trade_no;
        $params["body"] = $ordername;
        $params["fee_type"] = "CNY";
        $params["notify_url"] = SITE_URL.url('/QqPay/notify');
        $params["spbill_create_ip"] = get_client_ip();
        $params["total_fee"] = qh_money_to_cents($row['money']);
        $params["trade_type"] = "NATIVE";

        //api调用
        $qpayApi = new QpayMchAPI('https://qpay.qq.com/cgi-bin/pay/qpay_unified_order.cgi', null, 10);
        $ret = $qpayApi->reqQpay($params);
        $result = QpayMchUtil::xmlToArray($ret);
        //print_r($arr);

        if($result['return_code'] == 'SUCCESS' && $result['result_code'] == 'SUCCESS'){
            $code_url = $result['code_url'];
        }elseif(isset($result["err_code"])){
            return $this->render('public/error', ['msg' => t('pay.qq_create_failed', ['code' => $result["err_code"]]),'time' => 5, 'url' => '/']);
        }else{
            return $this->render('public/error', ['msg' => t('pay.qq_create_failed', ['code' => $result["return_code"]]),'time' => 5, 'url' => '/']);
        }
        View::assign([
            'row' => $row,
            'code_url' => $code_url
        ]);
        return $this->render();
    }

    public function wapPay(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        if(conf('qqpay_api') != 1) return $this->render('public/error', ['msg' => t('pay.interface_disabled'),'time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => t('pay.order_not_exist'),'time' => 5, 'url' => '/']);
        if (!$this->ownsPaymentOrder($row)) return $this->render('public/error', ['msg' => t('pay.order_access_denied'),'time' => 5, 'url' => '/']);
        $ordername = $row['name'];
        //入参
        $params = array();
        $params["out_trade_no"] = $trade_no;
        $params["body"] = $ordername;
        $params["fee_type"] = "CNY";
        $params["notify_url"] = SITE_URL.url('/QqPay/notify');
        $params["spbill_create_ip"] = get_client_ip();
        $params["total_fee"] = qh_money_to_cents($row['money']);
        $params["trade_type"] = "NATIVE";

        //api调用
        $qpayApi = new QpayMchAPI('https://qpay.qq.com/cgi-bin/pay/qpay_unified_order.cgi', null, 10);
        $ret = $qpayApi->reqQpay($params);
        $result = QpayMchUtil::xmlToArray($ret);
        //print_r($arr);
        if($result['return_code']=='SUCCESS' && $result['result_code']=='SUCCESS'){
            $code_url = 'https://myun.tenpay.com/mqq/pay/qrcode.html?_wv=1027&_bid=2183&t='.$result['prepay_id'];
        }elseif(isset($result["err_code"])){
            return $this->render('public/error', ['msg' => t('pay.qq_create_failed', ['code' => $result["err_code"]]),'time' => 5, 'url' => '/']);
        }else{
            return $this->render('public/error', ['msg' => t('pay.qq_create_failed', ['code' => $result["return_code"]]),'time' => 5, 'url' => '/']);
        }
        if(strpos($_SERVER['HTTP_USER_AGENT'], 'QQ/') !== false){
            return $this->redirectTo($code_url);
        }
        View::assign([
            'row' => $row,
            'code_url' => $code_url
        ]);
        return $this->render();
    }

    public function notify(){
        try {
            $qpayNotify = new QpayNotify();
            $result = $qpayNotify->getParams();
        } catch (\Throwable $e) {
            echo "<xml><return_code>FAIL</return_code><return_msg>" . $e->getMessage() . "</return_msg></xml>";
            return;
        }
        //判断签名
        if($qpayNotify->verifySign() && conf('qqpay_api') == 1) {
            //判断签名及结果（即时到帐）
            if($result['trade_state'] == "SUCCESS") {
                //商户订单号
                $out_trade_no = $result['out_trade_no'];
                //QQ钱包订单号
                $transaction_id = $result['transaction_id'];
                //金额,以分为单位
                $total_fee = $result['total_fee'];
                //币种
                $fee_type = $result['fee_type'];

                //------------------------------
                //处理业务开始
                //------------------------------
                $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();
                if (!$srow || strtoupper((string)$fee_type) !== 'CNY'
                    || qh_money_to_cents($srow['money']) !== (int)$total_fee) {
                    echo "<xml><return_code>FAIL</return_code><return_msg>订单金额或币种校验失败</return_msg></xml>";
                    return;
                }
                if (!$this->completeOrder($srow, (string)$transaction_id)) {
                    echo "<xml><return_code>FAIL</return_code><return_msg>订单入账失败</return_msg></xml>";
                    return;
                }
                //------------------------------
                //处理业务完毕
                //------------------------------
                echo "<xml>
                          <return_code>SUCCESS</return_code>
                      </xml>";
            } else {
                echo "<xml>
                          <return_code>FAIL</return_code>
                      </xml>";
            }
        } else {
            //回调签名错误
            echo "<xml>
                      <return_code>FAIL</return_code>
                      <return_msg>签名失败</return_msg>
                  </xml>";
        }
    }

    private function completeOrder(array $row, string $apiTradeNo): bool
    {
        if ($apiTradeNo === '') {
            return false;
        }
        try {
            return (bool)Db::transaction(function () use ($row, $apiTradeNo) {
                $current = Db::name('pay')->where('trade_no', $row['trade_no'])->lock(true)->find();
                if (!$current) {
                    return false;
                }
                if ((int)$current['status'] >= 1) {
                    return true;
                }
                Db::name('pay')->where('trade_no', $current['trade_no'])->update([
                    'endtime' => datetime(),
                    'api_trade_no' => $apiTradeNo,
                ]);
                if ($this->service->processOrder($current) !== true) {
                    throw new \RuntimeException('QQ 钱包订单入账失败');
                }
                return Db::name('pay')
                    ->where('trade_no', $current['trade_no'])
                    ->where('status', 0)
                    ->update(['status' => 1]) === 1;
            });
        } catch (\Throwable $e) {
            Log::error('QQ 钱包订单入账失败', ['order' => (string)($row['trade_no'] ?? ''), 'error' => $e->getMessage()]);
            return false;
        }
    }
}
