<?php

namespace app\pay\controller;

use app\common\controller\PayBackend;
use app\pay\service\CommonService;
use think\facade\Db;
use app\pay\library\qqpay\QpayMchAPI;
use app\pay\library\qqpay\QpayMchUtil;
use app\pay\library\qqpay\QpayNotify;
use think\facade\View;

class QqPay extends PayBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CommonService();
    }

    public function index(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        if(conf('qqpay_api') != 1) return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);
        $ordername = $row['name'];

        //入参
        $params = array();
        $params["out_trade_no"] = $trade_no;
        $params["body"] = $ordername;
        $params["fee_type"] = "CNY";
        $params["notify_url"] = SITE_URL.url('/QqPay/notify');
        $params["spbill_create_ip"] = get_client_ip();
        $params["total_fee"] = intval($row['money'] * 100);
        $params["trade_type"] = "NATIVE";

        //api调用
        $qpayApi = new QpayMchAPI('https://qpay.qq.com/cgi-bin/pay/qpay_unified_order.cgi', null, 10);
        $ret = $qpayApi->reqQpay($params);
        $result = QpayMchUtil::xmlToArray($ret);
        //print_r($arr);

        if($result['return_code'] == 'SUCCESS' && $result['result_code'] == 'SUCCESS'){
            $code_url = $result['code_url'];
        }elseif(isset($result["err_code"])){
            return $this->render('public/error', ['msg' => 'QQ钱包支付下单失败！['.$result["err_code"].'] '.$result["err_code_des"],'time' => 5, 'url' => '/']);
        }else{
            return $this->render('public/error', ['msg' => 'QQ钱包支付下单失败！['.$result["return_code"].'] '.$result["return_msg"],'time' => 5, 'url' => '/']);
        }
        View::assign([
            'row' => $row,
            'code_url' => $code_url
        ]);
        return $this->render();
    }

    public function wapPay(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        if(conf('qqpay_api') != 1) return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);
        $ordername = $row['name'];
        //入参
        $params = array();
        $params["out_trade_no"] = $trade_no;
        $params["body"] = $ordername;
        $params["fee_type"] = "CNY";
        $params["notify_url"] = SITE_URL.url('/QqPay/notify');
        $params["spbill_create_ip"] = get_client_ip();
        $params["total_fee"] = intval($row['money'] * 100);
        $params["trade_type"] = "NATIVE";

        //api调用
        $qpayApi = new QpayMchAPI('https://qpay.qq.com/cgi-bin/pay/qpay_unified_order.cgi', null, 10);
        $ret = $qpayApi->reqQpay($params);
        $result = QpayMchUtil::xmlToArray($ret);
        //print_r($arr);
        if($result['return_code']=='SUCCESS' && $result['result_code']=='SUCCESS'){
            $code_url = 'https://myun.tenpay.com/mqq/pay/qrcode.html?_wv=1027&_bid=2183&t='.$result['prepay_id'];
        }elseif(isset($result["err_code"])){
            return $this->render('public/error', ['msg' => 'QQ钱包支付下单失败！['.$result["err_code"].'] '.$result["err_code_des"],'time' => 5, 'url' => '/']);
        }else{
            return $this->render('public/error', ['msg' => 'QQ钱包支付下单失败！['.$result["return_code"].'] '.$result["return_msg"],'time' => 5, 'url' => '/']);
        }
        if(strpos($_SERVER['HTTP_USER_AGENT'], 'QQ/') !== false){
            return $this->redirectTo($code_url);
        }
        View::assign([
            'row' => $row,
            'code_url' => $code_url
        ]);
        return $this->render();
    }

    public function notify(){
        $qpayNotify = new QpayNotify();
        $result = $qpayNotify->getParams();
        //判断签名
        if($qpayNotify->verifySign() && conf('qqpay_api') == 1) {
            //判断签名及结果（即时到帐）
            if($result['trade_state'] == "SUCCESS") {
                //商户订单号
                $out_trade_no = $result['out_trade_no'];
                //QQ钱包订单号
                $transaction_id = $result['transaction_id'];
                //金额,以分为单位
                $total_fee = $result['total_fee'];
                //币种
                $fee_type = $result['fee_type'];

                //------------------------------
                //处理业务开始
                //------------------------------
                $srow = Db::name('pay')->where('trade_no', $out_trade_no)->find();
                if($srow['status'] == 0){
                    $result = Db::name('pay')->where('trade_no', $out_trade_no)->update(['status' => 1]);
                    if($result){
                        Db::name('pay')->where('trade_no', $out_trade_no)->update(['endtime' => datetime(), 'api_trade_no' => $transaction_id]);
                        $this->service->processOrder($srow);
                    }
                }
                //------------------------------
                //处理业务完毕
                //------------------------------
                echo "<xml>
                          <return_code>SUCCESS</return_code>
                      </xml>";
            } else {
                echo "<xml>
                          <return_code>FAIL</return_code>
                      </xml>";
            }
        } else {
            //回调签名错误
            echo "<xml>
                      <return_code>FAIL</return_code>
                      <return_msg>签名失败</return_msg>
                  </xml>";
        }
    }
}