<?php

namespace app\pay\controller;

use app\common\controller\PayBackend;
use app\pay\service\CommonService;
use think\facade\Db;
use app\pay\library\wxpay\NativePay;
use app\pay\library\wxpay\WxPayUnifiedOrder;
use app\pay\library\wxpay\JsApiPay;
use app\pay\library\wxpay\WxPayApi;
use app\pay\library\wxpay\PayNotifyCallBack;
use think\facade\View;

class WxPay extends PayBackend
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new CommonService();
    }

    public function index(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        if(conf('wxpay_api') != 1 && conf('wxpay_api') != 3) return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);
        $ordername = $row['name'];

        $notify = new NativePay();
        $input = new WxPayUnifiedOrder();
        $input->SetBody($ordername);
        $input->SetOut_trade_no($trade_no);
        $input->SetTotal_fee($row['money']*100);
        $input->SetSpbill_create_ip(get_client_ip());
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetNotify_url(SITE_URL.url('/WxPay/notify'));
        $input->SetTrade_type("NATIVE");
        $result = $notify->GetPayUrl($input);
        if($result["result_code"] == 'SUCCESS'){
            $code_url = $result['code_url'];
        }elseif(isset($result["err_code"])){
            return $this->render('public/error', ['msg' => '微信支付下单失败！['.$result["err_code"].'] '.$result["err_code_des"],'time' => 5, 'url' => '/']);
        }else{
            return $this->render('public/error', ['msg' => '微信支付下单失败！['.$result["return_code"].'] '.$result["return_msg"],'time' => 5, 'url' => '/']);
        }
        View::assign([
            'row' => $row,
            'code_url' => $code_url
        ]);
        return $this->render();
    }

    public function payOk(){
        return $this->render();
    }

    public function jsPay(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        $d = isset($get['d'])?$get['d']:null;
        if(conf('wxpay_api') != 1 && conf('wxpay_api') != 3) return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);
        $ordername = $row['name'];

        //①、获取用户openid
        $tools = new JsApiPay();
        $openId = $tools->GetOpenid();
        //②、统一下单
        $input = new WxPayUnifiedOrder();
        $input->SetBody($ordername);
        $input->SetOut_trade_no($trade_no);
        $input->SetTotal_fee($row['money']*100);
        $input->SetTime_start(date("YmdHis"));
        $input->SetTime_expire(date("YmdHis", time() + 600));
        $input->SetNotify_url(SITE_URL.url('/WxPay/notify'));
        $input->SetTrade_type("JSAPI");
        $input->SetProduct_id("01001");
        $input->SetOpenid($openId);
        $order = WxPayApi::unifiedOrder($input);

        if($order["result_code"] == 'SUCCESS'){
            $jsApiParameters = $tools->GetJsApiParameters($order);
        }elseif(isset($result["err_code"])){
            return $this->render('public/error', ['msg' => '微信支付下单失败！['.$result["err_code"].'] '.$result["err_code_des"],'time' => 5, 'url' => '/']);
        }else{
            return $this->render('public/error', ['msg' => '微信支付下单失败！['.$result["return_code"].'] '.$result["return_msg"],'time' => 5, 'url' => '/']);
        }

        if($d == 1){
            $redirect_url = 'data.backurl';
        }else{
            $redirect_url = url('/WxPay/payOk');
        }
        View::assign([
            'row' => $row,
            'redirect_url' => $redirect_url,
            'jsApiParameters' => $jsApiParameters
        ]);
        return $this->render();
    }

    public function wapPay(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        if(conf('wxpay_api') != 1 && conf('wxpay_api') != 3) return $this->render('public/error', ['msg' => '当前支付接口未开启！','time' => 5, 'url' => '/']);
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);
        $ordername = $row['name'];

        if(conf('wxpay_api') == 3){
            $notify = new NativePay();
            $input = new WxPayUnifiedOrder();
            $input->SetBody($ordername);
            $input->SetOut_trade_no($trade_no);
            $input->SetTotal_fee($row['money']*100);
            $input->SetSpbill_create_ip(get_client_ip());
            $input->SetTime_start(date("YmdHis"));
            $input->SetTime_expire(date("YmdHis", time() + 600));
            $input->SetNotify_url(SITE_URL.url('/WxPay/notify'));
            $input->SetTrade_type("MWEB");
            $result = $notify->GetPayUrl($input);
            if($result["result_code"] == 'SUCCESS'){
                if(conf('wxpay_api') == 3){
                    $redirect_url = SITE_URL.url('/WxPay/return').'?trade_no='.$trade_no;
                    $url = $result['mweb_url'].'&redirect_url='.urlencode($redirect_url);
                    return $this->redirectTo($url);
                }else{
                    $code_url = $result['code_url'];
                }
            }elseif(isset($result["err_code"])){
                return $this->render('public/error', ['msg' => '微信支付下单失败！['.$result["err_code"].'] '.$result["err_code_des"],'time' => 5, 'url' => '/']);
            }else{
                return $this->render('public/error', ['msg' => '微信支付下单失败！['.$result["return_code"].'] '.$result["return_msg"],'time' => 5, 'url' => '/']);
            }
        }else{
            $target_url = SITE_URL.url('/WxPay/jsPay').'?trade_no='.$trade_no;
        }
        View::assign([
            'row' => $row,
            'code_url' => $code_url,
            'target_url' => $target_url
        ]);
        return $this->render();
    }

    public function notify(){
        try {
            $notify = new PayNotifyCallBack();
            $notify->Handle(false);
        } catch (\Throwable $e) {
            echo 'FAIL';
        }
    }

    public function return(){
        $get = request()->get();
        $trade_no = isset($get['trade_no'])?$get['trade_no']:null;
        $row = Db::name('pay')->where('trade_no', $trade_no)->find();
        if(!$row) return $this->render('public/error', ['msg' => '该订单号不存在，请返回来源地重新发起请求！','time' => 5, 'url' => '/']);
        return $this->render();
    }
}