-- Generated by deploy/build-legacy-bridge.php.
-- Non-destructive table bridge for a 4.2.9 database copied into the new environment.
-- This file intentionally contains CREATE TABLE IF NOT EXISTS statements only.

CREATE TABLE IF NOT EXISTS `QH_feedback` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户ID',
  `title` varchar(255) NOT NULL COMMENT '反馈标题',
  `content` text NOT NULL COMMENT '反馈内容',
  `type` varchar(20) NOT NULL DEFAULT 'other' COMMENT '反馈类型：bug/feature/other',
  `reply` text COMMENT '历史回复字段，新增回复请写入QH_feedback_reply',
  `status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0待处理 1已受理 2已驳回 3已解决',
  `created_at` datetime NOT NULL COMMENT '提交时间',
  `updated_at` datetime DEFAULT NULL COMMENT '处理时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_status` (`user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `QH_feedback_reply` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `feedback_id` int(11) unsigned NOT NULL COMMENT '反馈ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '回复用户ID，0=管理员',
  `is_admin` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否管理员回复',
  `author` varchar(150) NOT NULL DEFAULT '' COMMENT '回复人名称',
  `content` text NOT NULL COMMENT '回复内容',
  `created_at` datetime NOT NULL COMMENT '回复时间',
  PRIMARY KEY (`id`),
  KEY `idx_feedback_id` (`feedback_id`),
  KEY `idx_feedback_admin` (`feedback_id`, `is_admin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `QH_notification` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '接收用户ID，0=管理员',
  `title` varchar(255) NOT NULL COMMENT '通知标题',
  `content` text COMMENT '通知内容',
  `type` varchar(50) DEFAULT 'feedback' COMMENT '通知类型',
  `link` varchar(255) DEFAULT '' COMMENT '跳转链接',
  `is_read` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0未读 1已读',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_read` (`user_id`, `is_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `QH_point_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户ID',
  `type` varchar(30) NOT NULL COMMENT 'consume/recharge/exchange/refund',
  `amount` int(11) NOT NULL DEFAULT 0 COMMENT '积分变化，正数增加，负数扣除',
  `integral_after` int(11) NOT NULL DEFAULT 0 COMMENT '变动后积分',
  `description` varchar(255) DEFAULT NULL COMMENT '描述',
  `source_type` varchar(50) DEFAULT '' COMMENT '来源类型',
  `source_no` varchar(64) DEFAULT '' COMMENT '来源编号',
  `related_id` int(11) unsigned DEFAULT NULL COMMENT '关联ID',
  `status` varchar(20) NOT NULL DEFAULT 'valid' COMMENT 'valid/invalid',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_source` (`source_type`,`source_no`),
  KEY `idx_user_time` (`user_id`,`created_at`),
  KEY `idx_related` (`related_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QH_wechat_mp_login` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `token` varchar(64) NOT NULL COMMENT '本地登录token',
  `scene` varchar(80) NOT NULL DEFAULT '' COMMENT '微信二维码场景值',
  `type` varchar(20) NOT NULL DEFAULT '' COMMENT 'userLogin/adminLogin/bindUser/bindAdmin',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/scanned/confirmed',
  `openid` varchar(64) NOT NULL DEFAULT '' COMMENT '微信openid',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '绑定用户ID',
  `admin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '绑定管理员ID',
  `expires_at` datetime NOT NULL COMMENT '过期时间',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_token` (`token`),
  KEY `idx_scene` (`scene`),
  KEY `idx_status_expire` (`status`, `expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信公众号扫码登录状态表';

CREATE TABLE IF NOT EXISTS `QH_point_product` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL COMMENT '商品名称',
  `image` varchar(255) DEFAULT '' COMMENT '商品图片',
  `description` text COMMENT '商品描述',
  `type` varchar(30) NOT NULL DEFAULT 'virtual_goods' COMMENT 'auth_code/virtual_goods',
  `stock` int(11) NOT NULL DEFAULT 0 COMMENT '库存',
  `required_points` int(11) NOT NULL DEFAULT 0 COMMENT '兑换所需积分',
  `exchange_limit` int(11) NOT NULL DEFAULT 0 COMMENT '每个用户兑换上限，0不限制',
  `reward_info` text COMMENT '虚拟商品奖品信息',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1上架 0下架',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QH_point_exchange_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户ID',
  `product_id` int(11) unsigned NOT NULL COMMENT '商品ID',
  `product_name` varchar(150) NOT NULL COMMENT '商品名称快照',
  `cost_points` int(11) NOT NULL DEFAULT 0 COMMENT '消耗积分',
  `reward_info` text COMMENT '奖品信息',
  `status` varchar(20) NOT NULL DEFAULT 'success' COMMENT 'success/canceled',
  `created_at` datetime NOT NULL COMMENT '兑换时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_time` (`user_id`,`created_at`),
  KEY `idx_product` (`product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QH_point_product_reward` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `product_id` int(11) unsigned NOT NULL COMMENT '商品ID',
  `reward_content` text NOT NULL COMMENT '奖品内容',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/issued',
  `user_id` int(11) unsigned DEFAULT NULL COMMENT '领取用户ID',
  `record_id` int(11) unsigned DEFAULT NULL COMMENT '兑换记录ID',
  `issued_at` datetime DEFAULT NULL COMMENT '发放时间',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_product_status` (`product_id`,`status`),
  KEY `idx_user` (`user_id`),
  KEY `idx_record` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `QH_balance_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户ID',
  `type` varchar(30) DEFAULT 'recharge' COMMENT '类型: recharge/consume/refund/adjust',
  `amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '变动金额（正=增加，负=减少）',
  `balance` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '变动后余额',
  `description` varchar(255) DEFAULT '' COMMENT '描述',
  `source_type` varchar(50) DEFAULT '' COMMENT '来源类型',
  `source_no` varchar(64) DEFAULT '' COMMENT '来源单号',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='余额变动日志';

CREATE TABLE IF NOT EXISTS `QH_withdraw` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '申请人用户ID',
  `amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '提现金额',
  `phone` varchar(20) DEFAULT '' COMMENT '手机号',
  `real_name` varchar(100) DEFAULT '' COMMENT '真实姓名',
  `pay_method` varchar(20) DEFAULT 'alipay' COMMENT '收款方式:alipay/wechat/bank',
  `qr_image` varchar(500) DEFAULT '' COMMENT '收款码图片',
  `user_remark` varchar(500) DEFAULT '' COMMENT '用户备注',
  `admin_remark` varchar(500) DEFAULT '' COMMENT '管理员处理备注',
  `transfer_image` varchar(500) DEFAULT '' COMMENT '管理员转账凭证',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '状态:pending/approved/rejected/withdrawn',
  `applied_at` datetime DEFAULT NULL COMMENT '申请时间',
  `handled_at` datetime DEFAULT NULL COMMENT '管理员处理时间',
  `withdrawn_at` datetime DEFAULT NULL COMMENT '用户撤回时间',
  `created_at` datetime DEFAULT NULL COMMENT '申请时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提现记录';

CREATE TABLE IF NOT EXISTS `QH_checkin_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户ID',
  `checkin_date` date NOT NULL COMMENT '打卡日期',
  `consecutive_days` int(11) NOT NULL DEFAULT 1 COMMENT '连续打卡天数',
  `points_earned` int(11) NOT NULL DEFAULT 0 COMMENT '获得积分',
  `ip` varchar(45) NOT NULL DEFAULT '' COMMENT '打卡IP',
  `created_at` datetime NOT NULL COMMENT '打卡时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_date` (`user_id`, `checkin_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_checkin_date` (`checkin_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='打卡记录表';

CREATE TABLE IF NOT EXISTS `QH_carousel` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL DEFAULT '' COMMENT '标题',
  `image` varchar(255) NOT NULL DEFAULT '' COMMENT '图片URL',
  `url` varchar(500) NOT NULL DEFAULT '' COMMENT '跳转地址',
  `sort` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint(1) unsigned NOT NULL DEFAULT 1 COMMENT '状态:0=隐藏,1=显示',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  KEY `sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='轮播图管理';

CREATE TABLE IF NOT EXISTS `QH_user_notice` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL DEFAULT '' COMMENT '公告标题',
  `content` text COMMENT '公告内容',
  `sort` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `status` tinyint(1) unsigned NOT NULL DEFAULT 1 COMMENT '状态:0=隐藏,1=显示',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_sort` (`sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户公告';

CREATE TABLE IF NOT EXISTS `QH_discount_code` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '所属用户ID',
  `code` varchar(32) NOT NULL COMMENT '唯一折扣码',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1启用 0停用',
  `created_at` datetime NOT NULL COMMENT '生成时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='折扣码表';

CREATE TABLE IF NOT EXISTS `QH_rebate_record` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` int(11) unsigned NOT NULL COMMENT 'QH_order.id',
  `pay_trade_no` varchar(255) DEFAULT NULL COMMENT 'QH_pay.trade_no',
  `payer_user_id` int(11) unsigned NOT NULL COMMENT '付款用户ID',
  `referrer_user_id` int(11) unsigned NOT NULL COMMENT '返利归属用户ID（折扣码所有者）',
  `discount_code` varchar(32) NOT NULL COMMENT '使用的折扣码',
  `paid_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '支付金额',
  `rebate_base_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '返利计算基数（充值面额）',
  `rebate_rate` decimal(5,2) NOT NULL DEFAULT 0.00 COMMENT '结算时的返利比例(%)',
  `rebate_amount` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT '返利金额',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT 'pending/settled/rejected/canceled',
  `settle_at` datetime DEFAULT NULL COMMENT '预计结算时间',
  `settled_at` datetime DEFAULT NULL COMMENT '实际结算时间',
  `risk_reason` varchar(255) NOT NULL DEFAULT '' COMMENT '内部风控原因',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_pay_trade_no` (`pay_trade_no`),
  KEY `idx_referrer` (`referrer_user_id`),
  KEY `idx_code` (`discount_code`),
  KEY `idx_status_settle_at` (`status`,`settle_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='返利记录表';

CREATE TABLE IF NOT EXISTS `QH_plugin` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '插件ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '发布者用户ID',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT '插件名称',
  `slug` varchar(100) NOT NULL DEFAULT '' COMMENT '插件标识(唯一)',
  `category` varchar(30) DEFAULT '' COMMENT '分类',
  `version` varchar(50) NOT NULL DEFAULT '1.0.0' COMMENT '插件版本',
  `author` varchar(100) NOT NULL DEFAULT '' COMMENT '作者',
  `author_url` varchar(255) DEFAULT '' COMMENT '作者网址',
  `description` text COMMENT '插件简介',
  `content` longtext COMMENT '插件详细介绍(富文本)',
  `icon` varchar(255) DEFAULT '' COMMENT '插件图标URL',
  `images` text COMMENT '插件图片(JSON数组,兼容旧数据)',
  `cover` varchar(255) DEFAULT '' COMMENT '插件封面图URL',
  `origin_type` tinyint(1) unsigned NOT NULL DEFAULT 1 COMMENT '来源:1=原创,2=转载',
  `origin_url` varchar(255) DEFAULT '' COMMENT '转载来源地址',
  `origin_author` varchar(100) DEFAULT '' COMMENT '转载原作者',
  `origin_note` varchar(500) DEFAULT '' COMMENT '转载声明/备注',
  `related_plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '关联插件ID，可选',
  `storage_driver` varchar(20) NOT NULL DEFAULT 'local' COMMENT '存储驱动:local/oss',
  `file_path` varchar(255) NOT NULL DEFAULT '' COMMENT '插件文件路径(私有存储)',
  `package_object_key` varchar(500) DEFAULT '' COMMENT '插件包OSS对象Key',
  `package_file_name` varchar(255) DEFAULT '' COMMENT '插件包原始文件名',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '文件大小(字节)',
  `package_mime_type` varchar(100) DEFAULT '' COMMENT '插件包MIME类型',
  `file_hash` varchar(64) DEFAULT '' COMMENT '文件SHA-256哈希',
  `icon_object_key` varchar(500) DEFAULT '' COMMENT '图标OSS对象Key',
  `cover_object_key` varchar(500) DEFAULT '' COMMENT '封面OSS对象Key',
  `update_description` text COMMENT '最新版本更新说明',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '插件价格(0为免费)',
  `pay_type` varchar(10) DEFAULT 'balance' COMMENT '支付方式:balance=余额,points=积分',
  `download_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '下载次数',
  `rating_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '评分人数',
  `rating_avg` decimal(3,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '平均评分(0-5)',
  `comment_count` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '评论数量',
  `status` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '状态:0=待审核,1=已上架,2=已下架,3=审核拒绝',
  `audit_note` varchar(500) DEFAULT '' COMMENT '审核备注',
  `sort` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '排序(数字越大越靠前)',
  `is_hot` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '是否热门:0=否,1=是',
  `is_recommend` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '是否推荐:0=否,1=是',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `published_at` datetime DEFAULT NULL COMMENT '上架时间',
  `publish_type` tinyint(1) NOT NULL DEFAULT 0 COMMENT '发布类型:0=立即发布,1=定时发布',
  `publish_time` datetime DEFAULT NULL COMMENT '定时发布时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `status` (`status`),
  KEY `price` (`price`),
  KEY `download_count` (`download_count`),
  KEY `rating_avg` (`rating_avg`),
  KEY `sort` (`sort`),
  KEY `related_plugin_id` (`related_plugin_id`),
  KEY `is_hot` (`is_hot`),
  KEY `is_recommend` (`is_recommend`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件表';

CREATE TABLE IF NOT EXISTS `QH_plugin_versions` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '版本记录ID',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `version` varchar(50) NOT NULL DEFAULT '' COMMENT '版本号',
  `storage_driver` varchar(20) NOT NULL DEFAULT 'local' COMMENT '存储驱动:local/oss',
  `package_path` varchar(500) DEFAULT '' COMMENT '本地插件包路径或URL',
  `package_object_key` varchar(500) DEFAULT '' COMMENT '插件包OSS对象Key',
  `package_file_name` varchar(255) DEFAULT '' COMMENT '插件包原始文件名',
  `package_file_size` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '插件包大小',
  `package_mime_type` varchar(100) DEFAULT '' COMMENT '插件包MIME类型',
  `package_hash` varchar(64) DEFAULT '' COMMENT '插件包SHA-256哈希',
  `update_description` text COMMENT '更新说明',
  `created_by` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '创建人用户ID',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_plugin_version` (`plugin_id`,`version`),
  KEY `idx_plugin_id` (`plugin_id`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件版本历史表';

CREATE TABLE IF NOT EXISTS `QH_plugin_resources` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '资源ID',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `version_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件版本ID',
  `resource_type` varchar(50) NOT NULL DEFAULT '' COMMENT '资源类型:icon/cover/package/attachment',
  `storage_driver` varchar(20) NOT NULL DEFAULT 'local' COMMENT '存储驱动:local/oss',
  `url` varchar(500) DEFAULT '' COMMENT '资源访问URL或本地路径',
  `object_key` varchar(500) DEFAULT '' COMMENT 'OSS对象Key',
  `file_name` varchar(255) DEFAULT '' COMMENT '原始文件名',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '文件大小',
  `mime_type` varchar(100) DEFAULT '' COMMENT 'MIME类型',
  `sort_order` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `created_by` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '创建人用户ID',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_plugin_id` (`plugin_id`),
  KEY `idx_version_id` (`version_id`),
  KEY `idx_resource_type` (`resource_type`),
  KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件资源表';

CREATE TABLE IF NOT EXISTS `QH_plugin_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `order_no` varchar(64) NOT NULL DEFAULT '' COMMENT '订单号',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `plugin_name` varchar(255) NOT NULL DEFAULT '' COMMENT '插件名称',
  `plugin_version` varchar(50) NOT NULL DEFAULT '' COMMENT '插件版本',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `app_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '应用ID',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '订单金额',
  `commission_rate` decimal(5,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '平台抽成比例(%)',
  `commission_amount` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '平台抽成金额',
  `developer_income` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '开发者收入',
  `pay_type` varchar(20) DEFAULT '' COMMENT '支付方式:alipay,wxpay,qqpay,balance',
  `pay_trade_no` varchar(100) DEFAULT '' COMMENT '支付平台订单号',
  `status` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '状态:0=待支付,1=已支付,2=已取消,3=已退款',
  `paid_at` datetime DEFAULT NULL COMMENT '支付时间',
  `ip` varchar(50) DEFAULT '' COMMENT '下单IP',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no` (`order_no`),
  KEY `plugin_id` (`plugin_id`),
  KEY `user_id` (`user_id`),
  KEY `app_id` (`app_id`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件订单表';

CREATE TABLE IF NOT EXISTS `QH_plugin_comment` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `app_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '应用ID',
  `content` text NOT NULL COMMENT '评论内容',
  `rating` tinyint(1) unsigned NOT NULL DEFAULT 5 COMMENT '评分:1-5星',
  `status` tinyint(1) unsigned NOT NULL DEFAULT 1 COMMENT '状态:0=待审核,1=已通过,2=已拒绝',
  `reply_content` text COMMENT '开发者回复内容',
  `reply_at` datetime DEFAULT NULL COMMENT '开发者回复时间',
  `ip` varchar(50) DEFAULT '' COMMENT '评论IP',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `user_id` (`user_id`),
  KEY `app_id` (`app_id`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件评论表';

CREATE TABLE IF NOT EXISTS `QH_plugin_rating` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '评分ID',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `app_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '应用ID',
  `rating` tinyint(1) unsigned NOT NULL DEFAULT 5 COMMENT '评分:1-5星',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `plugin_user_app` (`plugin_id`,`user_id`,`app_id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `user_id` (`user_id`),
  KEY `app_id` (`app_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件评分表';

CREATE TABLE IF NOT EXISTS `QH_plugin_download` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '下载记录ID',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `plugin_version` varchar(50) NOT NULL DEFAULT '' COMMENT '插件版本',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `app_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '应用ID',
  `order_id` int(11) unsigned DEFAULT 0 COMMENT '订单ID(付费插件)',
  `ip` varchar(50) DEFAULT '' COMMENT '下载IP',
  `created_at` datetime DEFAULT NULL COMMENT '下载时间',
  PRIMARY KEY (`id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `user_id` (`user_id`),
  KEY `app_id` (`app_id`),
  KEY `order_id` (`order_id`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件下载记录表';

CREATE TABLE IF NOT EXISTS `QH_plugin_download_token` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Token ID',
  `token` varchar(64) NOT NULL DEFAULT '' COMMENT '下载凭证',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `app_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '应用ID',
  `order_id` int(11) unsigned DEFAULT 0 COMMENT '订单ID(付费插件)',
  `ip` varchar(50) DEFAULT '' COMMENT '请求IP',
  `used` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT '是否已使用:0=未使用,1=已使用',
  `used_at` datetime DEFAULT NULL COMMENT '使用时间',
  `expires_at` datetime NOT NULL COMMENT '过期时间',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `plugin_id` (`plugin_id`),
  KEY `user_id` (`user_id`),
  KEY `app_id` (`app_id`),
  KEY `used` (`used`),
  KEY `expires_at` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='临时下载凭证表';

CREATE TABLE IF NOT EXISTS `QH_plugin_purchase` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '购买记录ID',
  `plugin_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '插件ID',
  `user_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '用户ID',
  `app_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '应用ID',
  `order_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT '订单ID',
  `price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '购买价格',
  `created_at` datetime DEFAULT NULL COMMENT '购买时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `plugin_user_app` (`plugin_id`,`user_id`,`app_id`),
  KEY `plugin_id` (`plugin_id`),
  KEY `user_id` (`user_id`),
  KEY `app_id` (`app_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='插件购买记录表';

CREATE TABLE IF NOT EXISTS `QH_loginlog` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户ID',
  `username` varchar(100) NOT NULL DEFAULT '' COMMENT '登录名',
  `power` varchar(20) NOT NULL DEFAULT '' COMMENT '权限类型:admin/user',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1=成功 0=失败',
  `ip` varchar(64) NOT NULL DEFAULT '' COMMENT '登录IP',
  `create_time` datetime DEFAULT NULL COMMENT '登录时间',
  PRIMARY KEY (`id`),
  KEY `idx_uid_power_status` (`uid`,`power`,`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志表';
