<?php
namespace app\user\controller;

use app\common\controller\UserBackend;

/**
 * 空控制器
 * @author 陌上花开
 * @since 2020/7/4
 * Class Error
 * @package app\user\controller
 */
class Error extends UserBackend
{
    /**
     * 初始化
     * @author 陌上花开
     * @since 2020/7/5
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 错误页面
     * @return mixed
     * @since 2020/7/4
     * @author 陌上花开
     */
    public function index()
    {
        return $this->render("public/404");
    }
}