<?php
declare (strict_types = 1);

namespace app\user\controller;

use app\user\service\CheckinService;
use app\user\service\IndexService;
use app\user\service\MenuService;
use app\common\controller\UserBackend;
use think\facade\View;
use think\facade\Db;
use think\facade\Log;
/**
 * 用户行为-控制器
 * @author 陌上花开
 * @since 2022/1/20
 * Class Index
 * @package app\user\controller
 */
class Index extends UserBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new IndexService();
    }
    /**
     * 后台主入口
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since: 2022/6/30
     * @author 陌上花开
     */
    public function index() {
        // 取消模板布局
        //$this->app->view->layout(false);
        try{
            $meunService = new MenuService();
            $menuList = $meunService->getList();
            $switchAccounts = Db::name('user_social_identity')->alias('current_link')
                ->join('social_identity current_identity', 'current_identity.id = current_link.identity_id')
                ->join('user_social_identity target_link', 'target_link.identity_id = current_link.identity_id')
                ->join('user target_user', 'target_user.id = target_link.user_id AND target_user.appid = target_link.app_id')
                ->join('app target_app', 'target_app.id = target_link.app_id')
                ->where('current_link.user_id', intval($this->userId))
                ->where('current_link.app_id', intval($this->userInfo['appid']))
                ->where('current_identity.provider', 'qq')
                ->where('target_user.status', 1)
                ->where('target_app.status', 2)
                ->field('target_user.id,target_user.username,target_user.appid,target_app.name AS appname')
                ->order('target_user.appid', 'asc')
                ->select()
                ->toArray();
            // Shared layout is role-driven; business menu source remains unchanged.
            View::assign([
                'layoutRole' => 'user',
                'layoutAvatar' => $this->userInfo['img'],
                'layoutUsername' => $this->userInfo['username'],
                'layoutAdminQqOauthBound' => false,
                'layoutSwitchAccounts' => $switchAccounts,
                'layoutCurrentUserId' => intval($this->userId),
                'menuList' => $menuList,
            ]);
        }catch (\Throwable $e){
            Log::error(sprintf(
                'User menu load failed [user_id=%d, exception=%s]: %s',
                intval($this->userId),
                get_class($e),
                $e->getMessage()
            ));
            return $this->render('/public/error', ['msg' => t('common.server_error').'[errorCode:GetMenuListError]']);
        }
        return View::fetch(APP_PATH . DS . 'common' . DS . 'view' . DS . 'layout' . DS . 'main_layout.html');
    }

    /**
     * 欢迎页
     * @author 陌上花开
     * @since: 2022/6/30
     */
    public function main() {
        $authCount = Db::name('auth')->where(['userid' => $this->userId])->count('id');
        $authYesterday = Db::name('auth')->where(['userid' => $this->userId])->whereTime('addtime', 'yesterday')->count('id');
        $authToday = Db::name('auth')->where(['userid' => $this->userId])->whereTime('addtime', 'today')->count('id');
        $authIncrease = $authToday - $authYesterday;

        $cdkeyCount = Db::name('cdkey')->where(['userid' => $this->userId])->count('id');

        $userCount = Db::name('user')->where(['userid' => $this->userId])->count('id');
        $userYesterday = Db::name('user')->where(['userid' => $this->userId])->whereTime('addtime', 'yesterday')->count('id');
        $userToday = Db::name('user')->where(['userid' => $this->userId])->whereTime('addtime', 'today')->count('id');
        $userIncrease = $userToday - $userYesterday;
        $logList = Db::name('log')->order('id' ,'desc')->field('title,create_time')->where(['username' => $this->userId, 'is_admin' => 0])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $balanceRanking = Db::name('user')->order('balance' ,'desc')->field('username,balance')->where(['appid' => $this->userInfo['appid']])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $integralRanking = Db::name('user')->order('integral' ,'desc')->field('username,integral')->where(['appid' => $this->userInfo['appid']])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $powerTierMap = $this->getPowerTierMap();
        $agentUsers = $this->getRandomAgentUsers(intval($this->userInfo['appid']), $powerTierMap);
        $currentPowerTier = $powerTierMap[intval($this->userInfo['power'])] ?? 'agent-tier-standard';
        $showPowerBadge = intval($this->myPowerInfo['default_power'] ?? 0) !== 1;

        // Hot & latest plugins
        $currentAppId = intval($this->userInfo['appid']);
        $hotPlugins = Db::name('plugin')->where('app_id', $currentAppId)->where('status', 1)->where('is_hot', 1)->order('sort', 'desc')->order('id', 'desc')->limit(4)->field('id,name,icon,author,price,description')->select()->toArray();
        $latestPlugins = Db::name('plugin')->where('app_id', $currentAppId)->where('status', 1)->order('id', 'desc')->limit(4)->field('id,name,icon,author,price,description')->select()->toArray();

        // My recent purchases
        $myPurchases = [];
        if (!empty($this->userId)) {
            $myPurchases = Db::name('plugin_purchase')
                ->alias('p')
                ->join('plugin pl', 'p.plugin_id = pl.id')
                ->where('p.user_id', intval($this->userId))
                ->where('p.app_id', $currentAppId)
                ->where('pl.app_id', $currentAppId)
                ->order('p.id', 'desc')
                ->limit(4)
                ->field('pl.id, pl.name, pl.icon, pl.price, p.created_at')
                ->select()
                ->toArray();
        }
        $myPluginCount = Db::name('plugin')->where('user_id', intval($this->userId))->count('id');
        $myOnlinePluginCount = Db::name('plugin')->where('user_id', intval($this->userId))->where('status', 1)->count('id');
        $myPlugins = Db::name('plugin')
            ->where('user_id', intval($this->userId))
            ->order('id', 'desc')
            ->limit(4)
            ->field('id, name, icon, status, description')
            ->select()
            ->toArray();
        $weekTrend = [];
        $weekAuthMax = 1;
        $weekUserMax = 1;
        for ($i = 6; $i >= 0; $i--) {
            $start = date('Y-m-d 00:00:00', strtotime('-' . $i . ' days'));
            $end = date('Y-m-d 23:59:59', strtotime('-' . $i . ' days'));
            $authNum = Db::name('auth')->where(['userid' => $this->userId])->whereTime('addtime', 'between', [$start, $end])->count('id');
            $userNum = Db::name('user')->where(['userid' => $this->userId])->whereTime('addtime', 'between', [$start, $end])->count('id');
            $weekAuthMax = max($weekAuthMax, $authNum);
            $weekUserMax = max($weekUserMax, $userNum);
            $weekTrend[] = [
                'day' => date('m-d', strtotime($start)),
                'auth' => $authNum,
                'user' => $userNum,
            ];
        }
        foreach ($weekTrend as &$trendItem) {
            $trendItem['auth_rate'] = max(6, round($trendItem['auth'] / $weekAuthMax * 100));
            $trendItem['user_rate'] = max(6, round($trendItem['user'] / $weekUserMax * 100));
        }
        unset($trendItem);

        // Emotional value data
        $hour = (int)date('H');
        $greeting = $hour < 6
            ? t('user_home.greeting_late_night')
            : ($hour < 9
                ? t('user_home.greeting_morning')
                : ($hour < 12
                    ? t('user_home.greeting_forenoon')
                    : ($hour < 14
                        ? t('user_home.greeting_noon')
                        : ($hour < 18 ? t('user_home.greeting_afternoon') : t('user_home.greeting_evening')))));
        $greetingEmoji = $hour < 6 ? '🌙' : ($hour < 9 ? '☀️' : ($hour < 12 ? '🌤' : ($hour < 14 ? '🌞' : ($hour < 18 ? '🌈' : '🌆'))));
        $memberDays = max(1, (int)((time() - strtotime($this->userInfo['addtime'])) / 86400));

        try {
            $checkinService = new CheckinService(intval($this->userId), $this->userInfo['username']);
            $checkinStatus = $checkinService->getStatus();
        } catch (\Exception $e) {
            $checkinStatus = ['checked_today' => false, 'consecutive_days' => 0, 'today_points' => 0, 'checkin_time' => null, 'error' => true];
        }

        View::assign([
            'checkin_status' => $checkinStatus,
            'checkin_enabled' => empty($checkinStatus['error']) && conf('checkin_enabled') !== '0',
            'checkin_base_points' => (int)(conf('checkin_base_points') ?: 5),
            'notice' => conf('notice_user'),
            'notice_list' => Db::name('user_notice')->where('status', 1)->order('sort', 'asc')->order('id', 'desc')->select()->toArray(),
            'app_notice' => $this->myAppInfo['app_notice'],
            'app_name' => $this->myAppInfo['name'],
            'app_id' => intval($this->myAppInfo['id']),
            'log_list' => $logList,
            'greeting' => $greeting,
            'greeting_emoji' => $greetingEmoji,
            'member_days' => $memberDays,
            'current_power_tier' => $currentPowerTier,
            'show_power_badge' => $showPowerBadge,
            'balance_ranking' => $balanceRanking,
            'integral_ranking' => $integralRanking,
            'agent_users' => $agentUsers,
            'auth_count' => $authCount,
            'auth_increase' => $authIncrease,
            'today_auths' => $authToday,
            'cdkey_count' => $cdkeyCount,
            'cdkey_unused' => Db::name('cdkey')->where(['userid' => $this->userId, 'status' => 0])->count('id'),
            'user_count' => $userCount,
            'user_increase' => $userIncrease,
            'hot_plugins' => $hotPlugins,
            'latest_plugins' => $latestPlugins,
            'my_purchases' => $myPurchases,
            'my_plugin_count' => $myPluginCount,
            'my_online_plugin_count' => $myOnlinePluginCount,
            'my_plugins' => $myPlugins,
            'carousel_list' => Db::name('carousel')->where('status', 1)->order('sort', 'asc')->order('id', 'desc')->select()->toArray(),
            'week_trend' => $weekTrend,
            'week_auth_max' => $weekAuthMax,
            'week_user_max' => $weekUserMax,
        ]);
        return $this->render();
    }

    /**
     * Build the shared badge palette from the current application's complete
     * active power hierarchy so the same power always gets the same colour.
     *
     * @return array<int, string>
     */
    private function getPowerTierMap(): array
    {
        $powerIds = Db::name('power_price')
            ->where([
                'tid' => intval($this->myAppInfo['power_template']),
                'status' => 1,
                'default_power' => 0,
            ])
            ->order('money', 'asc')
            ->order('id', 'asc')
            ->column('id');

        $tierMap = [];
        foreach (array_values($powerIds) as $index => $powerId) {
            $tierMap[intval($powerId)] = 'agent-tier-' . (($index % 10) + 1);
        }

        return $tierMap;
    }

    /**
     * Randomly showcase up to ten active agents from the current application.
     *
     * @param int $appId
     * @param array<int, string> $tierMap
     * @return array
     */
    private function getRandomAgentUsers(int $appId, array $tierMap = []): array
    {
        if (empty($tierMap)) {
            $tierMap = $this->getPowerTierMap();
        }

        try {
            $agents = Db::name('user')->alias('u')
                ->join('power_price p', 'p.id = u.power')
                ->leftJoin('user_social_identity usi', 'usi.user_id = u.id')
                ->leftJoin('social_identity si', "si.id = usi.identity_id AND si.provider = 'qq'")
                ->where([
                    'u.appid' => $appId,
                    'u.status' => 1,
                    'p.status' => 1,
                    'p.default_power' => 0,
                ])
                ->whereRaw('u.qq REGEXP ?', ['^[1-9][0-9]{4,11}$'])
                ->field('u.id,u.username,u.qq,u.power,p.name AS power_name,si.nickname AS social_nickname,si.avatar AS social_avatar')
                ->orderRaw('RAND()')
                ->limit(10)
                ->select()
                ->toArray();
        } catch (\Throwable $e) {
            // Backward compatibility for installations without OAuth identity tables.
            $agents = Db::name('user')->alias('u')
                ->join('power_price p', 'p.id = u.power')
                ->where([
                    'u.appid' => $appId,
                    'u.status' => 1,
                    'p.status' => 1,
                    'p.default_power' => 0,
                ])
                ->whereRaw('u.qq REGEXP ?', ['^[1-9][0-9]{4,11}$'])
                ->field('u.id,u.username,u.qq,u.power,p.name AS power_name')
                ->orderRaw('RAND()')
                ->limit(10)
                ->select()
                ->toArray();
        }

        foreach ($agents as &$agent) {
            $nickname = trim((string)($agent['social_nickname'] ?? ''));
            $agent['display_name'] = $nickname !== '' ? $nickname : (string)$agent['username'];

            $avatar = trim((string)($agent['social_avatar'] ?? ''));
            if ($avatar !== '' && !preg_match('#^(?:https?:)?//#i', $avatar)) {
                $avatar = '';
            }
            if ($avatar === '' && preg_match('/^[1-9][0-9]{4,11}$/', (string)($agent['qq'] ?? ''))) {
                $avatar = 'https://q1.qlogo.cn/g?b=qq&nk=' . rawurlencode((string)$agent['qq']) . '&s=100';
            }
            $agent['avatar'] = $avatar !== '' ? $avatar : '/Assets/img/logo.png';

            $powerId = intval($agent['power']);
            $agent['tier_class'] = $tierMap[$powerId] ?? ('agent-tier-' . (($powerId % 10) + 1));
        }
        unset($agent);

        return $agents;
    }

    public function editPassword(){
        if(IS_POST){
            $post = $this->request->post();
            $username = !empty($post['username'])?$post['username']:null;
            $oldPassword = !empty($post['oldPassword'])?$post['oldPassword']:null;
            $newPassword = !empty($post['newPassword'])?$post['newPassword']:null;
            if(empty($username)){
                return message(t('login.please_enter_username'), false);
            }
            if(empty($oldPassword)){
                return message(t('user.old_password_empty'), false);
            }
            $needsRehash = false;
            if(!qh_password_verify($oldPassword, $this->userInfo['password'], $needsRehash)){
                return message(t('user.old_password_wrong'), false);
            }
            if($username == $this->userInfo['username']){
                if(empty($newPassword)){
                    return message(t('user.new_password_empty'), false);
                }
                if($oldPassword == $newPassword){
                    return message(t('user.new_password_same'), false);
                }
                if(strlen($newPassword) < 6){
                    return message(t('user.new_password_short'), false);
                }
                try{
                    Db::name('user')
                        ->where('id', $this->userId)
                        ->data(['password' => qh_password_make($newPassword)])
                        ->update();
                    return message(t('user.password_change_success'), true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }else{
                $row = Db::name('user')->where('username', $username)->find();
                if($row){
                    return message(t('user.username_exists'), false);
                }
                if(!empty($newPassword)){
                    if($oldPassword == $newPassword){
                        return message(t('user.new_password_same'), false);
                    }
                    if(strlen($newPassword) < 6){
                        return message(t('user.new_password_short'), false);
                    }
                    $password = qh_password_make($newPassword);
                }else{
                    $password = $this->userInfo['password'];
                }
                try{
                    Db::name('user')
                        ->where('id', $this->userId)
                        ->data(['username' => $username, 'password' => $password])
                        ->update();
                    return message(t('user.username_change_success'), true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }
        }
        return $this->render();
    }
}
