<?php
declare (strict_types = 1);

namespace app\user\controller;

use app\user\service\IndexService;
use app\user\service\MenuService;
use app\common\controller\UserBackend;
use think\facade\View;
use think\facade\Db;
/**
 * 用户行为-控制器
 * @author 陌上花开
 * @since 2022/1/20
 * Class Index
 * @package app\user\controller
 */
class Index extends UserBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new IndexService();
    }
    /**
     * 后台主入口
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @since: 2022/6/30
     * @author 陌上花开
     */
    public function index() {
        // 取消模板布局
        //$this->app->view->layout(false);
        try{
            $meunService = new MenuService();
            $menuList = $meunService->getList();
            // Shared layout is role-driven; business menu source remains unchanged.
            View::assign([
                'layoutRole' => 'user',
                'layoutAvatar' => $this->userInfo['img'],
                'layoutUsername' => $this->userInfo['username'],
                'menuList' => $menuList,
            ]);
        }catch (\Exception $e){
            return $this->render('/public/error', ['msg' => '获取菜单失败！[errorCode:GetMenuListError]']);
        }
        return View::fetch(APP_PATH . DS . 'common' . DS . 'view' . DS . 'layout' . DS . 'main_layout.html');
    }

    /**
     * 欢迎页
     * @author 陌上花开
     * @since: 2022/6/30
     */
    public function main() {
        $authCount = Db::name('auth')->where(['appid' => $this->userInfo['appid']])->count('id');
        $authYesterday = Db::name('auth')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'yesterday')->count('id');
        $authToday = Db::name('auth')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'today')->count('id');
        $authIncrease = $authToday - $authYesterday;

        $paymentCount = Db::name('payment')->where(['appid' => $this->userInfo['appid']])->count('id');
        $paymentYesterday = Db::name('payment')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'yesterday')->count('id');
        $paymentToday = Db::name('payment')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'today')->count('id');
        $paymentIncrease = $paymentToday - $paymentYesterday;

        $pirateCount = Db::name('pirate')->where(['appid' => $this->userInfo['appid']])->count('id');
        $pirateYesterday = Db::name('pirate')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'yesterday')->count('id');
        $pirateToday = Db::name('pirate')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'today')->count('id');
        $pirateIncrease = $pirateToday - $pirateYesterday;

        $userCount = Db::name('user')->where(['appid' => $this->userInfo['appid']])->count('id');
        $userYesterday = Db::name('user')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'yesterday')->count('id');
        $userToday = Db::name('user')->where(['appid' => $this->userInfo['appid']])->whereTime('addtime', 'today')->count('id');
        $userIncrease = $userToday - $userYesterday;
        $logList = Db::name('log')->order('id' ,'desc')->field('title,create_time')->where(['username' => $this->userId, 'is_admin' => 0])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $balanceRanking = Db::name('user')->order('balance' ,'desc')->field('username,balance')->where(['appid' => $this->userInfo['appid']])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);
        $integralRanking = Db::name('user')->order('integral' ,'desc')->field('username,integral')->where(['appid' => $this->userInfo['appid']])->paginate([
            'list_rows'=> 10,
            'page' => 1,
        ]);

        View::assign([
            'notice' => conf('notice_user'),
            'app_notice' => $this->myAppInfo['app_notice'],
            'app_name' => $this->myAppInfo['name'],
            'log_list' => $logList,
            'balance_ranking' => $balanceRanking,
            'integral_ranking' => $integralRanking,
            'auth_count' => $authCount,
            'auth_increase' => $authIncrease,
            'payment_count' => $paymentCount,
            'payment_increase' => $paymentIncrease,
            'pirate_count' => $pirateCount,
            'pirate_increase' => $pirateIncrease,
            'user_count' => $userCount,
            'user_increase' => $userIncrease
        ]);
        return $this->render();
    }

    public function editPassword(){
        if(IS_POST){
            $post = $this->request->post();
            $username = !empty($post['username'])?$post['username']:null;
            $oldPassword = !empty($post['oldPassword'])?$post['oldPassword']:null;
            $newPassword = !empty($post['newPassword'])?$post['newPassword']:null;
            if(empty($username)){
                return message('请填写用户名！', false);
            }
            if(empty($oldPassword)){
                return message('请填写原密码！', false);
            }
            if($oldPassword != $this->userInfo['password']){
                return message('原密码不正确！', false);
            }
            if($username == $this->userInfo['username']){
                if(empty($newPassword)){
                    return message('请填写新密码！', false);
                }
                if($oldPassword == $newPassword){
                    return message('新密码不能与原密码相同！', false);
                }
                if(strlen($newPassword) < 6){
                    return message('新密码不能小于6位！', false);
                }
                try{
                    Db::name('user')
                        ->where('id', $this->userId)
                        ->data(['password' => $newPassword])
                        ->update();
                    return message('修改密码成功！', true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }else{
                $row = Db::name('user')->where(['username' => $username, 'appid' => $this->userInfo['appid']])->find();
                if($row){
                    return message('系统已存在该用户名，请更换后重试！', false);
                }
                if(!empty($newPassword)){
                    if($oldPassword == $newPassword){
                        return message('新密码不能与原密码相同！', false);
                    }
                    if(strlen($newPassword) < 6){
                        return message('新密码不能小于6位！', false);
                    }
                    $password = $newPassword;
                }else{
                    $password = $this->userInfo['password'];
                }
                try{
                    Db::name('user')
                        ->where('id', $this->userId)
                        ->data(['username' => $username, 'password' => $password])
                        ->update();
                    return message('修改用户名成功！', true);
                }catch (\Exception $e){
                    return message($e->getMessage(), false);
                }
            }
        }
        return $this->render();
    }
}
