<?php

namespace app\user\controller;

use app\common\controller\UserBackend;
use app\user\service\MyInfoService;
use think\facade\View;

class MyInfo extends UserBackend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MyInfoService();
    }

    public function index(){
        return $this->render();
    }

    public function recharge(){
        if(IS_POST){
            return $this->service->recharge();
        }
        View::assign('pay_notice', $this->myAppInfo['pay_notice']);
        return $this->render();
    }

    public function checkBinding(){
        if(IS_POST){
            $type = input('post.type');
            switch ($type){
                case 'email':
                    if(!empty($this->userInfo['email'])){
                        return message('success', true);
                    } else {
                        return message('error', false);
                    }
                case 'phone':
                    if(!empty($this->userInfo['phone'])){
                        return message('success', true);
                    } else {
                        return message('error', false);
                    }
                case 'qq':
                    if(!empty($this->userInfo['access_token'])){
                        return message('success', true);
                    } else {
                        return message('error', false);
                    }
                default:
                    return message('error', false);
            }

        }
    }

    public function changeBindingMail(){
        if(IS_POST){
            return $this->service->changeBindingMail();
        }
    }

    public function editUserInfo(){
        if(IS_POST){
            return $this->service->editUserInfo();
        }
    }

    public function updatePower(){
        if(IS_POST){
            if($this->myPowerInfo['parentid'] == 0){
                return message('您当前已经是最高权限！', false);
            }
            return $this->service->updatePower();
        }
    }
}