<?php

namespace app\user\controller;

use app\common\controller\UserBackend;
use app\user\service\MyInfoService;
use think\facade\View;

class MyInfo extends UserBackend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MyInfoService();
    }

    public function index(){
        View::assign('pay_notice', $this->myAppInfo['pay_notice'] ?? '');
        return $this->render('my_info/index');
    }

    public function recharge(){
        if(IS_POST){
            $result = $this->service->recharge();
            if (is_array($result)) {
                return json($result);
            }
            return $result;
        }
        return redirect((string)url('/MyInfo/index'));
    }

    public function checkBinding(){
        if(IS_POST){
            $type = input('post.type');
            switch ($type){
                case 'email':
                    if(!empty($this->userInfo['email'])){
                        return json(message('success', true));
                    } else {
                        return json(message('error', false));
                    }
                case 'qq':
                    if(!empty($this->userInfo['qq'])){
                        return json(message('success', true));
                    } else {
                        return json(message('error', false));
                    }
                default:
                    return json(message('error', false));
            }

        }
    }

    public function changeBindingMail(){
        if(IS_POST){
            return $this->service->changeBindingMail();
        }
    }

    public function editUserInfo(){
        if(IS_POST){
            return $this->service->editUserInfo();
        }
    }

    public function updatePower(){
        if(IS_POST){
            if($this->myPowerInfo['parentid'] == 0){
                return json(message(t('user.highest_power'), false));
            }
            $result = $this->service->updatePower();
            if (is_array($result)) {
                return json($result);
            }
            return $result;
        }
    }

    /**
     * 获取可升级的权限列表(个人中心卡片 UI 用)
     */
    public function getUserUpdatePowerList(){
        if(IS_POST){
            try{
                $powerPriceModel = new \app\admin\model\PowerPriceModel();
                $result = $powerPriceModel->getUserUpdatePowerList($this->userInfo['power']);
                return json(message(t('common.list_success'), true, ['data' => $result]));
            } catch (\Exception $e) {
                return json(message(t('power.get_list_failed').' [errorCode:GetUserUpdatePowerListError]', false));
            }
        }
    }
}
