<?php

namespace app\user\controller;

use app\common\controller\UserBackend;
use app\user\service\MyListService;
use think\Exception;
use think\facade\Db;
use think\facade\View;

class MyList extends UserBackend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MyListService();
    }

    public function editBinding(){
        if(IS_POST){
            $bindingType = input('post.bindingType');
            try{
                return json($this->service->editBinding($bindingType));
            }catch (\Throwable $e){
                return json(message(t('replace.auth_failed').$e->getMessage(), false));
            }
        }
    }

    public function unbind()
    {
        if (IS_POST) {
            $id = input('post.id');
            $type = input('post.type');
            try{
                $this->service->unbind($id,$type);
                return json(message(t('user.unbind_success'), true));
            }catch (\Throwable $e){
                return json(message($e->getMessage(), false));
            }
        }
    }

    public function batchUnbind()
    {
        if (IS_POST) {
            try{
                $ids = array_values(array_unique(array_filter(
                    array_map('intval', explode(',', (string)input('post.id'))),
                    static fn ($id) => $id > 0
                )));
                $type = input('post.type');
                if (empty($ids)) {
                    return json(message(t('validation.missing_id'), false));
                }
                if (count($ids) > 100) {
                    return json(message('auth.batch_unbind_limit', false));
                }
                $num = Db::transaction(function () use ($ids, $type) {
                    $done = 0;
                    foreach ($ids as $id) {
                        if ($this->service->unbind($id, $type) !== true) {
                            throw new \RuntimeException(t('user.delete_failed'));
                        }
                        $done++;
                    }
                    return $done;
                });
                return json(message(t('user.unbind_count', ['total' => count($ids), 'count' => $num]), true));
            }catch (\Throwable $e){
                return json(message($e->getMessage(), false));
            }
        }
    }

    public function auth(){
        try{
            if (IS_POST) {
                $result = $this->service->auth();
                return json(message(t('common.list_success'), true, ['data' => $result]));
            }
        }catch (\Throwable $e){
            return json(message($e->getMessage(), false, ['data' => []]));
        }
        try{
            return redirect((string)url('/Auth/list', ['tab' => 'bound']));
        }catch (\Exception $e){
            return $this->render('public/error', ['msg' => $e->getMessage()]);
        }
    }

}
