<?php

namespace app\user\controller;

use app\common\controller\UserBackend;
use app\user\service\MyListService;
use think\Exception;
use think\facade\View;

class MyList extends UserBackend
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new MyListService();
    }

    public function editBinding(){
        if(IS_POST){
            $bindingType = input('post.bindingType');
            try{
                return $this->service->editBinding($bindingType);
            }catch (\Exception $e){
                return message(t('replace.auth_failed').$e->getMessage(), false);
            }
        }
    }

    public function unbind()
    {
        if (IS_POST) {
            $id = input('post.id');
            $type = input('post.type');
            try{
                $this->service->unbind($id,$type);
                return message(t('user.unbind_success'), true);
            }catch (\Exception $e){
                return message($e->getMessage(), false);
            }
        }
    }

    public function batchUnbind()
    {
        if (IS_POST) {
            try{
                $ids = explode(',', input('post.id'));
                $type = input('post.type');
                //批量删除
                $num = 0;
                foreach ($ids as $key => $val) {
                    $res = $this->service->unbind($val,$type);
                    if ($res !== false) {
                        $num++;
                    }
                }
                return message(t('user.unbind_count', ['total' => count($ids), 'count' => $num]));
            }catch (\Exception $e){
                return message($e->getMessage(), false);
            }
        }
    }

    public function auth(){
        try{
            if (IS_POST) {
                $result = $this->service->auth();
                return message(t('common.list_success'), true, ['data' => $result]);
            }
        }catch (\Exception $e){
            return message($e->getMessage(), false, ['data' => []]);
        }
        try{
            View::assign('replace_notice', $this->myAppInfo['replace_notice']);
            return $this->render();
        }catch (\Exception $e){
            return $this->render('public/error', ['msg' => $e->getMessage()]);
        }
    }

}
