<?php

namespace app\user\controller;

use app\common\controller\UserBackend;
use app\user\service\OrderService;
class Order extends UserBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->service = new OrderService();
    }
}