<?php

namespace app\api\controller;

use app\common\controller\ApiBackend;
use think\Exception;
use app\common\extend\CheckInfo;
use think\facade\Session;
use think\facade\Cookie;
use think\facade\Db;
use app\common\service\ApplicationInstallerService;
class Qrlogin extends ApiBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->appModel = new \app\admin\model\AppModel();
    }

    public function getqrpic(){
        if(IS_POST){
            $url = 'https://ssl.ptlogin2.qq.com/ptqrshow?appid=716027609&e=2&l=M&s=3&d=72&v=4&t=0.' . time() . '&daid=383&pt_3rd_aid=101996138';
            $login_sig = bin2hex(random_bytes(24));
            $arr = $this->get_curl($login_sig, $url, 0, 0, 0, 1, 0, 0, 1);
            preg_match('/qrsig=(.*?);/', $arr['header'], $match);
            if ($qrsig = $match[1]){
                return message(t('common.success') ,true ,['qrsig' => $qrsig, 'data' => base64_encode($arr['body'])]);
            }else{
                return message(t('auth.qrcode_failed') ,false);
            }
        }
    }

    public function qqLogin()
    {
        if(IS_POST){
            $post = $this->request->post();
            $qrsig = !empty($post['qrsig']) ? $post['qrsig'] : null;
            $type = !empty($post['type']) ? $post['type'] : null;
            if(empty($qrsig)){
                return message(t('auth.missing_qrsig') ,false ,['code' => 6]);
            }
            if (empty($type)){
                return message(t('validation.missing_type') ,false ,['code' => 6]);
            }

            switch ($type){
                case 'userLogin':
                    $loginSwitch = conf('login_switch');
                    if (!is_array($loginSwitch)) {
                        $loginSwitch = array_filter(explode(',', (string)$loginSwitch));
                    }
                    if(!in_array('qrcode', $loginSwitch)) return message(t('auth.site_scan_disabled') ,false ,['code' => 6]);
                    break;
                case 'adminLogin':
                    $loginSwitch = conf('login_switch');
                    if (!is_array($loginSwitch)) {
                        $loginSwitch = array_filter(explode(',', (string)$loginSwitch));
                    }
                    if(!in_array('qrcode', $loginSwitch)) return message(t('auth.site_scan_disabled') ,false ,['code' => 6]);
                    break;
                case 'bindQQ':
                case 'adminBindQQ':
                case 'oauthMigrate':
                case 'oauthClaim':
                    break;
                case 'binding':
                    try{
                        parent::userLogin();
                    }catch (\Exception $e){
                        return message(sf_public_exception_message($e, t('qq.login_check_failed')) ,false ,['code' => 6]);
                    }
                    if($this->myAppInfo['binding_auth_switch'] != 1) return message(t('auth.bind_auth_disabled') ,false ,['code' => 6]);
                    break;
                case 'download':
                    if (sf_download_mode() !== 'qrcode') {
                        return message(t('download.qq_disabled'), false, ['code' => 6]);
                    }
                    $appid = !empty($post['appid'])?intval($post['appid']):null;
                    $auth_info = !empty($post['auth_info'])?$post['auth_info']:null;
                    if(empty($appid)){
                        return message(t('auth.select_app') ,false);
                    }
                    if(empty($auth_info)){
                        return message(t('auth.enter_content') ,false);
                    }

                    $row = Db::name('auth')
                        ->where([
                            'appid' => $appid,
                            'auth_info' => $auth_info
                        ])
                        ->field('id,qq')
                        ->find();
                    if(empty($row)){
                        return message(t('auth.not_exist') ,false);
                    }
                    break;
                default:
                    return message(t('common_ui.type_error') ,false ,['code' => 6]);
            }

            $url = 'https://ssl.ptlogin2.qq.com/ptqrlogin?u1=https%3A%2F%2Fgraph.qq.com%2Foauth2.0%2Flogin_jump&ptqrtoken=' . $this->getqrtoken($qrsig) . '&ptredirect=1&h=1&t=1&g=1&from_ui=1&ptlang=2052&action=0-0-' . time() . '&js_ver=22011714&js_type=1&login_sig=&pt_uistyle=40&aid=716027609&daid=383&pt_3rd_aid=101996138&has_onekey=1&';
            $ret = $this->login_get_curl($qrsig, $url, 0, $url, 0, 1);
            if (preg_match("/ptuiCB\('(.*?)'\)/", $ret, $arr)) {
                $r = explode("','", str_replace("', '", "','", $arr[1]));
                switch ($r[0]){
                    case 0:
                        preg_match('/uin=(\d+)&/', $ret, $uin);
                        $uin = $this->getuin($uin[1]);
                        $get_token = bin2hex(random_bytes(32));
                        session('get_token', $get_token);
                        session('get_qq', $uin);
                        Session::save();
                        return message(t('common.success') ,true ,['code' => 0, 'nick' => urlencode($r[5]), 'qq' => $uin]);
                    case 65:
                        return message(t('auth.qrcode_invalid') ,false ,['code' => 1]);
                    case 66:
                        return message(t('auth.qrcode_valid') ,true ,['code' => 2]);
                    case 67:
                        return message(t('auth.qrcode_verifying') ,true ,['code' => 3]);
                    default:
                        return message(t('qq.login_status_abnormal') ,false ,['code' => 6]);
                }
            } else {
                return message(t('qq.service_response_error') ,false ,['code' => 6]);
            }
        }
    }

    public function userLogin(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        $post = $this->request->post();
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        $username = !empty($post['username']) ? $post['username'] : null;
        $appid = !empty($post['appid']) ? intval($post['appid']) : null;
        if(empty($get_token)){
            return message(t('auth.token_expired') ,false);
        }
        if(empty($get_qq)){
            return message(t('auth.token_expired') ,false);
        }
        if(!empty($username) && !empty($appid)){
            // 多账号选择必须仍然受本次扫码得到的 QQ 约束，不能只凭用户名和应用 ID 登录。
            $row = Db::name('user')->where([
                'username' => $username,
                'appid' => $appid,
                'qq' => $get_qq,
                'status' => 1,
            ])->find();
            if(empty($row))return message(t('user.not_exist') ,false);
            Session::regenerate(true);
            cookie('userId', $row['id']);
            cookie('userSign', data_auth_sign($row['appid'].$row['username'].$row['password'].sf_password_hash()));
            Session::delete('get_token');
            Session::delete('get_qq');
            Session::save();
            $content = [
                'Title' => '登录后台',
                '结果' => '登陆成功[使用QQ扫码登录]',
                'Result' => 'success'
            ];
            event('UserLogin', $content);
            return message(t('login.success'), true, null);
        }else{
            $row = Db::name('user')->where(['qq' => $get_qq, 'status' => 1])->select();
            $count = $row->count();
            $data = [];
            switch ($count){
                case 0:
                    return message(t('user.not_exist'), false);
                case 1:
                    $user = $row->first();
                    if (empty($user['appid']) || empty($user['username'])) {
                        return message(t('user.account_abnormal'), false);
                    }
                    Session::regenerate(true);
                    cookie('userId', $user['id']);
                    cookie('userSign', data_auth_sign($user['appid'].$user['username'].$user['password'].sf_password_hash()));
                    Session::delete('get_token');
                    Session::delete('get_qq');
                    Session::save();
                    $content = [
                        'Title' => '登录后台',
                        'Result' => 'success'
                    ];
                    event('UserLogin', $content);
                    return message(t('login.success'), true, null);
                default:
                    foreach ($row as $res){
                        if(!isset($res['appid']) || $res['appid'] === '' || $res['appid'] === null){
                            continue;
                        }
                        if(!isset($res['username']) || $res['username'] === '' || $res['username'] === null){
                            continue;
                        }
                        $appInfo = $this->appModel->getInfo($res['appid']);
                        if($appInfo){
                            $appName = $appInfo['name'];
                        }else{
                            $appName = t('common.load_failed');
                        }

                        $data[] = ['username' => $res['username'], 'qq' => $res['qq'], 'appname' => $appName, 'appid' => $res['appid']];
                    }
                    return message(t('login.select_account'), true, $data);
            }
        }
    }

    public function bindQQ(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        if(empty($get_token) || empty($get_qq)){
            return message(t('auth.token_expired') ,false);
        }
        try{
            parent::userLogin();
        }catch (\Exception $e){
            return message(sf_public_exception_message($e, t('qq.login_check_failed')) ,false);
        }
        $userId = cookie('userId');
        if(empty($userId)){
            return message(t('common.need_login') ,false);
        }
        try{
            Db::transaction(function () use ($userId, $get_qq) {
                $exists = Db::name('user')
                    ->where('qq', $get_qq)
                    ->where('id', '<>', $userId)
                    ->lock(true)
                    ->find();
                if ($exists) {
                    throw new \RuntimeException(t('login.qq_already_bound'));
                }
                Db::name('user')->where('id', $userId)->data(['qq' => $get_qq])->update();
            });
        }catch (\Exception $e){
            return message(sf_public_exception_message($e, t('profile.qq_bind_failed')) ,false);
        }
        Session::delete('get_token');
        Session::delete('get_qq');
        Session::save();
        return message(t('profile.qq_bind_success') ,true);
    }

    /**
     * 管理员QQ扫码登录
     */
    public function adminLogin(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        if(empty($get_token) || empty($get_qq)){
            return message(t('auth.token_expired') ,false);
        }
        $admin = Db::name('admin')->where(['qq' => $get_qq, 'status' => 1])->find();
        if(empty($admin)){
            return message(t('qq.admin_not_bound') ,false);
        }
        Session::regenerate(true);
        session('adminId', $admin['id'], 86400);
        session('adminSign', data_auth_sign($admin['username'].$admin['password'].sf_password_hash()), 86400);
        Session::delete('get_token');
        Session::delete('get_qq');
        Session::save();
        return message(t('login.success') ,true, ['url' => '/admin.php/Index/index.html']);
    }

    /**
     * 管理员QQ扫码绑定
     */
    public function adminBindQQ(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        if(empty($get_token) || empty($get_qq)){
            return message(t('auth.token_expired') ,false);
        }
        $adminId = session('adminId');
        if(empty($adminId)){
            return message(t('common.need_login') ,false);
        }
        try{
            Db::transaction(function () use ($adminId, $get_qq) {
                $exists = Db::name('admin')
                    ->where('qq', $get_qq)
                    ->where('id', '<>', $adminId)
                    ->lock(true)
                    ->find();
                if ($exists) {
                    throw new \RuntimeException(t('qq.admin_already_bound'));
                }
                Db::name('admin')->where('id', $adminId)->data(['qq' => $get_qq])->update();
            });
        }catch (\Exception $e){
            return message(sf_public_exception_message($e, t('profile.qq_bind_failed')) ,false);
        }
        Session::delete('get_token');
        Session::delete('get_qq');
        Session::save();
        return message(t('profile.qq_bind_success') ,true);
    }

    /**
     * 管理员解除QQ绑定
     */
    public function adminUnbindQQ(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        $adminId = session('adminId');
        if(empty($adminId)){
            return message(t('common.need_login') ,false);
        }
        try{
            Db::name('admin')->where('id', $adminId)->data(['qq' => null])->update();
        }catch (\Exception $e){
            return message(t('profile.qq_unbind_failed') ,false);
        }
        return message(t('profile.qq_unbind_success') ,true);
    }

    public function binding(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        $post = $this->request->post();
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        $bindingType = !empty($post['bindingType']) ? $post['bindingType'] : null;
        $list = $post['list'] ?? null;
        if(empty($get_token)){
            return message(t('auth.token_expired') ,false);
        }
        if(empty($get_qq)){
            return message(t('auth.token_expired') ,false);
        }
        try{
            parent::userLogin();
        }catch (\Exception $e){
            return message(sf_public_exception_message($e, t('qq.login_check_failed')) ,false ,['code' => 6]);
        }
        if($get_qq != $this->userInfo['qq']){
            return message(t('user.qq_bind_auth_mismatch') ,false);
        }
        switch($bindingType){
            case 'auth':
                if(!empty($list)){
                    if (!is_array($list)) {
                        return message(t('common_ui.type_error'), false);
                    }
                    $ids = array_values(array_unique(array_filter(array_map('intval', $list), static function ($id) {
                        return $id > 0;
                    })));
                    if (empty($ids)) {
                        return message(t('auth.select_bind_auth'), false);
                    }
                    if (count($ids) > 100) {
                        return message(t('auth.batch_bind_limit', ['limit' => 100]), false);
                    }
                    try {
                        Db::transaction(function () use ($ids, $get_qq) {
                            foreach ($ids as $id) {
                                $row = Db::name('auth')
                                    ->where(['id' => $id, 'appid' => $this->userInfo['appid']])
                                    ->field('id,auth_info,bindingid,qq')
                                    ->lock(true)
                                    ->find();
                                if (empty($row)) {
                                    throw new \RuntimeException(t('auth.not_exist') . ' [ID:' . $id . ']');
                                }
                                $label = ' [ID:' . $id . ', auth_info:' . (string)$row['auth_info'] . '] ';
                                if ((int)$row['bindingid'] !== 0) {
                                    throw new \RuntimeException(t('auth.not_exist') . $label . t('auth.already_exist'));
                                }
                                if ((string)$row['qq'] !== (string)$get_qq) {
                                    throw new \RuntimeException(t('auth.not_exist') . $label . t('auth.qq_mismatch'));
                                }
                                $updated = Db::name('auth')
                                    ->where(['id' => $id, 'appid' => $this->userInfo['appid'], 'bindingid' => 0])
                                    ->data(['bindingid' => $this->userId])
                                    ->update();
                                if ($updated !== 1) {
                                    throw new \RuntimeException(t('auth.bind_state_changed'));
                                }
                            }
                        });
                    } catch (\Exception $e) {
                        return message(sf_public_exception_message($e, t('auth.bind_retry')), false);
                    }
                    Session::delete('get_token');
                    Session::delete('get_qq');
                    Session::save();
                    return message(t('auth.bind_success') ,true);
                }else{
                    $row = Db::name('auth')->where(['qq' => $get_qq, 'bindingid' => 0, 'appid' => $this->userInfo['appid']])->field('id,auth_info')->select();
                    if($row->isEmpty()) return message(t('auth.no_auth_to_bind') ,false);
                    $data = [];
                    foreach ($row as $res){
                        $data[] = ['id' => $res['id'], 'auth_info' => $res['auth_info']];
                    }
                    return message(t('auth.select_bind_auth') ,true, $data);
                }
            default:
                return message(t('common_ui.type_error') ,false);
        }
    }

    public function download(){
        if (!IS_POST) {
            return message(t('common.illegal_request'), false);
        }
        if (sf_download_mode() !== 'qrcode') {
            return message(t('download.qq_disabled'), false);
        }
        $post = $this->request->post();
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        $appid = !empty($post['appid'])?intval($post['appid']):null;
        $auth_info = !empty($post['auth_info'])?$post['auth_info']:null;
        if(empty($get_token)){
            return message(t('auth.token_expired') ,false);
        }
        if(empty($get_qq)){
            return message(t('auth.token_expired') ,false);
        }

        if(empty($appid)){
            return message(t('auth.select_app') ,false);
        }

        if(empty($auth_info)){
            return message(t('auth.enter_content') ,false);
        }
        $row = Db::name('auth')
            ->where([
                'appid' => $appid,
                'auth_info' => $auth_info
            ])
            ->field('id,qq')
            ->find();
        if(empty($row)){
            return message(t('auth.not_exist') ,false);
        }
        Session::delete('get_token');
        Session::delete('get_qq');
        Session::save();
        if($row['qq'] != $get_qq){
            return message(t('auth.qq_mismatch') ,false);
        }

        $ticket = ApplicationInstallerService::issueDownloadTicket(
            $appid,
            (int)$row['id'],
            (string)get_client_ip()
        );
        if (empty($ticket['ok'])) {
            return message((string)$ticket['msg'], false);
        }
        return message(t('app.download_link_success') ,true, [
            'url' => SITE_URL.'/api.php/Download/download/?sign='.$ticket['ticket'],
        ]);
    }
    private function getGTK($skey){
        $len = strlen($skey);
        $hash = 5381;
        for ($i = 0; $i < $len; $i++) {
            $hash += ($hash << 5) + ord($skey[$i]);
        }
        return $hash & 0x7fffffff;//计算g_tk
    }

    private function getuin($uin){
        for ($i = 0; $i < strlen($uin); $i++) {
            if ($uin[$i] == 'o' || $uin[$i] == '0') continue;
            else break;
        }
        return substr($uin, $i);
    }

    private function getqrtoken($qrsig){
        $len = strlen($qrsig);
        $hash = 0;
        for ($i = 0; $i < $len; $i++) {
            $hash += (($hash << 5) & 2147483647) + ord($qrsig[$i]) & 2147483647;
            $hash &= 2147483647;
        }
        return $hash & 2147483647;
    }

    private function get_curl($login_sig, $url, $post = 0, $referer = 0, $cookie = 0, $header = 0, $ua = 0, $nobaody = 0, $split = 0){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
        curl_setopt($ch, CURLOPT_TIMEOUT, 15);
        $httpheader[] = 'Accept: image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8';
        $httpheader[] = 'Accept-Encoding: gzip, deflate, br';
        $httpheader[] = 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6';
        $httpheader[] = 'Cache-Control: no-cache';
        $httpheader[] = 'Connection: keep-alive';
        $httpheader[] = 'Cookie: pt_login_sig=' . $login_sig;
        $httpheader[] = 'Host: ssl.ptlogin2.qq.com';
        $httpheader[] = 'Pragma: no-cache';
        $httpheader[] = 'Referer: https://xui.ptlogin2.qq.com/';
        $httpheader[] = 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Microsoft Edge";v="98"';
        $httpheader[] = 'sec-ch-ua-mobile: ?1';
        $httpheader[] = 'sec-ch-ua-platform: "Android"';
        $httpheader[] = 'Sec-Fetch-Dest: image';
        $httpheader[] = 'Sec-Fetch-Mode: no-cors';
        $httpheader[] = 'Sec-Fetch-Site: same-site';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $httpheader);
        if ($post) {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        }
        if ($header) {
            curl_setopt($ch, CURLOPT_HEADER, TRUE);
        }
        if ($cookie) {
            curl_setopt($ch, CURLOPT_COOKIE, $cookie);
        }
        if ($referer) {
            curl_setopt($ch, CURLOPT_REFERER, $referer);
        }
        if ($ua) {
            curl_setopt($ch, CURLOPT_USERAGENT, $ua);
        } else {
            curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36');
        }
        if ($nobaody) {
            curl_setopt($ch, CURLOPT_NOBODY, 1);

        }
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $ret = curl_exec($ch);
        if ($split) {
            $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $header = substr($ret, 0, $headerSize);
            $body = substr($ret, $headerSize);
            $ret = array();
            $ret['header'] = $header;
            $ret['body'] = $body;
        }
        curl_close($ch);
        return $ret;
    }

    private function login_get_curl($qrsig, $url, $post = 0, $referer = 0, $cookie = 0, $header = 0, $ua = 0, $nobaody = 0, $split = 0){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
        curl_setopt($ch, CURLOPT_TIMEOUT, 15);

        $httpheader[] = 'Accept:*/*';
        $httpheader[] = 'Accept-Encoding:gzip,deflate,sdch';
        $httpheader[] = 'Accept-Language:zh-CN,zh;q=0.8';
        $httpheader[] = 'Connection:close';
        $httpheader[] = 'Cookie: qrsig=' . $qrsig;

        curl_setopt($ch, CURLOPT_HTTPHEADER, $httpheader);
        if ($post) {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        }
        if ($header) {
            curl_setopt($ch, CURLOPT_HEADER, TRUE);
        }
        if ($cookie) {
            curl_setopt($ch, CURLOPT_COOKIE, $cookie);
        }
        if ($referer) {
            curl_setopt($ch, CURLOPT_REFERER, $referer);
        }
        if ($ua) {
            curl_setopt($ch, CURLOPT_USERAGENT, $ua);
        } else {
            curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36');
        }
        if ($nobaody) {
            curl_setopt($ch, CURLOPT_NOBODY, 1);

        }
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $ret = curl_exec($ch);
        if ($split) {
            $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $header = substr($ret, 0, $headerSize);
            $body = substr($ret, $headerSize);
            $ret = array();
            $ret['header'] = $header;
            $ret['body'] = $body;
        }
        curl_close($ch);
        return $ret;
    }
}
