<?php

namespace app\api\controller;

use app\common\controller\ApiBackend;
use think\Exception;
use app\common\extend\CheckInfo;
use think\facade\Cache;
use think\facade\Session;
use think\facade\Db;
class Qrlogin extends ApiBackend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->appModel = new \app\admin\model\AppModel();
    }

    public function getqrpic(){
        if(IS_POST){
            $url = 'https://ssl.ptlogin2.qq.com/ptqrshow?appid=716027609&e=2&l=M&s=3&d=72&v=4&t=0.' . time() . '&daid=383&pt_3rd_aid=101996138';
            $login_sig = md5(uniqid(rand(), TRUE));
            $arr = $this->get_curl($login_sig, $url, 0, 0, 0, 1, 0, 0, 1);
            preg_match('/qrsig=(.*?);/', $arr['header'], $match);
            if ($qrsig = $match[1]){
                return message('success！' ,true ,['qrsig' => $qrsig, 'data' => base64_encode($arr['body'])]);
            }else{
                return message('二维码获取失败！' ,false);
            }
        }
    }

    public function qqLogin()
    {
        if(IS_POST){
            $post = $this->request->post();
            $qrsig = !empty($post['qrsig']) ? $post['qrsig'] : null;
            $type = !empty($post['type']) ? $post['type'] : null;
            if(empty($qrsig)){
                return message('缺少QRSIG参数！' ,false ,['code' => 6]);
            }
            if (empty($type)){
                return message('缺少TYPE参数！' ,false ,['code' => 6]);
            }

            switch ($type){
                case 'userLogin':
                    if(!in_array('qrcode',conf('login_switch'))) return message('站点未开启扫码登录！' ,false ,['code' => 6]);
                    break;
                case 'binding':
                    try{
                        parent::userLogin();
                    }catch (\Exception $e){
                        return message($e->getMessage() ,false ,['code' => 6]);
                    }
                    if($this->myAppInfo['binding_auth_switch'] != 1) return message('当前应用未开启绑定授权功能！' ,false ,['code' => 6]);
                    break;
                case 'download':
                    $appid = !empty($post['appid'])?intval($post['appid']):null;
                    $auth_info = !empty($post['auth_info'])?$post['auth_info']:null;
                    if(empty($appid)){
                        return message('请选择所属应用！' ,false);
                    }
                    if(empty($auth_info)){
                        return message('请填写授权内容！' ,false);
                    }

                    $row = Db::name('auth')
                        ->where([
                            'appid' => $appid,
                            'auth_info' => $auth_info
                        ])
                        ->field('qq')
                        ->find();
                    if(empty($row)){
                        return message('不存在此授权！' ,false);
                    }
                    break;
                default:
                    return message('不存在此类型！' ,false ,['code' => 6]);
            }

            $url = 'https://ssl.ptlogin2.qq.com/ptqrlogin?u1=https%3A%2F%2Fgraph.qq.com%2Foauth2.0%2Flogin_jump&ptqrtoken=' . $this->getqrtoken($qrsig) . '&ptredirect=1&h=1&t=1&g=1&from_ui=1&ptlang=2052&action=0-0-' . time() . '&js_ver=22011714&js_type=1&login_sig=&pt_uistyle=40&aid=716027609&daid=383&pt_3rd_aid=101996138&has_onekey=1&';
            $ret = $this->login_get_curl($qrsig, $url, 0, $url, 0, 1);
            if (preg_match("/ptuiCB\('(.*?)'\)/", $ret, $arr)) {
                $r = explode("','", str_replace("', '", "','", $arr[1]));
                switch ($r[0]){
                    case 0:
                        preg_match('/uin=(\d+)&/', $ret, $uin);
                        $uin = $uin[1];
                        $get_token = base64_encode(md5($uin . md5($uin . '*$$*') . '23132' . md5(date("Y-m-d-H"))));
                        session('get_token', $get_token);
                        session('get_qq', $uin);
                        return message('success！' ,true ,['code' => 0, 'nick' => urlencode($r[5]), 'qq' => $uin]);
                    case 65:
                        return message('二维码已失效。' ,false ,['code' => 1]);
                    case 66:
                        return message('二维码未失效。' ,true ,['code' => 2]);
                    case 67:
                        return message('正在验证二维码。' ,true ,['code' => 3]);
                    default:
                        return message($r[4] ,false ,['code' => 6]);
                }
            } else {
                return message($ret ,false ,['code' => 6]);
            }
        }
    }

    public function userLogin(){
        $post = $this->request->post();
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        $username = !empty($post['username']) ? $post['username'] : null;
        $appid = !empty($post['appid']) ? intval($post['appid']) : null;
        if(empty($get_token)){
            return message('TOKEN失效，请重新扫码！' ,false);
        }
        if(empty($get_qq)){
            return message('TOKEN失效，请重新扫码！' ,false);
        }
        if(!empty($username) && !empty($appid)){
            $row = Db::name('user')->where(['username' => $username, 'appid' => $appid, 'status' => 1])->find();
            if(empty($row))return message('不存在此用户！' ,false);
            Session::set('userId', $row['id']);
            Session::set('userSign',data_auth_sign($row['username'].'SF'.$row['password']));
            Session::delete('get_token');
            Session::delete('get_qq');
            Session::save();
            $content = [
                'Title' => '登录后台',
                '结果' => '登陆成功[使用QQ扫码登录]',
                'Result' => 'success'
            ];
            event('UserLogin', $content);
            return message('登陆成功！' ,true);
        }else{
            $row = Db::name('user')->where(['qq' => $get_qq, 'status' => 1])->select();
            $count = $row->count();
            $data = [];
            switch ($count){
                case 0:
                    return message('不存在此用户！' ,false);
                case 1:
                    return message('登陆成功！' ,true);
                default:
                    foreach ($row as $res){
                        if(empty($res['appid'])){
                            continue;
                        }
                        if(empty($res['username'])){
                            continue;
                        }
                        $appInfo = $this->appModel->getInfo($res['appid']);
                        if($appInfo){
                            $appName = $appInfo['name'];
                        }else{
                            $appName = '获取失败';
                        }

                        $data[] = ['username' => $res['username'], 'qq' => $res['qq'], 'appname' => $appName, 'appid' => $res['appid']];
                    }
                    return message('请选择要登录的账号！' ,true, $data);
            }
        }
    }

    public function binding(){
        $post = $this->request->post();
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        $bindingType = !empty($post['bindingType']) ? $post['bindingType'] : null;
        $list = !empty($post['list']) ? $post['list'] : null;
        if(empty($get_token)){
            return message('TOKEN失效，请重新扫码！' ,false);
        }
        if(empty($get_qq)){
            return message('TOKEN失效，请重新扫码！' ,false);
        }
        try{
            parent::userLogin();
        }catch (\Exception $e){
            return message($e->getMessage() ,false ,['code' => 6]);
        }
        if($get_qq != $this->userInfo['qq']){
            return message('请使用当前账户绑定的QQ扫码！' ,false);
        }
        switch($bindingType){
            case 'auth':
                if(!empty($list)){
                    if(empty($list))return message('请选择要绑定的授权！' ,false);
                    foreach ($list as $res){
                        $row = Db::name('auth')->where(['id' => $res, 'appid' => $this->userInfo['appid']])->field('id,bindingid,qq')->find();
                        if(empty($row)) return message('不存在此ID:'.$res.'授权！' ,false);
                        if($row['bindingid'] != 0) return message('ID:'.$res.'，授权:'.$res['auth_info'].'已被绑定，请勿重复绑定！' ,false);
                        if($row['qq'] != $get_qq) return message('ID:'.$res.'，授权:'.$res['auth_info'].'不是您的授权，无法绑定！' ,false);
                        try{
                            Db::name('auth')->where(['id' => $res, 'appid' => $this->userInfo['appid']])->data(['bindingid' => $this->userId])->update();
                        }catch (\Exception $e){
                            return message($e->getMessage() ,false);
                        }
                    }
                    Session::delete('get_token');
                    Session::delete('get_qq');
                    Session::save();
                    return message('绑定成功！' ,true);
                }else{
                    $row = Db::name('auth')->where(['qq' => $get_qq, 'bindingid' => 0, 'appid' => $this->userInfo['appid']])->field('id,auth_info')->select();
                    if($row->isEmpty()) return message('该QQ已无要绑定的授权！' ,false);
                    $data = [];
                    foreach ($row as $res){
                        $data[] = ['id' => $res['id'], 'auth_info' => $res['auth_info']];
                    }
                    return message('请选择要绑定的授权！' ,true, $data);
                }
            case 'payment':
                if(!empty($list)){
                    if(empty($list))return message('请选择要绑定的认证！' ,false);
                    foreach ($list as $res){
                        $row = Db::name('payment')->where(['id' => $res, 'appid' => $this->userInfo['appid']])->field('id,bindingid,qq')->find();
                        if(empty($row)) return message('不存在此ID:'.$res.'认证！' ,false);
                        if($row['bindingid'] != 0) return message('ID:'.$res.'，认证:'.$res['url'].'已被绑定，请勿重复绑定！' ,false);
                        if($row['qq'] != $get_qq) return message('ID:'.$res.'，认证:'.$res['url'].'不是您的认证，无法绑定！' ,false);
                        try{
                            Db::name('payment')->where(['id' => $res, 'appid' => $this->userInfo['appid']])->data(['bindingid' => $this->userId])->update();
                        }catch (\Exception $e){
                            return message($e->getMessage() ,false);
                        }
                    }
                    Session::delete('get_token');
                    Session::delete('get_qq');
                    Session::save();
                    return message('绑定成功！' ,true);
                }else{
                    $row = Db::name('payment')->where(['qq' => $get_qq, 'bindingid' => 0, 'appid' => $this->userInfo['appid']])->field('id,url')->select();
                    if($row->isEmpty()) return message('该QQ已无要绑定的授权！' ,false);
                    $data = [];
                    foreach ($row as $res){
                        $data[] = ['id' => $res['id'], 'auth_info' => $res['url']];
                    }
                    return message('请选择要绑定的授权！' ,true, $data);
                }
            default:
                return message('类型错误！' ,false);
        }
    }

    public function download(){
        $post = $this->request->post();
        $get_token = !empty(session('get_token'))?session('get_token'):null;
        $get_qq = !empty(session('get_qq'))?session('get_qq'):null;
        $appid = !empty($post['appid'])?intval($post['appid']):null;
        $auth_info = !empty($post['auth_info'])?$post['auth_info']:null;
        if(empty($get_token)){
            return message('TOKEN失效，请重新扫码！' ,false);
        }
        if(empty($get_qq)){
            return message('TOKEN失效，请重新扫码！' ,false);
        }

        if(empty($appid)){
            return message('请选择所属应用！' ,false);
        }

        if(empty($auth_info)){
            return message('请填写授权内容！' ,false);
        }
        $row = Db::name('auth')
            ->where([
                'appid' => $appid,
                'auth_info' => $auth_info
            ])
            ->field('qq')
            ->find();
        if(empty($row)){
            return message('不存在此授权！' ,false);
        }
        Session::delete('get_token');
        Session::delete('get_qq');
        Session::save();
        if($row['qq'] != $get_qq){
            return message('该授权QQ与所填QQ不匹配！' ,false);
        }

        $res = Db::name('version')
            ->where([
                ['appid', '=', $appid],
                ['status', '=', 1],
                ['type', '=', 0]
            ])
            ->find();
        if(empty($res)){
            return message('此应用无安装包' ,false);
        }
        $value = serialize([
            'versionInfo' => $res,
            'authInfo' => $row
        ]);
        $key = md5(uniqid());
        Cache::set($key, $value, 43200);
        return message('获取下载链接成功' ,true, ['url' => 'http://'.DOMAIN.'/api.php/Download/download/?sign='.$key]);
    }
    private function getGTK($skey){
        $len = strlen($skey);
        $hash = 5381;
        for ($i = 0; $i < $len; $i++) {
            $hash += ($hash << 5) + ord($skey[$i]);
        }
        return $hash & 0x7fffffff;//计算g_tk
    }

    private function getuin($uin){
        for ($i = 0; $i < strlen($uin); $i++) {
            if ($uin[$i] == 'o' || $uin[$i] == '0') continue;
            else break;
        }
        return substr($uin, $i);
    }

    private function getqrtoken($qrsig){
        $len = strlen($qrsig);
        $hash = 0;
        for ($i = 0; $i < $len; $i++) {
            $hash += (($hash << 5) & 2147483647) + ord($qrsig[$i]) & 2147483647;
            $hash &= 2147483647;
        }
        return $hash & 2147483647;
    }

    private function get_curl($login_sig, $url, $post = 0, $referer = 0, $cookie = 0, $header = 0, $ua = 0, $nobaody = 0, $split = 0){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        $httpheader[] = 'Accept: image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8';
        $httpheader[] = 'Accept-Encoding: gzip, deflate, br';
        $httpheader[] = 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6';
        $httpheader[] = 'Cache-Control: no-cache';
        $httpheader[] = 'Connection: keep-alive';
        $httpheader[] = 'Cookie: pt_login_sig=' . $login_sig;
        $httpheader[] = 'Host: ssl.ptlogin2.qq.com';
        $httpheader[] = 'Pragma: no-cache';
        $httpheader[] = 'Referer: https://xui.ptlogin2.qq.com/';
        $httpheader[] = 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Microsoft Edge";v="98"';
        $httpheader[] = 'sec-ch-ua-mobile: ?1';
        $httpheader[] = 'sec-ch-ua-platform: "Android"';
        $httpheader[] = 'Sec-Fetch-Dest: image';
        $httpheader[] = 'Sec-Fetch-Mode: no-cors';
        $httpheader[] = 'Sec-Fetch-Site: same-site';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $httpheader);
        if ($post) {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        }
        if ($header) {
            curl_setopt($ch, CURLOPT_HEADER, TRUE);
        }
        if ($cookie) {
            curl_setopt($ch, CURLOPT_COOKIE, $cookie);
        }
        if ($referer) {
            curl_setopt($ch, CURLOPT_REFERER, $referer);
        }
        if ($ua) {
            curl_setopt($ch, CURLOPT_USERAGENT, $ua);
        } else {
            curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36');
        }
        if ($nobaody) {
            curl_setopt($ch, CURLOPT_NOBODY, 1);

        }
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $ret = curl_exec($ch);
        if ($split) {
            $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $header = substr($ret, 0, $headerSize);
            $body = substr($ret, $headerSize);
            $ret = array();
            $ret['header'] = $header;
            $ret['body'] = $body;
        }
        curl_close($ch);
        return $ret;
    }

    private function login_get_curl($qrsig, $url, $post = 0, $referer = 0, $cookie = 0, $header = 0, $ua = 0, $nobaody = 0, $split = 0){
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

        $httpheader[] = 'Accept:*/*';
        $httpheader[] = 'Accept-Encoding:gzip,deflate,sdch';
        $httpheader[] = 'Accept-Language:zh-CN,zh;q=0.8';
        $httpheader[] = 'Connection:close';
        $httpheader[] = 'Cookie: qrsig=' . $qrsig;

        curl_setopt($ch, CURLOPT_HTTPHEADER, $httpheader);
        if ($post) {
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        }
        if ($header) {
            curl_setopt($ch, CURLOPT_HEADER, TRUE);
        }
        if ($cookie) {
            curl_setopt($ch, CURLOPT_COOKIE, $cookie);
        }
        if ($referer) {
            curl_setopt($ch, CURLOPT_REFERER, $referer);
        }
        if ($ua) {
            curl_setopt($ch, CURLOPT_USERAGENT, $ua);
        } else {
            curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36');
        }
        if ($nobaody) {
            curl_setopt($ch, CURLOPT_NOBODY, 1);

        }
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        $ret = curl_exec($ch);
        if ($split) {
            $headerSize = curl_getinfo($ch, CURLINFO_HEADER_SIZE);
            $header = substr($ret, 0, $headerSize);
            $body = substr($ret, $headerSize);
            $ret = array();
            $ret['header'] = $header;
            $ret['body'] = $body;
        }
        curl_close($ch);
        return $ret;
    }
}