<?php
namespace addons\addCode\controller;

use app\common\controller\Backend;
use app\common\service\SafeZipService;
use PhpZip\Exception\ZipException;
use PhpZip\ZipFile;
use think\facade\Db;
class AddCode extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if(IS_POST){
            $post = $this->request->post();
            $appid = !empty($post['appid'])?intval($post['appid']):null;
            $filename = !empty($post['name'])?$post['name']:null;
            if(empty($appid)){
                return message(t('auth.select_app'), false);
            }
            if(empty($filename)){
                return message(t('upload.select_file'), false);
            }
            $filename = trim((string)$filename);
            if ($filename !== basename($filename) || !preg_match('/^[^\x00\/\\\\]{1,180}\.zip$/iu', $filename)) {
                return message(t('upload.filename_invalid'), false);
            }
            try{
                $appInfo = Db::name('app')
                    ->where('id', $appid)
                    ->field('public_key,api_key,check_auth_method')
                    ->find();
                $authcode_str = file_get_contents(ADDONS_PATH . DS . 'addCode' . DS . 'common' . DS . 'AuthCode.QH');
                $authcode_str = str_replace('QH_DOMAIN', DOMAIN, $authcode_str);
                $authcode_str = str_replace('QH_APPID', $appid, $authcode_str);
                $authcode_str = str_replace('QH_API_KEY', $appInfo['api_key'], $authcode_str);
                $authcode_str = str_replace('QH_METHOD', $appInfo['check_auth_method'], $authcode_str);
                $authcode_str = str_replace('QH_HTTP', is_https()?'true':'false', $authcode_str);
                $authinfo_str = file_get_contents(ADDONS_PATH . DS . 'addCode' . DS . 'common' . DS . 'AuthInfo.QH');
                $authinfo_str = str_replace('QH_PUBLIC_KEY', $appInfo['public_key'], $authinfo_str);
            }catch (\Exception $e){
                return message($e->getMessage() ,false);
            }

            $zip = new ZipFile();
            try {
                $filePath = RUNTIME_PATH . DS . 'temp' . DS . 'upload' . DS;
                if(!is_dir($filePath)){
                    @mkdir($filePath, 0755, true);
                }
                $fname = $filePath . $filename;
                $zipProblem = SafeZipService::validate($fname, [], 20000, 1073741824);
                if ($zipProblem !== null) {
                    @unlink($fname);
                    return message($zipProblem, false);
                }
                // 打开插件压缩包
                try {
                    $zip->openFile($fname);
                } catch (ZipException $e) {
                    $zip->close();
                    @unlink($fname);
                    return message(t('archive.open_failed') ,false);
                }

                $tempDir = $filePath . 'temp';
                //创建临时目录
                rmdirs($tempDir, false);
                @mkdir($tempDir, 0755, true);

                // 解压到临时目录
                try {
                    $zip->extractTo($tempDir);
                } catch (ZipException $e) {
                    $zip->close();
                    rmdirs($tempDir, false);
                    @unlink($fname);
                    return message(t('archive.extract_failed') ,false);
                }
                $pathInfo = getDirContent($tempDir);
                $caihong = 0;
                $jiuyan = 0;
                $thinkphp5 = 0;
                $thinkphp6 = 0;
                foreach ($pathInfo as $res){
                    switch ($res){
                        case 'assets':
                        case 'includes':
                        case 'admin':
                        case 'install':
                        case 'template':
                        case 'user':
                        case 'index.php':
                        case 'ajax.php':
                        case 'corn.php':
                            $caihong++;
                            $jiuyan++;
                            break;
                        case 'config.php':
                        case 'mini.php':
                        case 'api.php':
                        case 'record.php':
                        case 'other':
                            $caihong++;
                            break;
                        case 'copyapi.php':
                        case 'jump.php':
                        case 'kt_ok.php':
                        case 'ktfz.php':
                        case 'ktfz_ajax.php':
                        case 'login.php':
                        case 'sub.php':
                        case 'api':
                        case 'webht':
                        case 'order':
                        case 'database.php':
                            $jiuyan++;
                            break;
                        case 'think':
                        case 'runtime':
                        case 'vendor':
                        case 'extend':
                        case 'public':
                            $thinkphp6++;
                            $thinkphp5++;
                            break;
                        case 'view':
                        case 'route':
                        case 'config':
                        case 'app':
                            $thinkphp6++;
                            break;
                        case 'build.php':
                        case 'thinkphp':
                        case 'application':
                            $thinkphp5++;
                            break;
                    }
                }
                $maxValue = max($caihong, $jiuyan, $thinkphp5, $thinkphp6);
                switch ($maxValue){
                    case $caihong:
                        $file = $tempDir . DS . 'includes' . DS . 'common.php';
                        if(!is_file($file)){
                            return message(t('source_package.rainbow_includes_missing') ,false);
                        }
                        $this->delLastLine($file);
                        $handle = fopen($file, 'a');
                        fwrite($handle, $authcode_str);
                        fclose($handle);
                        file_put_contents($tempDir . DS . 'includes' . DS . 'AuthInfo.php', $authinfo_str);
                        $msg = '系统检测到您上传的是彩虹系统，已采用彩虹系统方案添加授权代码成功！';
                        break;
                    case $jiuyan:
                        $file = $tempDir . DS . 'includes' . DS . 'common.php';
                        if(!is_file($file)){
                            return message(t('source_package.jiuyan_includes_missing') ,true);
                        }
                        $this->delLastLine($file);
                        $handle = fopen($file, 'a');
                        fwrite($handle, $authcode_str);
                        fclose($handle);
                        file_put_contents($tempDir . DS . 'includes' . DS . 'AuthInfo.php', $authinfo_str);
                        $msg = '系统检测到您上传的是旧言系统，已采用旧言系统方案添加授权代码成功！';
                        break;
                    case $thinkphp5:
                        $file = $tempDir . DS . 'application' . DS . 'common.php';
                        if(!is_file($file)){
                            return message(t('source_package.tp5_application_missing') ,false);
                        }
                        $this->delLastLine($file);
                        $handle = fopen($file, 'a');
                        fwrite($handle, $authcode_str);
                        fclose($handle);
                        file_put_contents($tempDir . DS . 'includes' . DS . 'AuthInfo.php', $authinfo_str);
                        $msg = '系统检测到您上传的是ThinkPHP V5.0，已采用ThinkPHP V5.0系统方案添加授权代码成功！';
                        break;
                    case $thinkphp6:
                        $file = $tempDir . DS . 'app' . DS . 'common.php';
                        if(!is_file($file)){
                            return message(t('source_package.tp5_app_missing') ,false);
                        }
                        $this->delLastLine($file);
                        $handle = fopen($file, 'a');
                        fwrite($handle, $authcode_str);
                        fclose($handle);
                        file_put_contents($tempDir . DS . 'includes' . DS . 'AuthInfo.php', $authinfo_str);
                        $msg = '系统检测到您上传的是ThinkPHP V6.0，已采用ThinkPHP V6.0系统方案添加授权代码成功！';
                        break;
                }
                $zip_name = 'QH-一键添加授权代码盗版追踪' . time() . '.zip';
                $dir_file = $filePath . $zip_name;
                $dir_name = $tempDir;
                $zip = new \ZipArchive;
                $zip->open($dir_file, \ZipArchive::CREATE | \ZipArchive::OVERWRITE);
                try {
                    $files = new \RecursiveIteratorIterator(
                        new \RecursiveDirectoryIterator($dir_name), \RecursiveIteratorIterator::LEAVES_ONLY
                    );

                    foreach ($files as $filename => $file) {
                        if (!$file->isDir()) {
                            $filePath2 = $file->getRealPath();
                            $relativePath = str_replace(DS, '/', substr($filePath2, strlen($dir_name)));
                            $zip->addFile($filePath2, $relativePath);
                        }
                    }
                    unset($files);
                } catch (\Exception $e) {
                    return message(t('source_package.pack_failed'),false);
                }
                return message($msg,true, $zip_name);
            } catch (\Exception $e) {
                return message($e->getMessage() ,false);
            } finally {
                $zip->close();
                @unlink($fname);
            }
        }
    }

    public function download(){
        $name = trim((string)$this->request->get('name'));
        if(empty($name)){
            return $this->render('/public/error', ['msg' => t('archive.name_required')]);
        }
        if ($name !== basename($name) || !preg_match('/^[^\x00\/\\\\]{1,180}\.zip$/iu', $name)) {
            return $this->render('/public/error', ['msg' => t('archive.name_invalid')]);
        }
        $filePath = RUNTIME_PATH . DS . 'temp' . DS . 'upload' . DS . $name;
        if(!is_file($filePath)){
            return $this->render('/public/error', ['msg' => t('archive.not_found')]);
        }
        return download($filePath, $name);
    }

    private function delLastLine($file_path) {
        $file = fopen($file_path, 'r');
        while(!feof($file)) {
            $fp = fgets($file);
            if($fp) {
                $content[] = $fp;
            }
        }
        $content[count($content) - 1] = str_replace('?>', '', end($content));
        fclose($file);//重新写入文件
        $file = fopen($file_path, 'w+');
        fwrite($file, implode("", $content));
        fclose($file);
    }
}
