<?php

return [
    [
        'name' => 'type',
        'title' => t('wxpush_config.interface'),
        'type' => 'radio',
        'content' => [
            t('common.closed'),
            'Server酱',
            'WxPusher',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'server',
        'title' => 'ServerChan',
        'type' => 'array',
        'content' => [],
        'value' => [
            'sendkey' => t('wxpush_config.send_key_placeholder'),
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wxpusher',
        'title' => 'WxPusher',
        'type' => 'array',
        'content' => [],
        'value' => [
            'uid' => t('wxpush_config.uid_placeholder'),
            'apptoken' => t('wxpush_config.app_token_placeholder'),
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => t('common.nice_tips'),
        'type' => 'string',
        'content' => [],
        'value' => t('wxpush_config.help_html'),
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'orange',
    ],
];
