<?php
namespace addons\clearData\controller;

use app\common\controller\Backend;
use think\facade\Cache;
class ClearData extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function clearCache()
    {
        if(IS_POST){
            $type = $this->request->post('type');
            switch ($type){
                case 'menu':
                    Cache::tag('QH_Menu')->clear();
                    break;
                case 'app':
                    Cache::tag('QH_App')->clear();
                    break;
                case 'set':
                    Cache::tag('QH_Set')->clear();
                    break;
                 case 'version':
                    Cache::tag('QH_Version')->clear();
                    break;
                case 'all':
                    Cache::clear();
                    break;
                default:
                    return message(t('cache.type_not_found'), false);
            }
            return message(t('cache.clear_success'), true);
        }
    }
}
