<?php
namespace addons\clearData\controller;

use app\common\controller\Backend;
use think\facade\Cache;
class ClearData extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function clearCache()
    {
        if(IS_POST){
            $type = $this->request->post('type');
            switch ($type){
                case 'menu':
                    Cache::tag('SF_Menu')->clear();
                    break;
                case 'app':
                    Cache::tag('SF_App')->clear();
                    break;
                case 'set':
                    Cache::tag('SF_Set')->clear();
                    break;
                 case 'version':
                    Cache::tag('SF_Version')->clear();
                    break;
                case 'all':
                    Cache::clear();
                    break;
                default:
                    return message('清除失败，不存在此缓存类型！', false);
            }
            return message('清除成功', true);
        }
    }
}